### ISSUE TITLE
clash转换缺少混淆参数

### ISSUE THREAD

**Issue by snipersteve** [tindy2013/subconverter#1]
clashr用了没问题，clash貌似不能识别混淆。转的订阅是ssd，带有混淆参数，但转之后的clash配置里没有。

**Comment by tindy2013** [comment]
@snipersteve 请详细描述你的问题

**Comment by snipersteve** [comment]
![_20191106101417](https://user-images.githubusercontent.com/834498/68305555-d555cb80-00e2-11ea-97ac-c780084f7413.png)
如图，转换ssd订阅后的clash配置，缺少混淆参数。原本是有的。

**Comment by tindy2013** [comment]
@snipersteve 实测没有问题 请检查订阅
