### ISSUE TITLE
clash 转 clash 时，skip-cert-verify 字段会丢失，导致无法连接

### ISSUE THREAD

**Issue by oddcc** [tindy2013/subconverter#100]
用的就是最基本的转换：`http://127.0.0.1:25500/sub?target=clash&url=targetUrl`
下面为了看的清楚一点我没按配置格式贴，但包含的字段信息就是这样的。
这个字段丢失会导致转换后的配置不能用，不知道能否按原样进行转换？我看过文档，好像并没提到自定义的地方。

原 http 配置：
```
name: CN2 香港高级线路
type: http
server: server
port: 3389
password: password
username: username
tls: true
skip-cert-verify: false ## 这一行丢失了
```
转换后 http 配置：
```
name: CN2 香港高级线路
server: server
port: 3389
type: http
username: username
password: password
tls: false ## true -> false
```

原 v2ray 配置：
```
name: CN2 香港高级线路_VMess
type: vmess
server: server
port: 3389
alterId: 0
cipher: auto
uuid: uuid
tls: true
udp: false
network: ws
skip-cert-verify: true ## 这一行丢失了
ws-path: /path
ws-headers:
    Host: limbo.update.microsoft.com
```
转换后 v2ray 配置：
```
name: CN2 香港高级线路_VMess
server: server
port: 3389
type: vmess
uuid: uuid
alterId: 0
cipher: auto
tls: true
network: ws
ws-path: /path
ws-headers: {Host: limbo.update.microsoft.com}
headers: {Host: limbo.update.microsoft.com}
```

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 [node_pref] 部分

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E8%BF%9B%E9%98%B6%E9%93%BE%E6%8E%A5 调用说明 (进阶)

**Comment by oddcc** [comment]
原来还是因为读文档不仔细。。不好意思
非常感谢回复！

**Comment by oddcc** [comment]
使用 scv=false 之后，上面的 v2ray 节点没问题了，tls: true -> true，skip-cert-verify: true 也没有丢失。
但 http 节点还是有问题，会出现 tls: true -> false，skip-cert-verify: true 的情况，在我使用的这个机场中，这样还是无法连接。
请问有没有配置项可以忽略某些字段，就按原样转换呢？

原 http 配置：
```
name: CN2 香港高级线路
type: http
server: server
port: 3389
password: password
username: username
tls: true
skip-cert-verify: false 
```

转换后 http 配置：
```
name: CN2 香港高级线路
server: server
port: 3389
type: http
username: username
password: password
tls: false ## true -> false
skip-cert-verify: true ## false -> true  
```

**Comment by tindy2013** [comment]
Fixed in commit [a3e337c](https://github.com/tindy2013/subconverter/commit/a3e337c56965edc92390a0ca42348cbd9fcb9401)
