### ISSUE TITLE
在远程config里使用过滤规则失效问题

### ISSUE THREAD

**Issue by hiCasper** [tindy2013/subconverter#101]
使用Clash规则输入，其中包含SS及V2Ray节点，在自定义规则（.ini文件）中 `include_remarks` 能够生效，而 `exclude_remarks` 则无法生效，将同样规则应用在GET中的exclude参数又能够生效。

**Comment by tindy2013** [comment]
Fixed in commit [5b492a5](https://github.com/tindy2013/subconverter/commit/5b492a56a1c99daadb9d0b2470b6476b496f0923)
