### ISSUE TITLE
Feature Request: [server] 下加入白名单功能

### ISSUE THREAD

**Issue by luvletter2333** [tindy2013/subconverter#105]
挂在路由器上时，防止局域网内不认识的机器扫描盗取链接

**Comment by luvletter2333** [comment]
可以匹配IP/MAC地址或者均匹配才允许访问

**Comment by tindy2013** [comment]
@luvletter2333 对于这类问题推荐以前置 nginx 进行限制 并反向代理至后端的方式解决

**Comment by luvletter2333** [comment]
但对于这一个小服务来说有一点大动干戈的感觉orz

我试试能不能改一改提一个pr吧

Tindy X <notifications@github.com> 于 2020年3月25日周三 11:08写道：

**Comment by ttimasdf** [comment]
挂路由器上的话就用iptables规则限制一下就好了，

**Comment by luvletter2333** [comment]
以后用上docker应该可以吧 谢了
