### ISSUE TITLE
Feature Request: 当源订阅链接挂掉时返回最后一次成功的结果

### ISSUE THREAD

**Issue by luvletter2333** [tindy2013/subconverter#106]
由于上游不太稳定，有时候会出现源订阅链接失效的情况
这时候subconverter会返回一个错误信息，我的openclash会直接挂掉
请问这时候能否返回上一次成功的结果？

> The following link doesn't contain any valid node info: https://*****.link/link/****************?mu=4

**Comment by luvletter2333** [comment]
在我的openwrt上面，curl 请求订阅链接可以返回正确的结果，但是请求同样运行在openwrt上的subconverter却无法正常返回，请问这可能是什么原因造成的 ？

**Comment by YukawaMi** [comment]
如果能返回上一次的成功结果，那是不是还得做个数据库给存着。。。。。这不太现实
