### ISSUE TITLE
如何通过外部配置文件或参数覆盖 remove_old_emoji 选项

### ISSUE THREAD

**Issue by john-jane-doe** [tindy2013/subconverter#108]
如题，请问如何通过传入外部配置文件或者通过 URL 参数覆盖掉 [`pref.ini`](https://github.com/tindy2013/subconverter/blob/master/base/pref.ini) 中原定义的 [`remove_old_emoji`](https://github.com/tindy2013/subconverter/blob/master/base/pref.ini#L111) 选项？在使用公共 API 时想让 `remove_old_emoji` 选项被修改为 `false`，但似乎通过外部配置文件只能修改 emoji 的对应规则，也没有看到 URL 参数中有关于此的选项。

非常感谢 :pray:

**Comment by tindy2013** [comment]
@john-jane-doe 目前未加入该开关 以后会考虑加入

**Comment by john-jane-doe** [comment]
好的，感谢您的回复

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
2020年3月26日星期四上午10点17分，Tindy X <notifications@github.com> 来信：
