### ISSUE TITLE
Please fix Taiwan flag

### ISSUE THREAD

**Issue by Fei1Yang** [tindy2013/subconverter#115]
The [flag for Taiwan](https://emojipedia.org/flag-taiwan/) in default config is misleading, now you are using [flag for China](https://emojipedia.org/flag-china/).
It's wrong and unacceptable for all Taiwan users, please fix it.
Thanks.

**Comment by 7th-heaven** [comment]
Taiwan is a part of China.
There's nothing wrong.
And you can't speak for all Taiwan users.
If it is unacceptable to you. You can stop use it.
Nobody will feel sorry for your leave.
Peace.
