### ISSUE TITLE
URL 嵌套解析

### ISSUE THREAD

**Issue by caesarjing** [tindy2013/subconverter#117]
例：在Shadowrocket中经过base64编码的
`https://dXNlcm5hbWU6cGFzc3dvcmRAc2VydmVyOnBvcnQ=?remarks=%e4%b8%96%e7%95%8c%e6%9c%80%e5%bf%ab%e7%9a%84%e6%9c%8d%e5%8a%a1%e5%99%a8`
可以被解析为：`https://username:password@server:port?remarks=世界最快的服务器`，但在subconverter里会提示`The following link doesn't contain any valid node info: xxx`

**Comment by tindy2013** [comment]
Added in commit [d06ecdb](https://github.com/tindy2013/subconverter/commit/d06ecdb0105586e955e851b95fa3a84922f8d05a)
