### ISSUE TITLE
远程ruleset读取错误时无提示，并且导致该ruleset丢失。可复现。

### ISSUE THREAD

**Issue by 7th-heaven** [tindy2013/subconverter#118]
0.4.4版本中。当远程ruleset无法读取时，cli无提示，生成的配置文件也无任何提示。

**Comment by tindy2013** [comment]
目前属于预期行为 后续将在发现 Ruleset 获取失败或无内容时在 CLI 打出警告

**Comment by tindy2013** [comment]
Added in commit [79b9211](https://github.com/tindy2013/subconverter/commit/79b9211c7f67f47a3d824da6c8c1fb3768902f25)

**Comment by 7th-heaven** [comment]
> 
> 
> Added in commit [79b9211](https://github.com/tindy2013/subconverter/commit/79b9211c7f67f47a3d824da6c8c1fb3768902f25)

已更新0.5.0，不过如果能在初始化读取rulesets时就提示最好，目前似乎是只会在读取配置时才会提示。而且会间歇出现无法读取远程rulesets的情况，多试几次就能成功，建议在配置中加入retry选项。
