### ISSUE TITLE
请问如何通过正则进行节点名称的排除?

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [tindy2013/subconverter#119]
中文文档中, [clash_proxy_group] 部分, 表示支持使用正则进行节点筛选, 请问如何通过正则表达式进行排除呢?目前尝试了使用  `(^广州$)` 或 `(^(?!广州).*?$)` 这两种写法, 都无法做到排除的功能.

**Comment by tindy2013** [comment]
@Android-AwesomeRoy ^(?!.*?(广州)).*$

**Comment by Android-AwesomeRoy** [comment]
![image](https://user-images.githubusercontent.com/19187129/78253640-4cbf4800-7527-11ea-83d0-376895cef7e4.png)
实验证明并不行啊,

**Comment by tindy2013** [comment]
`*`被当作加粗了 已更新

**Comment by Android-AwesomeRoy** [comment]
> `*`被当作加粗了 已更新

已解决, 感谢~

**Comment by Android-AwesomeRoy** [comment]
> `*`被当作加粗了 已更新
![image](https://user-images.githubusercontent.com/19187129/78258208-75e2d700-752d-11ea-8f51-7718be275356.png)
刚发现了问题,这样写以后, 对应的节点文字并不会在原来的位置, 但是会跑到策略组的最后面.

**Comment by tindy2013** [comment]
你在最后面添加的 `.*` 会将剩余没选上的节点都选上

**Comment by Android-AwesomeRoy** [comment]
> 你在最后面添加的 `.*` 会将剩余没选上的节点都选上

啊对, 刚才发现 这个问题了, 现在没问题啦.~

**Comment by Editing42** [comment]
请问如何匹配包含a且不包含b的节点呢？

**Comment by LM-Firefly** [comment]
@Editing42 a.*(?!b)
