### ISSUE TITLE
配置文件中加入对surge规则组中tolerence参数的支持

### ISSUE THREAD

**Issue by bingsmocha** [tindy2013/subconverter#121]
利用   “custom_proxy_group=✈ 延迟最低`url-test`.*`http://www.gstatic.com/generate_204`500”生成的surge配置文件中规则一般为“XXX = url-test, XXX, XXX, url=http://www.gstatic.com/generate_204, interval=500”，缺少了对tolerance参数的支持；

附：
拥有tolerance参数的实例：XXX = url-test, XXX, XXX, url=http://www.gstatic.com/generate_204, interval=500, tolerance=100
Surge规则中tolerance参数的说明：https://manual.nssurge.com/policy/group.html

非常感谢！

**Comment by tindy2013** [comment]
未来会考虑加入

**Comment by bingsmocha** [comment]
> 未来会考虑加入

好的👌，多谢！

**Comment by tindy2013** [comment]
Added in commit [3d2c8c8](https://github.com/tindy2013/subconverter/commit/3d2c8c8038ca050c05833d23aacd68ad877d9be3)
