### ISSUE TITLE
BUG：使用最新版本或自动构建的版本后，SSSUB的模板功能没有正常运行。

### ISSUE THREAD

**Issue by HuanMeng0** [tindy2013/subconverter#125]
关联ISSUE：https://github.com/tindy2013/subconverter/issues/99

生成的订阅结果没有包含模板内容，如“route”参数。

**Comment by tindy2013** [comment]
实际测试并未出现问题，请提供相关材料

**Comment by HuanMeng0** [comment]
是否需要设置一些的选项才能正常工作？
