### ISSUE TITLE
Surfboard 配置中 USER-AGENT 规则

### ISSUE THREAD

**Issue by AzunyanDaisuki** [tindy2013/subconverter#127]
转换的 Surfboard 配置中会保留有 USER-AGENT 规则，但Surfboard 无法使用这一规则https://manual.getsurfboard.com/#shou-xian-bu-zhi-chi-de-gong-neng

**Comment by tindy2013** [comment]
Fixed in commit [3d2c8c8](https://github.com/tindy2013/subconverter/commit/3d2c8c8038ca050c05833d23aacd68ad877d9be3)
