### ISSUE TITLE
quantumult x 规则转换错误

### ISSUE THREAD

**Issue by sengoku-f** [tindy2013/subconverter#129]
今天刚发现的，quantumult x 不支持`IP-CIDR6`，引用含有`IP-CIDR6`的规则时会报错。
另外，新版api不支持`txt`后缀的规则了？引用`txt`文件规则 quantumult x 会提示`Response invalid`

**Comment by lcysyx** [comment]
还有PROCESS-NAME。之前是会把IP-CIDR6和PROCESS-NAME等QuanX不支持的规则过滤掉的。现在没过滤了，导入QuanX就会报错。

**Comment by KorenKrita** [comment]
同样的情况，processname和ipcid6导致转换为qx时规则订阅无法导入

**Comment by tindy2013** [comment]
Fixed in commit [dada1d4](https://github.com/tindy2013/subconverter/commit/dada1d4b09be23f533ab4c878dcfac0f86ba4473)
