### ISSUE TITLE
mac用户怎么用

### ISSUE THREAD

**Issue by CJianYu** [tindy2013/subconverter#131]
弱弱的问一句，mac用户要怎么使用

**Comment by L0snight** [comment]
@CJianYu 下载mac版本的，运行即可。用法参照README

**Comment by CJianYu** [comment]
![image](https://user-images.githubusercontent.com/18615652/78890199-c3b08f80-7a97-11ea-85a3-052cf055ca84.png)
前三个都是mac版本吗

**Comment by L0snight** [comment]
@CJianYu darwin64

**Comment by CJianYu** [comment]
感谢🙏

**Comment by gg051202** [comment]
感谢🙏
