### ISSUE TITLE
可以为部分节点开启UDP吗

### ISSUE THREAD

**Issue by shenwei101623** [tindy2013/subconverter#135]

**Comment by tindy2013** [comment]
目前还不能细化控制到每个节点

**Comment by printempw** [comment]
同样遇到此问题，可以的话希望后续能考虑一下相关支持

**Comment by sakuyamaij** [comment]
同。机场节点有些udp false有些true，目前sub只能一股脑全开or全关
希望将来能够在导入节点时继承udp参数，和将udp true的节点筛选出来，这两个功能

**Comment by gang4399** [comment]
目前只能自己猥琐，把订阅节点按自己的了解情况重命名 注释UDP和留空。留空的节点手写替换。

如果要直接通过订阅实现，因无法探测服务器是否支持，同一节点订阅手动正则式分两份输出节点，一份%udp=true一份留空。之后能不能直接合并或之后客户端怎么合并我就不知道了。哈哈哈哈。其实这需求我也喜欢

**Comment by gang4399** [comment]
> 同。机场节点有些udp false有些true，目前sub只能一股脑全开or全关
> 希望将来能够在导入节点时继承udp参数，和将udp true的节点筛选出来，这两个功能

如果是获得的节点已经定义了udp TRUE or FALSE 那sub订阅转换时不做udp定义即可 继承原节点定义。

但多机场节点有无udp定义的混合情况的话就不清楚了。

**Comment by snachx** [comment]
udp-relay 可不可以优先继承订阅里面的设置啊？如果订阅里面没有设置才应用统一的开启或者关闭

**Comment by NinjaUmbra** [comment]
@snachx 这个需要clash核心作出改动 sub才方便做进一步修改 目前github好像有人提了 你可以去看看

**Comment by zhongfly** [comment]
如果不指定udp的话(即url参数不包含udp=true或udp=false）会保留订阅里的设置
