### ISSUE TITLE
404 File not found.

### ISSUE THREAD

**Issue by shmilwdc** [tindy2013/subconverter#136]
docker-compose方式部署，subconverter没有暴露端口，nginx直接反代到subconverter的容器名，通过nginx访问报404，返回File not found.。但是进入nginx容器内curl subconverter:25500正确返回subconverter v0.5.1 backend

**Comment by Mit2g** [comment]
```
echo "subconverter网址 {
 gzip
 tls /root/ssl/api.bianyuan.xyz_chain.crt /root/ssl/subconverter网址_key.key
 proxy / 8.8.8.8:25500 {
    websocket
    header_upstream Host {host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Port {server_port}
    header_upstream X-Forwarded-Proto {scheme}
  }
}
```
caddy使用以上方法可行 但是nginx也是同样不行 初步判断是设置nginx的websocket只传出而没有传入
`curl 反代地址:25500?/sub?target=%TARGET%&url=%URL%&config=%CONFIG% `可以复现`curl 反代地址:25500`返回_版本号_ 而如上curl返回_file not found_的情况

**Comment by ngstyle** [comment]
字符串拼接的url 出错了。。

**Comment by ngstyle** [comment]
拼接的url 格式不对了
25500?/sub?target=%TARGET%&url=%URL%&config=%CONFIG% curl返回file not found的情况

25500 后面的? 去掉
