### ISSUE TITLE
能否添加html？

### ISSUE THREAD

**Issue by wk989898** [tindy2013/subconverter#139]
能否添加一个简单的网页来实现转换？
看着文档输有点慢，而且还需要encode url

**Comment by CareyWang** [comment]
@wk989898 https://gfwsb.114514.best/

**Comment by wk989898** [comment]
> @wk989898 https://gfwsb.114514.best/

这种我不是很信任，本地连接放心

**Comment by tindy2013** [comment]
我开的也不放心¿

**Comment by wk989898** [comment]
> 我开的也不放心¿

收到！
