### ISSUE TITLE
能否在输出时对含特殊字符的 value 增加引号？

### ISSUE THREAD

**Issue by Howard-00** [tindy2013/subconverter#14]
如题，pyyaml 等库在 Ordered Dict 类型 （key: value）中，如果 value 含冒号就会报错，如部分机场的节点名、ssr 类型代理的 protocolparam 参数等。因此为了提高兼容性，希望作者可以对含有特殊符号的 value 加上引号，以便和其他工具配合使用。

**Comment by tindy2013** [comment]
@Howard-00 未来再考虑加入

**Comment by Howard-00** [comment]
已通过替换 pyyaml 库解决
