### ISSUE TITLE
订阅转换到clash snell节点消失

### ISSUE THREAD

**Issue by joshuawm** [tindy2013/subconverter#143]
使用subconvert转换时，远程配置文件含有snell节点，进行转换后消失。
测试含有snell节点的远程配置文件在clash for Windows使用正常，但是在转换后的文件里面消失

**Comment by tindy2013** [comment]
Added in commit [52c8eff](https://github.com/tindy2013/subconverter/commit/52c8eff182f6c831264fa90a6b13b0eb852b7a17)

**Comment by joshuawm** [comment]
更新已解决 
感谢
