### ISSUE TITLE
clash更新了，字段需要修改

### ISSUE THREAD

**Issue by wulifuji** [tindy2013/subconverter#146]
版本0.9.8
![image](https://user-images.githubusercontent.com/61496038/80270557-bd532200-86eb-11ea-970a-6876e5fd97ce.png)

**Comment by L0snight** [comment]
@wulifuji 目前直接在url后加&new_name=true,或者直接改配置文件clash_use_new_filed_name,或者通过template功能都可以生成新字段名的配置

**Comment by wulifuji** [comment]
already SOLVED
