### ISSUE TITLE
在自定义profile中，类TG协议不生效

### ISSUE THREAD

**Issue by wontdoanything** [tindy2013/subconverter#149]
最新发布的release版本

类 TG 代理的 HTTP/Socks 链接 由于没有命名设定，所以可以在后方插入&remark=进行命名，例如

tg://http?server=1.2.3.4&port=233&user=user&pass=pass&remark=Example

https://t.me/http?server=1.2.3.4&port=233&user=user&pass=pass&remark=Example

这条规则中，remark命令部分在自定义profile中未安remark生成想要的名称

即时我是用
http://127.0.0.1:25500/sub?target=clash&url=tg%3A%2F%2Fhttp%3Fserver%3D1.2.3.4%26port%3D233%26user%3Duser%26pass%3Dpass%26remark%3DExample

生成的proxy节点，也是

Proxy:
  - {name: 1.2.3.4:233, server: 1.2.3.4, port: 233, type: http, username: user, password: pass, tls: false}

**Comment by tindy2013** [comment]
@wontdoanything 未更新 README 实应为 remarks=xxx

**Comment by wontdoanything** [comment]
好的，我试下，我想请教下，我想在google组中去除网易音乐解锁的节点，目前有这样的支持吗？如果有，能给我参考下吗？目前我只找到类似include规则，是否存在我前面说的exclude的规则

**Comment by tindy2013** [comment]
@wontdoanything ^(?!.*?(关键词)).*$

**Comment by wontdoanything** [comment]
> @wontdoanything ^(?!._?(关键词))._$

我没表达清楚，是这里

**Comment by wontdoanything** [comment]
> @wontdoanything ^(?!._?(关键词))._$

我没表达清楚，是这里

**Comment by wontdoanything** [comment]
我没表达清楚，比方说这个文件groups_forcerule.txt文件，

**Comment by Mit2g** [comment]
> 我没表达清楚，比方说这个文件groups_forcerule.txt文件，
> 动画疯`select`(Taiwan|深台|彰化|新北|台)
> 匹配这些关键字，有剔除关键字的吗？我不需要一些节点

https://github.com/tindy2013/subconverter/issues/119

**Comment by wontdoanything** [comment]
按照119里的方法，可以了，感谢作者
