### ISSUE TITLE
导出surge4 ios 出现 invalid line

### ISSUE THREAD

**Issue by Jerry0527** [tindy2013/subconverter#15]
导出surge4 ios 出现 invalid line:
![20191203_025125000_iOS](https://user-images.githubusercontent.com/28797671/70016353-0ed30700-15bb-11ea-9a1e-ea38a6984d4f.png)

![Snipaste_2019-12-03_10-53-59](https://user-images.githubusercontent.com/28797671/70016419-417cff80-15bb-11ea-9bf1-4a3f1f5fd0be.png)

**Comment by tindy2013** [comment]
Commit [f31508c](https://github.com/tindy2013/subconverter/commit/f31508c72c163fcef25655e0e67c57637c58c804) 已修复该bug

**Comment by Jerry0527** [comment]
可以打包release一下吗，我看最新版本的release是9天前的,代码是8天前改的

**Comment by tindy2013** [comment]
@Jerry0527 今天晚些时候将放出 release

**Comment by Jerry0527** [comment]
好的，多谢
