### ISSUE TITLE
远程配置里洞主规则，global tv策略组对于netflix不生效，还是会走proxy的

### ISSUE THREAD

**Issue by huangshayang** [tindy2013/subconverter#150]
![image](https://user-images.githubusercontent.com/22701466/80345014-0d241b80-889b-11ea-8232-d84a3b0c4481.png)
![image](https://user-images.githubusercontent.com/22701466/80345064-1dd49180-889b-11ea-96e8-45f97ae6e0bc.png)
设置了美国，结果还是走的香港，节点没问题。Disney+、hulu、hbo now都能正确

**Comment by huangshayang** [comment]
global tv里好像没有加入netflix的

**Comment by tindy2013** [comment]
Fixed in the [latest revision](https://gist.github.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/revisions)
