### ISSUE TITLE
建议托管地址适配clash for window v0.9.7以后的版本

### ISSUE THREAD

**Issue by coderloverXH** [tindy2013/subconverter#155]
建议托管地址适配clash for window v0.9.7以后的版本，虽然我知道在url后面手动加上&new_name=true即可解决，但是如果能适配clash for window v0.9.7以后的版本就更好了。
适配举例：
![适配](https://user-images.githubusercontent.com/63088614/80562597-b8a7aa00-8a1a-11ea-9dc1-16284218158e.png)

**Comment by tindy2013** [comment]
Already added `Clash 新字段名` option in `更多选项`, you may need to `重置所有设置` to make it work .
