### ISSUE TITLE
如何设置Nginx使用子路径反代到Sub后端端口上使用？

### ISSUE THREAD

**Issue by jerrell851** [tindy2013/subconverter#159]
目前我用Nginx设置反代到域名的 / 上是可以正常使用SUB后台的。但这样会浪费一个子域名而且我觉得隐私性不够友好，我尝试设置反代到 子路径 未果，请作者指点一下：

子路径Nginx的反代设置：
    location /web {
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #8888端口是我设置的sub监听端口
        proxy_pass      http://127.0.0.1:8888; 
    }  

pref.ini里的相关设置：
managed_config_prefix= http://127.0.0.1:8888
port=8888

以上设置后，访问： http://domain.com/web，提示 invaild request
如果访问 http://domain.com/web/sub?target.....，则返回 file not found。
而我知道，反代如果正确的话应该是返回：subconverter v0.5.1 backend

折腾了几天，没搞定，麻烦你了，谢谢！

**Comment by tindy2013** [comment]
```
location ^~ /web/ {
    proxy_pass http://127.0.0.1:8888/;
}
```
除此以外，不需要设置 `Connection: upgrade` 等 Header，因为 SubConverter 并不是使用 WebSocket 进行通信的。

**Comment by jerrell851** [comment]
我正准备上来填平这个坑，谢谢作者，我早上调试的时候已经发现问题，其实有没有header这些都不重要，重要的是反代的路径（http://127.0.0.1:8888/）后面一定要有 / 符号，否则会把反代前的字符传递到后面导致 invaild request。 所以我问题解决啦，非常感谢tindy！
