### ISSUE TITLE
clash转clash会丢失ss的obfs

### ISSUE THREAD

**Issue by ijglb** [tindy2013/subconverter#16]
转换前：
`- {"name":"ss","type":"ss","server":"a.com","port":1234,"cipher":"aes-128-gcm","password":"1234","plugin":"obfs","plugin-opts":{"mode":"http","host":"docs.microsoft.com"}}`

转换后：
`- {type: ss, cipher: aes-128-gcm, password: 1234, name: ss, server: a.com, port: 1234}`

**Comment by tindy2013** [comment]
fixed on commit [df909bd](https://github.com/tindy2013/subconverter/commit/df909bdb60ceb277ec495382e6b4b7e722810a19)
