### ISSUE TITLE
config 参数不生效，无法使用自定义分组

### ISSUE THREAD

**Issue by gumutianqi** [tindy2013/subconverter#161]
使用自定义的其他 Config 参数之后，并没有生效，最后发现问题在这里：

```
# pref.ini 文件第 170 行
custom_proxy_group=!!import:snippets/groups.txt
```
这里定义的 groups.txt 决定了只使用 snippets/groups.txt 里面定义的分组，自己改了一下，新增了一个groups_full.txt，发现文件能生成，但是 ClashX不工作了。

**Comment by Mit2g** [comment]
直接把原本的注释掉 替换为你的
