### ISSUE TITLE
生成的QuantumultX订阅内容能否使用自订URL而不是127.0.0.1:25500

### ISSUE THREAD

**Issue by phlinhng** [tindy2013/subconverter#164]
这是生成的QuantumultX配置中的一部分
```
[filter_remote]
http://127.0.0.1:25500/getruleset?type=2&url=cnVsZXMvTG9jYWxBcmVhTmV0d29yay5saXN0&group=8J-OryDlhajnkIPnm7Tov54, tag=🎯 全球直连, enabled=true
http://127.0.0.1:25500/getruleset?type=2&url=cnVsZXMvTVNTZXJ2aWNlcy5saXN0&group=4pOC77iPIOW-rui9r-acjeWKoQ, tag=Ⓜ️ 微软服务, enabled=true
http://127.0.0.1:25500/getruleset?type=2&url=cnVsZXMvQ29ubmVyc0h1YS9TdXJnZS9SdWxlc2V0L1VuYnJlYWsubGlzdA&group=8J-OryDlhajnkIPnm7Tov54, tag=🎯 全球直连, enabled=true
```
我的API是部署在公网上的，请问要去哪里修改配置文件把`http://127.0.0.1:25500`换成`https://myapi.com`？

**Comment by tindy2013** [comment]
[配置文件](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中 `[managed_config]` 部分的 `managed_config_prefix`

**Comment by phlinhng** [comment]
> [配置文件](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中 `[managed_config]` 部分的 `managed_config_prefix`

已成功，感謝說明！

**Comment by eicky** [comment]
> [配置文件](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中 `[managed_config]` 部分的 `managed_config_prefix`

请问docker怎么把这个路径映射一下呢？

**Comment by golezi** [comment]
> managed_config

提个小建议
能不能改成默认为当前请求的prefix

**Comment by LiweiDong** [comment]
> > managed_config
> 
> 提个小建议 能不能改成默认为当前请求的prefix

附议。 遇到同样的问题 找到这里解决

**Comment by han3sui** [comment]
遇到同样的问题，并且docker好像没有暴露这个参数出来，只能进内部修改文件？
