### ISSUE TITLE
自定义规则路径不生效

### ISSUE THREAD

**Issue by cnperi** [tindy2013/subconverter#165]
本地生成配置文件时，external_config.yml中的规则自定义路径不生效
「clash_rule_base: myfiles/test/custom_clash_rules.yml」
无效，只有
「clash_rule_base: base/custom_clash_rules.yml」
才有效

**Comment by cnperi** [comment]
同样的，emoji参数也不生效，无论是放在自定义路径下，还是放到snippet路径下，必须修改初始的snippet/emoji.txt才能生效。

**Comment by tindy2013** [comment]
1. 如需要指向其他目录  请修改 `pref` 中 `base_path` 的路径
2. 已知问题  下个版本修复
