### ISSUE TITLE
group参数没用，错误匹配了remarks参数

### ISSUE THREAD

**Issue by uoox** [tindy2013/subconverter#166]
文档里面写到：

> 类 TG 代理的 HTTP/Socks 链接由于没有命名设定，所以可以在后方插入&remarks=进行命名，同时也可以插入 &group= 设置组别名称，以上两个参数需要经过 URLEncode 处理，例如
> 
> tg://http?server=1.2.3.4&port=233&user=user&pass=pass&remarks=Example&group=xxx
> 
> https://t.me/http?server=1.2.3.4&port=233&user=user&pass=pass&remarks=Example&group=xxx

实际情况是group参数没有用，与remarks参数相匹配了（也就是remarks既是name又是group开头）

**Comment by tindy2013** [comment]
预期行为 并没有错误
