### ISSUE TITLE
quanx base [policy] 不支持 ssid 方式.

### ISSUE THREAD

**Issue by shao222** [tindy2013/subconverter#167]
你好! 我在base.conf文件中, 参照其他 static= 方式写了如下规则, 但无效果.
```
ssid=📡 无线选择, direct, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/SSID.png
```
ssid 改为 static 也是如此, 无法在最终配置文件中加载 img-url 字段.

谢谢!

btw: 在quanx的自定义 custom_proxy_group 书写格式和默认的有误
如下才是正确的方式, 可以被quanx 识别配置文件.
```
custom_proxy_group=📡 无线选择`ssid`🔰 节点选择`🔰 节点选择,WIFI-SSID=DIRECT
```

**Comment by tindy2013** [comment]
Fixed in commit [54747a3](https://github.com/tindy2013/subconverter/commit/54747a3268d805755838252e092a0c6e97a69904)
