### ISSUE TITLE
在线订阅转换ssr节点，如果为全数字密码，则转换后password多了个!<str> 导致错误

### ISSUE THREAD

**Issue by HorrZzz** [tindy2013/subconverter#168]
例如密码为111111
转换后password: !<str> 111111

**Comment by tindy2013** [comment]
预期行为 用于标记密码为字符串  Clash Core 可正常解析 不存在问题

**Comment by HorrZzz** [comment]
> 预期行为 用于标记密码为字符串 Clash Core 可正常解析 不存在问题

好吧。谢谢
