### ISSUE TITLE
希望在[profile]中支持rename功能

### ISSUE THREAD

**Issue by leechiuccc** [tindy2013/subconverter#169]
[profile]中，只能使用一条rename规则，若添加多个rename，则只生效最后一条

虽然可把rename规则全写到pref.ini的rename_node上，但把多家✈️的规则写上去势必会互相混淆

**Comment by tindy2013** [comment]
URL 参数中的 `rename` 格式如下 ( 内容须先进行 URLEncode 处理 ) ：
```
&rename=match1@replace1`match2@replace2`...
```

**Comment by tindy2013** [comment]
除此以外还可使用 [外部配置文件](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE)
