### ISSUE TITLE
跑不起来....运行以后IP是0.0.0.0

### ISSUE THREAD

**Issue by leominor46** [tindy2013/subconverter#17]
windows环境,打开以后ip是0.0.0.0 访问localhost无法访问,是使用姿势不对吗?

![image](https://user-images.githubusercontent.com/57203372/70292408-290a2080-1819-11ea-9ef9-b21743246c8c.png)

**Comment by tindy2013** [comment]
![image](https://user-images.githubusercontent.com/49061470/70292548-81412280-1819-11ea-95b1-7c45450140a5.png)
你端口呢

**Comment by leominor46** [comment]
> ![image](https://user-images.githubusercontent.com/49061470/70292548-81412280-1819-11ea-95b1-7c45450140a5.png)
> 你端口呢
![image](https://user-images.githubusercontent.com/57203372/70292788-23f9a100-181a-11ea-9142-9f21c054978d.png)
gan感谢大佬回复,都加上了的 但是访问不到服务的感觉

**Comment by tindy2013** [comment]
你命令行窗口选定了 会暂停的

**Comment by leominor46** [comment]
好了...是我太菜了.. 
谢谢大佬了!

**Comment by PYniang** [comment]
@tindy2013 @tindy2013 臭tindy趕快給我定制測速軟件！
