### ISSUE TITLE
能否使用一份txt中添加所有的订阅链接

### ISSUE THREAD

**Issue by sengoku-f** [tindy2013/subconverter#181]
能否将多份订阅链接写入一份`txt`文件中
api使用`txt`文件链接
这样就不用每次都在网页上填入很多链接，而且可以缩短订阅链接长度

**Comment by Mit2g** [comment]
请阅读[这部分](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%A1%A3%E6%A1%88) 从而使用`ini`来实现你的设想
