### ISSUE TITLE
code.createjs.com被错误屏蔽

### ISSUE THREAD

**Issue by Oyami-Srk** [tindy2013/subconverter#182]
createjs提供了一些用于渲染HTML5界面的模组，其中code.createjs.com被AdRule错误屏蔽

https://github.com/tindy2013/subconverter/blob/c77f064e882797a73c01be38d773eb0584fc81da/base/rules/NobyDa/Surge/AdRule.list#L2252

**Comment by tindy2013** [comment]
请向 [上游](https://github.com/NobyDa/Script) 提交 Issue
