### ISSUE TITLE
从请求地址或者环境变量中动态获取managed_config_prefix

### ISSUE THREAD

**Issue by jinyu121** [tindy2013/subconverter#186]
可能对Docker/群晖会更友好一些。

**Comment by jinyu121** [comment]
找到了 profile_data 这个参数，能解决问题

**Comment by jinyu121** [comment]
但是这个参数对 只针对Surge第一行起作用（就是那个Managed什么什么的），RULE-SET里面的URL依然用的是managed_config_prefix

https://github.com/tindy2013/subconverter/blob/0a7e1cac97d08a20ece58b4789bf98257d8f5da7/src/subexport.cpp#L1654

**Comment by Mit2g** [comment]
> 但是这个参数对 只针对Surge第一行起作用（就是那个Managed什么什么的），RULE-SET里面的URL依然用的是managed_config_prefix
> 
> https://github.com/tindy2013/subconverter/blob/0a7e1cac97d08a20ece58b4789bf98257d8f5da7/src/subexport.cpp#L1654

可以使用[此处](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E-%E8%BF%9B%E9%98%B6)提到的 ***expand*** 参数来直接将ruleset中url拉取为规则 从而规避这个问题

**Comment by nb5p** [comment]
@Mit2g 你弄个域名解析到该IP，再把域名写入配置文件，可以解决此问题

**Comment by tindy2013** [comment]
Added in commit ee6de60223f31b4a1ba2507f9619859a793c73dc
