### ISSUE TITLE
请问可以在 insert_url 中插入自定义的 vmess 节点吗？

### ISSUE THREAD

**Issue by oddcc** [tindy2013/subconverter#189]
如题，只搜到了http和socks的写法

**Comment by tindy2013** [comment]
请按照 [v2rayN 分享链接 ver.2](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)) 中的格式添加

**Comment by LunaticTian** [comment]
在insert_url 或者 单独的mkcp vmess节点会被过滤无法加入
