### ISSUE TITLE
最新版本无法获取订阅节点

### ISSUE THREAD

**Issue by XinSSS** [tindy2013/subconverter#196]
同样的`generate.ini`0.5.2使用没问题, 刚试了下0.6.0, 无法生成配置, 显示: The following link doesn't contain any valid node info.

订阅链接肯定是能拿到节点的, 但是出现这样的提示我不知道是哪里出了问题

**Comment by QuteSaltyFish** [comment]
我也遇到了这个问题，很烦

**Comment by Twor** [comment]
+1

**Comment by tindy2013** [comment]
说清楚什么订阅 提供更详细的信息很难？
很难我就直接 Close 了

**Comment by XinSSS** [comment]
@tindy2013 一直用的ssr订阅链接,之前一直都正常
![iShot2020-07-1015 38 25](https://user-images.githubusercontent.com/30732527/87129279-a15f2580-c2c3-11ea-8563-17321fb0543d.png)

**Comment by XinSSS** [comment]
@tindy2013 
试了下最新版本0.6.1订阅没有问题, 但是生成文件的文件名还有点小问题 , 如下图
![Snipaste_2020-07-11_16-45-55](https://user-images.githubusercontent.com/30732527/87220427-20bd2980-c396-11ea-81dc-eaebbd797217.png)

generate.ini是UTF-8编码
不清楚别的平台上是否有这个问题

**Comment by cnperi** [comment]
我也碰上这个问题了。
本地转换时，profile.ini文件里面，url填写在线地址，会出现一下错误：

**Comment by tindy2013** [comment]
> @tindy2013
> 试了下最新版本0.6.1订阅没有问题, 但是生成文件的文件名还有点小问题 , 如下图
> ![Snipaste_2020-07-11_16-45-55](https://user-images.githubusercontent.com/30732527/87220427-20bd2980-c396-11ea-81dc-eaebbd797217.png)
> 
> generate.ini是UTF-8编码
> 不清楚别的平台上是否有这个问题

在 Windows 下中文文件名默认使用 GBK 编码。可以使用 ANSI 格式保存 `generate.ini` 来解决该问题。

**Comment by oddcc** [comment]
> 我也碰上这个问题了。
> 本地转换时，profile.ini文件里面，url填写在线地址，会出现以下错误：
> Artifact 'xxx-clash' generate ERROR! Reason: The following link doesn't contain any valid node info: https://xxxxxxx.net/link/asdfgasdfasdfadsf?mu=40
> 
> 把订阅文件下载下来放到本地，把profile.ini文件的url填写上本地路径，则正常。
> 
> # 确认机场地址没被墙。
> 我自己的锅。

@cnperi 请问最终是如何解决的？

**Comment by cnperi** [comment]
> > 我也碰上这个问题了。
> > 本地转换时，profile.ini文件里面，url填写在线地址，会出现以下错误：
> > Artifact 'xxx-clash' generate ERROR! Reason: The following link doesn't contain any valid node info: https://xxxxxxx.net/link/asdfgasdfasdfadsf?mu=40
> > 把订阅文件下载下来放到本地，把profile.ini文件的url填写上本地路径，则正常。
> > # 确认机场地址没被墙。
> > 我自己的锅。
> 
> @cnperi 请问最终是如何解决的？

链接引用错误，改过来就好了。
