### ISSUE TITLE
香港旗

### ISSUE THREAD

**Issue by cliuff** [tindy2013/subconverter#197]
为何香港不是中国旗？

**Comment by NevadaCities** [comment]
@cliuff 香港区旗

**Comment by cliuff** [comment]
@NevadaCities 特区就能与国家相并列？

**Comment by NevadaCities** [comment]
@cliuff 香港特别行政区属于特别行政区域，与澳门是一个等级的。有自己的区旗与区徽。台湾本身是一个省份而不是归属于特别行政区域，至于为什么是省份，因为国民年代的历史遗留问题。

**Comment by NevadaCities** [comment]
@cliuff 可以查询特别行政区域在国家法律中的相关条例，江泽民所说的一国两制并不是你一个人就能把香港特别行政区改成香港省的。

**Comment by EKyero** [comment]
同样使用🇨🇳会与台湾出现混淆，容易后续识别上会造成困扰
在某品牌的**国行设备** 上，🇭🇰和🇲🇴也是可以正常显示的

**Comment by NevadaCities** [comment]
@NevadaCities 基本法 第十条 香港特别行政区除悬挂中华人民共和国国旗和国徽外，还可使用香港特别行政区区旗和区徽。
