### ISSUE TITLE
是否考虑通过submodule的方式导入三方rules

### ISSUE THREAD

**Issue by rhettor** [tindy2013/subconverter#198]
人工同步rules感觉比较麻烦，感觉采用submodule的方式感觉要轻松些。

目前老版本神机规则已经停止更新，新版规则是[DivineEngine/Profiles](https://github.com/DivineEngine/Profiles/tree/master)，那么通过submodule的方式替换规则也比较方便。

**Comment by tindy2013** [comment]
由于大部分源仓库中除 Rulesets 外，其他大部分文件都未使用。因此为了减少发布的 Releases 的体积，Rulesets 会进行手动更新。

**Comment by rhettor** [comment]
@tindy2013 那只有辛苦了
