### ISSUE TITLE
节点过多会提示 URI Too Large

### ISSUE THREAD

**Issue by ysneo** [tindy2013/subconverter#201]
![image](https://user-images.githubusercontent.com/17615113/86759525-2bff1500-c077-11ea-88bd-8e9689b67cc2.png)

**Comment by tindy2013** [comment]
请不要直接向公共 API 传入大量单链接。使用提供的订阅地址，或在未有订阅地址的情况下自行合并链接为订阅格式，并用文本托管平台存放。
