### ISSUE TITLE
ss带obfs参数的链接在转换成target=surge&ver=4会被丢失

### ISSUE THREAD

**Issue by rhettor** [tindy2013/subconverter#206]
**Mac版surge支持ss的obfs参数，但是在转换成surge订阅的时候会被丢失。**
![CleanShot 2020-07-13 at 17.55.20@2x.png](https://i.loli.net/2020/07/13/nsKliWD1Y6Lc2Tf.png)

**Comment by tindy2013** [comment]
未提供任何详细信息，该 Issue 将被直接关闭。
