### ISSUE TITLE
ssd:// 问题

### ISSUE THREAD

**Issue by Forty-nine** [tindy2013/subconverter#207]
我的 机场 订阅 信息 是 ssd:// 开头 后面是 编码 信息

像是 墙洞 等的 subconverter 可以 转换 clash

我的 就提示 没有 有效 节点。

有谁知道问题所在吗？

**Comment by tindy2013** [comment]
非标准 SSD 订阅将可能无法解析。请联系你的节点提供商更换为标准 SSD 订阅，或是提供该订阅的详细信息。
