### ISSUE TITLE
转换订阅时出现了the following link doesn't contain any valid node info:

### ISSUE THREAD

**Issue by CosmoZzZzZzZ** [tindy2013/subconverter#209]
以前用还是正常的

**Comment by CosmoZzZzZzZ** [comment]
详细描述
某家机场给的是base64加密的订阅
再未解密时，添加至ClashXR 显示为空。打开yaml文件显示the following link doesn't contain any valid node info:xxxxxxxxx
解密后变成ssr单链接 转换后显示error502 ClashXR软件显示托管配置文件格式不正确: yaml: line 9: mapping values are not allowed in this context

求大佬解决！！
谢谢您！

**Comment by AidenLx** [comment]
+1

**Comment by CosmoZzZzZzZ** [comment]
突然发现使用本地版localhost:25500没有问题
只有在线转换有这个问题

**Comment by rbforelle** [comment]
我也碰到一样的问题,机场给的订阅链接是base64加密的,我刚试了下https://subconverter.herokuapp.com这个可以转,其他的好像都不行

**Comment by CosmoZzZzZzZ** [comment]
> 我也碰到一样的问题,机场给的订阅链接是base64加密的
> 我刚试了下[https://subconverter.herokuapp.com这个可以转,其他的好像都不行](https://subconverter.herokuapp.com%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E8%BD%AC,%E5%85%B6%E4%BB%96%E7%9A%84%E5%A5%BD%E5%83%8F%E9%83%BD%E4%B8%8D%E8%A1%8C)

多谢大佬！

**Comment by OpenWaygate** [comment]
> 我也碰到一样的问题,机场给的订阅链接是base64加密的
> 我刚试了下[https://subconverter.herokuapp.com这个可以转,其他的好像都不行](https://subconverter.herokuapp.com%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E8%BD%AC,%E5%85%B6%E4%BB%96%E7%9A%84%E5%A5%BD%E5%83%8F%E9%83%BD%E4%B8%8D%E8%A1%8C)

这个好像不支持clash的新参数...

**Comment by tindy2013** [comment]
部分机场会对公共 API 的 IP 进行封禁，导致无法正常获取订阅信息。如有需要可自建或使用其他公共 API 。

**Comment by CosmoZzZzZzZ** [comment]
> 部分机场会对公共 API 的 IP 进行封禁，导致无法正常获取订阅信息。如有需要可自建或使用其他公共 API 。

多谢大佬
