### ISSUE TITLE
带obfs参数的SS订阅转化失败

### ISSUE THREAD

**Issue by flyingwhitewhale** [tindy2013/subconverter#210]
目前手头几个带obfs参数的机场，利用电脑端0.6.1转化为ios客户端配置失败，问题如下

1）prefer.ini的default_url**使用sip002订阅情况**下
A机场转化为surge/quanx后，配置文件里A机场节点完全不显示，B机场正常。（而转化为clash配置文件AB均正常）。
通过分析SIP002中节点信息，发现如下不同
A机场节点
ss://xxx@xxx:port/?plugin=obfs-local%3Bobfs%3Dhttp%3Bobfs-host%3Dxxx#
B机场节点
ss://xxx@xxx:port/?plugin=simple-obfs%3Bobfs%3Dhttp%3Bobfs-host%3Dxxx#
继续对比其他几个带ofbs的机场，证实，**节点信息含plugin=obfs-local的均转化失败。**

2）pref.ini的default_url**改用clash订阅，则AB机场均能正常转化**到最终ios客户端配置文件。

希望大佬能帮忙解答下问题，谢谢

**Comment by suili** [comment]
> **节点信息含plugin=obfs-local的均转化失败。**

我遇到了同样的问题。

**Comment by flyingwhitewhale** [comment]
> > **节点信息含plugin=obfs-local的均转化失败。**
> 
> 我遇到了同样的问题。

t大最新的commit已经解决了这个问题，等更新release或使用t大的官方api吧
