### ISSUE TITLE
TAG参数如何使用？

### ISSUE THREAD

**Issue by leic4u** [tindy2013/subconverter#214]
根据0.6.0版本的更新记录，显示已支持对订阅打`TAG`，用于对该链接的节点进行重命名，看了`README`好像还没有更新`TAG`的使用方法，我尝试在参数里加`%26tag=XXX`来赋值，没有成功，请大佬讲解一下`TAG`参数如何使用呢？

**Comment by tindy2013** [comment]
@leic4u url=tag:airport,https://example.com/subscription

**Comment by leic4u** [comment]
@tindy2013 需要对符号进行encode编码吗？

**Comment by leic4u** [comment]
@tindy2013 测试了下不用encode就可以获取节点了，但是在外部配置文件中应该怎么配呢，我用了
```rename=!!tag:xxx!!^@[XXX]```
```rename=!!tag=xxx!!^@[XXX]```
```rename=!!TAG=xxx!!^@[XXX]```
这三种方式都不行

**Comment by leic4u** [comment]
转 #215
