### ISSUE TITLE
Clash转换报错 -- Template render failed!

### ISSUE THREAD

**Issue by am1006** [tindy2013/subconverter#216]
在请求 `http://127.0.0.1:25500/sub?target=clash&url=https%3A......` 之后，得到：

```
Template render failed! Reason: [inja.exception.render_error] (at 9:7) variable 'request.clash.dns' not found
```

仔细查了所有issue，发现之前没有人碰到过这个情况。Google了也没有得到答案。我使用的是docker环境，直接pull的，没有任何更改。

感谢任何帮助!

**Comment by am1006** [comment]
Follow up: 测试了surge作为target，是正常的。

**Comment by tindy2013** [comment]
@am1006 latest tag 中部分功能可能出现了问题 可以先使用 0.5.1 tag

**Comment by am1006** [comment]
好的！我今晚再测试下，看看能从log里找到什么。
真的很感谢！

**Comment by Snowflake-Pink** [comment]
> @am1006 latest tag 中部分功能可能出现了问题 可以先使用 0.5.1 tag

相同问题，顺便想问下现在支持旧 `Clash` 转新 `Clash` 配置文件格式的功能吗？@

**Comment by testforme233** [comment]
> @am1006 latest tag 中部分功能可能出现了问题 可以先使用 0.5.1 tag

相同问题，但是今天clash内核更新支持ssr，请问如何使用0.5.1tag使得clash支持ssr

**Comment by am1006** [comment]
我实测 0.6.1 Release 正常使用。建议docker使用者不要直接pull latest。

**Comment by hardy-one** [comment]
连接加上&clash.dns=1或者在all_base.tpl删除相关语句，应该可以。

**Comment by Mit2g** [comment]
> > @am1006 latest tag 中部分功能可能出现了问题 可以先使用 0.5.1 tag
> 
> 相同问题，顺便想问下现在支持旧 `Clash` 转新 `Clash` 配置文件格式的功能吗？@

https://github.com/tindy2013/subconverter/issues/220

**Comment by ztyzbb** [comment]
请问现在是否支持Clash 1.x 版本的配置文件？
[breaking changes in 1.0.0](https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0)

**Comment by Mit2g** [comment]
> 请问现在是否支持Clash 1.x 版本的配置文件？
> [breaking changes in 1.0.0](https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0)

#duplicate https://github.com/tindy2013/subconverter/issues/225#issuecomment-664744653
