### ISSUE TITLE
能从ssr转其他类型吗，链接该怎么填？

### ISSUE THREAD

**Issue by qliang0816** [tindy2013/subconverter#22]
如题

**Comment by tindy2013** [comment]
@qliang0816 直接和其他订阅一样填入 不同target会自动选择支持的节点类型

**Comment by qliang0816** [comment]
我这边有个机场订阅链接：https://xxx.cloud/sub/xxxxx.html，读不出节点信息

**Comment by tindy2013** [comment]
请通过Telegram频道 [@stairspeedtest](https://t.me/stairspeedtest) 的附属群组联系我

**Comment by qliang0816** [comment]
没找到附属群组。。。
