### ISSUE TITLE
Clash新版支持ssr问题

### ISSUE THREAD

**Issue by happy-tao** [tindy2013/subconverter#220]
Clash新版已经支持了SSR，但是0.6.1目前转化clashr和clash均不能支持最新版的内核。

> `target=clash`无法解析ssr节点。
> `target=clashr` 里面有两个参数 `protocolparam` 和 `obfsparam` 应该改为  `protocol-param` 和 `obfs-param`。

辛苦对新版做出支持。

**Comment by zhongfly** [comment]
https://github.com/tindy2013/subconverter/commit/f56e7dd5aeeb88ca87427bfe9ede6e27ea8a5e4a
