### ISSUE TITLE
规则导致万网域名查询失效

### ISSUE THREAD

**Issue by AkariiinMKII** [tindy2013/subconverter#223]
位置：[line5833@/base/rules/NobyDa/Surge/AdRule.list](https://github.com/tindy2013/subconverter/blob/8bc6e8de395e9b0fff3155cc4f3ad0f97101ee15/base/rules/NobyDa/Surge/AdRule.list#L5833)

**Comment by sengoku-f** [comment]
> 位置：[line5833@/base/rules/NobyDa/Surge/AdRule.list](https://github.com/tindy2013/subconverter/blob/8bc6e8de395e9b0fff3155cc4f3ad0f97101ee15/base/rules/NobyDa/Surge/AdRule.list#L5833)

那就别加广告过滤啊

**Comment by txyyh** [comment]
@AkariiinMKII 此问题请报告给规则维护者而非本仓库

**Comment by AkariiinMKII** [comment]
[solved](https://github.com/NobyDa/Script/commit/62c9a007b1bfde63ae1d165ff7a7ab9487858ede)
