### ISSUE TITLE
ssr订阅转换clashr失败，没有任何节点信息，打开后提示The following link doesn't contain any valid node info

### ISSUE THREAD

**Issue by klefjkl** [tindy2013/subconverter#224]
The following link doesn't contain any valid node info: https://xxxxxxxx.xxx
ssr订阅地址转换后生成的clashr链接打开后显示如图，里面没有任何节点信息，原ssr为rc4-md5加密，http_simple混淆，origin协议
使用https://sub-web.netlify.app/
这个站点转换后没有任何问题，可以直接使用。
![121](https://user-images.githubusercontent.com/68412656/88520608-62043900-d026-11ea-9ecc-43b3bb9efc7b.png)

**Comment by tindy2013** [comment]
@klefjkl 薯条机场已封禁该公共 API，无法获取订阅内容。请自行选择其他转换后端或自建后端进行转换。
