### ISSUE TITLE
Clash兼容性问题

### ISSUE THREAD

**Issue by leihao** [tindy2013/subconverter#225]
上游 Clash 核心已移除前向兼容代码

包括但不限于

- 不再解析 "Proxy" "Proxy Group" "Rule" 字段 而 使用 "proxies" "proxy-groups" "rules"
- 不再解析 "rule-provider" 而使用 "rule-providers"
- 不再解析 Shadowsocks 协议的 "obfs", "obfs-host" 而 使用 "plugin" "plugin-opts"
- 不再解析 "FINAL" "SOURCE-IP-CIDR" 而 使用 "MATCH" "SRC-IP-CIDR"

Clash for Android 会为该变更保留 2个月 的前向兼容 各位 用户 及 提供商 尽快适配新的配置文件规范

参见 commit
-2781090 (https://github.com/Dreamacro/clash/commit/7c62fe41b40e6b20c8c88e0e5b5ee96ac0c46dd9) 
-e57a13e (https://github.com/Dreamacro/clash/commit/88d8f937938d7aba774b1af638df6910b1a1a14d)

试了手工改simple_base.yml不生效

**Comment by tindy2013** [comment]
参见 commit
- df9f030ca975fe060b1412c76b6d2b6f2ce6c868

**Comment by leihao** [comment]
> 参见 commit
> 
> * [df9f030](https://github.com/tindy2013/subconverter/commit/df9f030ca975fe060b1412c76b6d2b6f2ce6c868)

看到了,感谢!
