### ISSUE TITLE
不支持协议为chacha20协议的ssr订阅

### ISSUE THREAD

**Issue by zhuwenjie2346** [tindy2013/subconverter#226]
试了一下，也更新到了最新的Clash.for.Windows-0.11.2-客户端了，但是它的订阅转换不支持chacha20协议的ssr订阅。就是在114514那订阅转换原chacha20的ssr后，无法更新订阅，出错提示这个。
![clashr](https://user-images.githubusercontent.com/46016453/88622602-bb777100-d0d5-11ea-862d-cc42496a555b.jpg)
用在d大那个最新的Clash.for.Windows-0.11.2也无法订阅更新。提示更新后也是这个。这个问题能解决不？谢谢。

**Comment by tindy2013** [comment]
不能。支不支持不是我说了算。Clash 上游 Go 加密库早在数月前就已不再支持 chacha20 加密。

**Comment by zhuwenjie2346** [comment]
好吧，知道了，谢谢
