### ISSUE TITLE
新版clash：参数obfsparam和protocolparam已更名

### ISSUE THREAD

**Issue by hesongtao96** [tindy2013/subconverter#228]
tindy哥您好，感谢您写的subconverter，一直很好用，最近clash推出0.11.2更新，已经原生支持了ssr，相比于clashR，主要有两处改动，参数obfsparam更名为obfs-param，参数protocolparam更名为protocol-param，请问下您是否可以考虑根据这两处改动更新subcoverter呢，小白目前还不知道怎么自己更新，非常谢谢您！

**Comment by tindy2013** [comment]
@hesongtao96 请使用 target、

**Comment by hesongtao96** [comment]
> @hesongtao96 请使用 target clash 输出原生 SSR 节点信息

谢谢tindy哥！问题已经解决啦，祝一切顺利🌹

**Comment by yarkable** [comment]
@hesongtao96 thanks for reminding.
