### ISSUE TITLE
部分后端转换部分订阅显示“The following link doesn't contain any valid node info ”

### ISSUE THREAD

**Issue by asasdday** [tindy2013/subconverter#229]
在用subcon.py6.pw和bianyuan.xyz转换时都会出现此问题。
自己在heroku搭建的也无法正常转换。
api.wcc.best可以正常转换。
使用的是薯条订阅。
想问这是什么原因，麻烦了。

**Comment by asasdday** [comment]
有类似提出是订阅based64解密的原因，那为何api.wcc.best可以转换，求解

**Comment by dante2046** [comment]
@asasdday 薯条屏蔽，并将继续屏蔽各类转换api网址

**Comment by mw418** [comment]
如何解决呢
