### ISSUE TITLE
clash转换之后，控制台下面部分分组不能选取节点。

### ISSUE THREAD

**Issue by wwkazmm110** [tindy2013/subconverter#230]
clash转换之后，控制台下面部分分组不能选取节点。用的是魅影，转换之后，下面香港，台湾等一些分组，不能选节点。

**Comment by zm24120** [comment]
url-test是自动策略~

**Comment by wwkazmm110** [comment]
> url-test是自动策略〜

不好意思，我是新手小包，那哪里有手动选择的策略。转换订阅里面我该选择哪个？

**Comment by Mit2g** [comment]
> > url-test是自动策略〜
> 
> 不好意思，我是新手小白，那哪里有手动选择的策略。转换订阅里面我该选择哪个？

选择 `无url-test`或其他任意预制规则
