### ISSUE TITLE
通过配置订阅在线规则出现「Failed to fetch ruleset or ruleset is empty」提示

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [tindy2013/subconverter#231]
配置文件内容如下：
rulesets：
![image](https://user-images.githubusercontent.com/19187129/89096643-c51d1380-d40a-11ea-85f4-0c673080302f.png)

groups：
![image](https://user-images.githubusercontent.com/19187129/89096648-d108d580-d40a-11ea-91a4-41ac435a7fcf.png)

当通过浏览器发起订阅时，terminal输出内容如下：
![image](https://user-images.githubusercontent.com/19187129/89096656-e847c300-d40a-11ea-81a5-46716eb04021.png)

配置文件的订阅链接通过浏览器可以正常访问。

**Comment by swiftwind0405** [comment]
兄弟，你这个配置不错啊，能分享下不

**Comment by Android-AwesomeRoy** [comment]
> 兄弟，你这个配置不错啊，能分享下不

你去搜一下 ACL4SSR 就好。那里面都有。

**Comment by swiftwind0405** [comment]
> > 兄弟，你这个配置不错啊，能分享下不
> 
> 你去搜一下 ACL4SSR 就好。那里面都有。

好！感谢回复

**Comment by KevinLoveGitHub** [comment]
我也出现了同样的问题，该怎么解决呀？

**Comment by NinjaUmbra** [comment]
@KevinLoveGitHub 123

**Comment by NinjaUmbra** [comment]
@KevinLoveGitHub 你可能需要通过代理更新规则

**Comment by KevinLoveGitHub** [comment]
@NinjaUmbra 解决了，感谢

**Comment by cx99325** [comment]
> @NinjaUmbra 解决了，感谢

您好，请问怎么解决的呢，我也是同样的情况

**Comment by NinjaUmbra** [comment]
> > @NinjaUmbra 解决了，感谢
> 
> 
> 
> 您好，请问怎么解决的呢，我也是同样的情况

更改dns

**Comment by Duke-li** [comment]
> 
> 更改dns
你好本地window也报这个错，已经用clash上梯子了，修改DNS是需要修改网卡里面的DNS吗？

**Comment by Duke-li** [comment]
> > > @NinjaUmbra 解决了，感谢
> > 
> > 
> > 您好，请问怎么解决的呢，我也是同样的情况
> 
> 更改dns

你好本地window11，已经用clash翻墙了，还是报这个错，需要修改网卡里面的dns嘛？
