### ISSUE TITLE
在线订阅规则出现[Maximum file size exceeded]

### ISSUE THREAD

**Issue by eMeab** [tindy2013/subconverter#232]
规则为[https://anti-ad.net/surge.txt](url)

**Comment by tindy2013** [comment]
在线 API 为防止恶意破坏，已限制下载的单个文件大小不能超过 1MB。如有需要请使用更简单的 RULE-SET，拆分该 RULE-SET 或使用自建 API 以规避限制。

**Comment by tindy2013** [comment]
长时间未得到回复，该 Issue 将被关闭。
