### ISSUE TITLE
ssr to clash

### ISSUE THREAD

**Issue by geekotaku** [tindy2013/subconverter#233]
ssr协议参数中带冒号（如下），转换到clash后配置为：protocol-param: 13053:TLNbF4
由于没有引号导致yaml解析错误

协议参数：13053:TLNbF4

**Comment by tindy2013** [comment]
为 Clash(R) 生成的订阅来自 yaml-cpp 库，符合 YAML 1.2 标准，可被 Clash(R) 核心正确解析，并可通过 https://www.yamllint.com 的格式检查。若您所使用的客户端报告了该错误，请联系此客户端的开发者。

**Comment by xfzha0** [comment]
我的没引号正常的

**Comment by geekotaku** [comment]
proxies:
  - {name: "🇭🇰 [SR101] 香港", server: xxx, port: 5001, type: ssr, cipher: chacha20-ietf, password: xxx, protocol: auth_aes128_sha1, obfs: tls1.2_ticket_auth, protocol-param: 13053:TLNbF4, obfs-param: 0947e13053.microsoft.com}

(<unknown>): found unexpected ':' while scanning a plain scalar at line 2 column 173

**Comment by xfzha0** [comment]
clash 提示错误了吗？

**Comment by geekotaku** [comment]
是的，因为键值对的值中含有冒号，必须要加引号才可以

**Comment by geekotaku** [comment]
是的，因为值中含有冒号必须加引号
protocol-param: "13053:TLNbF4"
这样才可以

**Comment by xfzha0** [comment]
奇怪，你什么版本的clash啊，我的premium不带引号是正常可以识别的

**Comment by geekotaku** [comment]
正常情况下不带引号是可以的呀，但是这个值里有冒号，看清楚！！！

**Comment by xfzha0** [comment]
> 正常情况下不带引号是可以的呀，但是这个值里有冒号，看清楚！！！

是的，我的里面有冒号并且正常使用

**Comment by zm24120** [comment]
![图片](https://user-images.githubusercontent.com/53201527/89254504-d1df7880-d651-11ea-9f09-3000953877c7.png)

毫无问题

**Comment by geekotaku** [comment]
试了一下，clash for windows确实可以！
但是我的环境是linux里的clash，转了一个不带冒号的链接没任何问题，就这个带冒号的不行
我都是放在proxy-providers里的

**Comment by geekotaku** [comment]
发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。

**Comment by zm24120** [comment]
> 
> 
> 发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。

你内核版本问题吧

**Comment by geekotaku** [comment]
> > 发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。
> 
> 你内核版本问题吧，用这个 https://tmpclashpremiumbindary.cf/

嗯，查了一下dev分支才支持ssr，我用的release

**Comment by zm24120** [comment]
> 
> 
> > > 发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。
> > 
> > 
> > 你内核版本问题吧，用这个 https://tmpclashpremiumbindary.cf/
> 
> 嗯，查了一下dev分支才支持ssr，我用的release

release版本还没同步ssr支持呀~ 我发你的是premium的内测核心~这支持

**Comment by zm24120** [comment]
> 
> 
> > > 发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。
> > 
> > 
> > 你内核版本问题吧，用这个 https://tmpclashpremiumbindary.cf/
> 
> 嗯，查了一下dev分支才支持ssr，我用的release

release版本还没同步ssr支持呀~ 我发你的是premium的内测核心~这支持

**Comment by geekotaku** [comment]
> > > > 发现问题：linux端的clash不支持ssr配置？！文档里明明写着可以，clash for windows也可以，不是转换的错。
> > > 
> > > 
> > > 你内核版本问题吧，用这个 https://tmpclashpremiumbindary.cf/
> > 
> > 
> > 嗯，查了一下dev分支才支持ssr，我用的release
> 
> release版本还没同步ssr支持呀~ 我发你的是premium的内测核心~这支持

感谢，已经成功！
