### ISSUE TITLE
关于QuantumultX 订阅转换，[filter_remote]、[policy]的一些问题。

### ISSUE THREAD

**Issue by PoetryU** [tindy2013/subconverter#234]
转换设置：
客户端**QuantumultX**
远程配置**不使用，由接口方提供**
后端**自己部署的subconverter**

关于我的`pref.ini`:
```
[common]
;default_external_config=config/被注释了
quanx_rule_base=base/quanx.conf

[rulesets]
enabled=true
overwrite_original_rules=false
update_ruleset_on_request=false
ruleset=!!import:snippets/rulesets.txt

[proxy_groups]
custom_proxy_group=!!import:snippets/groups.txt
```

`.txt`均为项目中的源文件未修改。
----
`quanx.conf`:
![asRfmj.png](https://s1.ax1x.com/2020/08/05/asRfmj.png)
![asRv7R.png](https://s1.ax1x.com/2020/08/05/asRv7R.png)

也就是圈X的：[filter_remote]、[policy] 我都已经定义好了。
## 描述问题：
但因为`pref.ini`中的`[rulesets]、[proxy_groups]`
最终生成的订阅配置文件：
* `[policy]`被`[proxy_groups]`替换
*  `[filter_remote]`没有被替换，是 `[filter_remote]+[rulesets]`的形式
* `[filter_remote]`部分，顺序发生改变（因为圈X的`filter_remote`遵循从上至下匹配，所以顺序被按照字母升序）

想要的效果：

## 求助问题：
针对上述的问题。我想在
```
客户端**QuantumultX**
远程配置**不使用，由接口方提供**
后端**自己部署的subconverter**
```
解决[描述问题](#描述问题)

请教大佬，这样的需求有什么好的解决方案？(比如针对QuanX，写一个远程配置文件ini?)

[配置转换前后片段](https://paste.ubuntu.com/p/hDkHRjQqjb/)

**Comment by tindy2013** [comment]
属于预期行为。Quantumult X 的 base 配置中，已定义的 policy 将用于为生成的分组匹配 img-url。而已定义的 filter_remote 将会被保留，并根据内部 conf 解析器的定义，这些项目将按照 key 升序排序。您应将自己所需的分组以及规则添加至后端的配置文件中，以供 subconverter 读取生成目标 policy 以及 filter。

**Comment by PoetryU** [comment]
感谢大佬的回复。我还有个问题

我在后端已经编辑了`quanx.conf`，然后 **远程配置不使用，由接口方提供**，生成的quanX配置还是有`pref.ini`中的`[rulesets]、[proxy_groups]`

emmmmm如果把`pref.ini`中的`[rulesets]、[proxy_groups]`删除，其他的客户端就没有相应的规则了。

**Comment by tindy2013** [comment]
> 感谢大佬的回复。我还有个问题
> 
> 我在后端已经编辑了`quanx.conf`，然后 **远程配置不使用，由接口方提供**，生成的quanX配置还是有`pref.ini`中的`[rulesets]、[proxy_groups]`
> 
> emmmmm如果把`pref.ini`中的`[rulesets]、[proxy_groups]`删除，其他的客户端就没有相应的规则了。

_**由接口方提供**_ 就是指使用 `pref.ini` 中的分组规则进行生成啊
