### ISSUE TITLE
0.6系列版本出现The following link doesn't contain any valid node info

### ISSUE THREAD

**Issue by reizhi** [tindy2013/subconverter#235]
后端配置情况：
```
port=2550
managed_config_prefix=http://127.0.0.1:2550
```
其他未动，采用Nginx反代，25500端口对外提供服务，以方便配置HTTPS。
源订阅类型无论选择 clash 或 shadowrocket，均出现提示The following link doesn't contain any valid node info

控制台输出：
```
2020/08/08 Sat 19:27:33.885383 [14164 22][INFO] Reading preference settings...
2020/08/08 Sat 19:27:33.887385 [14164 22][INFO] Read preference settings completed.
2020/08/08 Sat 19:27:33.887385 [14164 22][INFO] Fetching node data from url 'https://********/api/user/account/subscribe/81e********************8e92cf'.
```

但是如果将源订阅文件下载为 xx.yaml，再上传至任意 web 服务器，再生成的链接均可以被正常转换。
源订阅 clash 配置在 clash for win 中可以正常使用。
退回0.5.2版本后问题消失。
```
2020/08/08 Sat 19:26:11.518255 [6294][INFO] Reading preference settings...
2020/08/08 Sat 19:26:11.518647 [6294][INFO] Read preference settings completed.
2020/08/08 Sat 19:26:11.518754 [6294][INFO] Fetching node data from url 'https://*********/api/user/account/subscribe/0ca*************************'
2020/08/08 Sat 19:26:11.694337 [6294][INFO] Generate completed.
```

**Comment by AidenLx** [comment]
#209 这个问题之前我也遇到过，现在又出现了，只好临时退回0.5.2，说是公共api的问题，但是为什么退回老版就可以正常使用了呢？

**Comment by superszy** [comment]
新版本确实有此问题，把生成的链接复制到浏览器，多次刷新，偶尔能正确返回。之前版本没问题。

**Comment by AuroraDysis** [comment]
遇到同样的问题，自建的，并非公共ip，wget也可以正常下载

**Comment by esmuellert** [comment]
一样的问题，但是非常奇怪。我在自己的Mac电脑上建的docker在0.5.2版本下能够运行，但是在vps上建的无论什么版本都运行不了，而且在vps本地curl也运行不了。但是有的网站建的api能够正常运行，不知道这是哪方面的问题。

**Comment by tindy2013** [comment]
已修复限制下载大小相关代码中的问题，Docker 用户可重新拉取 latest 镜像进行测试。

**Comment by superszy** [comment]
> 已修复限制下载大小相关代码中的问题，Docker 用户可重新拉取 latest 镜像进行测试。

更新之后没问题了，非常感谢

**Comment by kettly1260** [comment]
> 已修复限制下载大小相关代码中的问题，Docker 用户可重新拉取 latest 镜像进行测试。

使用0.6.4版依旧存在该问题，返回0.5.2版本恢复

**Comment by Comah** [comment]
0.6.4版本更新之后 所有订阅都出现了这个问题了
The following link doesn't contain any valid node info 
希望大佬尽快修复
