### ISSUE TITLE
取值中文不行

### ISSUE THREAD

**Issue by not-know** [tindy2013/subconverter#236]
Clash for Windows可以用tap来全局代理，但是需要指定网卡来避免环路，我就修改 base/all_base.tpl 文件加入如下配置
![image](https://user-images.githubusercontent.com/41330630/89719111-93eaa780-d9f7-11ea-9020-efa4ba6a1e9d.png)
但是输入中文就无法渲染
![image](https://user-images.githubusercontent.com/41330630/89719133-c399af80-d9f7-11ea-80e2-07ac64d88b60.png)
英文就可以
![image](https://user-images.githubusercontent.com/41330630/89719146-e4fa9b80-d9f7-11ea-86b0-65d6e6190530.png)

有什么办法可以解决吗

**Comment by not-know** [comment]
我也不太懂，反正就是瞎配置的  不知道是不是配错了

**Comment by tindy2013** [comment]
![image](https://user-images.githubusercontent.com/49061470/89726225-b2c65980-da4a-11ea-848f-9ae2dc294f64.png)

**Comment by tindy2013** [comment]
长时间未得到回复，该 Issue 将被关闭。
