### ISSUE TITLE
能否增加一个Argument，筛选出特定端口的节点

### ISSUE THREAD

**Issue by QiuSimons** [tindy2013/subconverter#238]
比如&port=1234，筛选出使用1234端口的节点？

**Comment by tindy2013** [comment]
可使用 `filter_script`:
```javascript
function filter(node) {
  const info = JSON.parse(node.ProxyInfo);
  if(info.Port == "1234")
    return true;
  return false;
}
```
填入 `pref` 配置文件中，仅限自行搭建使用。

**Comment by QiuSimons** [comment]
> 可使用 `filter_script`:
> 
> ```js
> function filter(node) {
>   const info = JSON.parse(node.ProxyInfo);
>   if(info.Port == "1234")
>     return true;
>   return false;
> }
> ```
> 
> 填入 `pref` 配置文件中，仅限自行搭建使用。

谢谢，要打开enable_filter=false对吧？
然后如果能做个默认筛选参数的话就更方便了~
