### ISSUE TITLE
能否针对Clash增加fake-ip-filter接口

### ISSUE THREAD

**Issue by elanchou** [tindy2013/subconverter#239]
能否针对Clash增加fake-ip-filter接口，现在机场很多为域名解析，Clash开启增强模式后如果不在fake-ip-filter中添加机场域名，会导致DNS解析失败

**Comment by zhongfly** [comment]
请参照https://github.com/tindy2013/subconverter/blob/master/base/base/GeneralClashConfig.yml 新建满足需求的模板文件，之后在配置文件中指定clash配置使用该模板

**Comment by RichardLuo0** [comment]
> 请参照https://github.com/tindy2013/subconverter/blob/master/base/base/GeneralClashConfig.yml 新建满足需求的模板文件，之后在配置文件中指定clash配置使用该模板

请问globals支持数组吗？我这样写他提示 yaml-cpp: error at line 13, column 14: bad conversion
还是说我理解有误
![Image](https://github.com/user-attachments/assets/d5d42ae7-63b5-459d-99cf-4c096c39079e)
![Image](https://github.com/user-attachments/assets/980848f0-9336-405c-9f3c-2c46e4b8cc5c)
