### ISSUE TITLE
自动选择节点如何在节点挂掉时自动重新测速切换到其他节点？

### ISSUE THREAD

**Issue by LEggcookies** [tindy2013/subconverter#240]
自动选择的节点如果失效，会在连接超时后重新测速重新选择节点吗？我这目前来看没有看到这样的效果，要等到 300 秒过去重新测速之后才会切换节点

custom_proxy_group=🍎 苹果服务`url-test`(美国|US)`http://www.gstatic.com/generate_204`300
表示创建一个叫 🍎 苹果服务 的 url-test 策略组,并向其中添加名字含'美国','US'的节点，每隔300秒测试一次

url-test、select、还有其他关键字吗？
http://www.gstatic.com/generate_204 是测试地址还是什么

**Comment by gg4924** [comment]
我用的clash，除了你说的url-test、select，还有relay、fallback、load-balance，你可以看这个页面[https://github.com/Dreamacro/clash/wiki/configuration](url)里的Proxy Groups说明。
