### ISSUE TITLE
自定义User-Agent支持

### ISSUE THREAD

**Issue by happy-tao** [tindy2013/subconverter#242]
由于部分机场出于安全考虑禁止了第三方更新订阅，其中关键字应该是根据User-Agent进行判定的。

所以请求开发者请求订阅链接时支持自定义User-Agent，用来方便自己搭建的自用订阅转化服务。

建议写入固定pref.ini读取配置即可，不用做在URL里面。也杜绝了部分sub-web服务直接通过修改UA达到访问机场的目的。

希望考虑支持一下此功能。再次拜谢。

**Comment by tindy2013** [comment]
As of commit b705d84f84f5c9ac0738d0f5b228973f56f2c8d7 (release v0.6.3), the behavior when downloading subscriptions is forwarding headers including User-Agent from the requests sent by your clients (Clash for Windows, Surge or your browser, etc.).

**Comment by happy-tao** [comment]
感谢支持，已更新到0.6.3，能够透传User-Agent了。
