### ISSUE TITLE
配置跟新版的Clash x不兼容

### ISSUE THREAD

**Issue by CJianYu** [tindy2013/subconverter#246]
今天更新了clash x，然后导入生成的yaml，但是不起效果，是兼容性问题吗

**Comment by KinXdle** [comment]
参数上加上&new_name=true

**Comment by dante2046** [comment]
@KinXdle ¿

**Comment by zhongfly** [comment]
提issue应该提供subconverter版本号，clashX版本号，所使用的subconverter配置文件，转换参数

**Comment by CJianYu** [comment]
用了@KinXdle的方法解决了，感谢老哥
