### ISSUE TITLE
访问接口时出现"Segmentation fault"错误

### ISSUE THREAD

**Issue by MoeMion** [tindy2013/subconverter#25]
环境Centos7 64bit
服务器内存充足
访问接口时进程直接GG并回报Segmentation fault

**Comment by Miondada** [comment]
Serving HTTP @ http://0.0.0.0:25500
handle_cmd:    GET
handle_uri:    /sub?target=clashr&url=[https链接]
Fetching node data from url 'https://tz.qwq.cc/s/SsXa1'.
2019/12/17 Tue 17:53:05.801767 [DEBUG] Received Link.
2019/12/17 Tue 17:53:05.801796 [DEBUG] Downloading subscription data...
2019/12/17 Tue 17:53:06.358933 [DEBUG] Parsing subscription data...
Segmentation fault

**Comment by tindy2013** [comment]
@Miondada 链接类型

**Comment by Miondada** [comment]
ssr+vmess混合 https://tz.qwq.cc/s/SsXa1 订阅地址

**Comment by tindy2013** [comment]
@Miondada 已保存内容 可以重置

**Comment by tindy2013** [comment]
@Miondada 晚些时候检查问题

**Comment by Miondada** [comment]
非常感谢，如果有需要，可以在TG @Mion_QwQ找到我。

**Comment by tindy2013** [comment]
@Miondada @stairspeedtest 频道附属群组

**Comment by SNSLogty** [comment]
本人部署在debian10_x64上，转换某些类型的v2ray链接相关链接会出现Segmentation fault，但是在windows上同样地址转换不会出现相关报错。

```
handle_cmd:    GET
handle_uri:    /sub?target=clash&url=https://xxx'
Reading preference settings...
Read preference settings completed.
Fetching node data from url 'https://xxx'.
Segmentation fault

```

**Comment by tindy2013** [comment]
@SNSLogty 先尝试使用公共 API 进行测试 环境同样为 Debian 10 x64

**Comment by SNSLogty** [comment]
非常感谢

**Comment by SNSLogty** [comment]
> @SNSLogty 先尝试使用公共 API 进行测试 环境同样为 Debian 10 x64

非常感谢

**Comment by A1exInamin** [comment]
本地部署在 macOS 10.15.2 环境下，转换类型为 `clashr`

在 `gistconf.ini` 内已指定 `token` 和 `id`

在修改 gist 时同样报错 Segmentation Fault

```
handle_cmd:    GET
handle_uri:    /clashr?upload=true
Reading preference settings...
Read preference settings completed.
Fetching node data from url '[**hidden**]'.
Generate target: ClashR
Gist id provided. Modifying gist...
[1]    87283 segmentation fault  ./subconverter
```

**Comment by tindy2013** [comment]
@A1exInamin 请提供使用的版本

**Comment by A1exInamin** [comment]
> @A1exInamin 请提供使用的版本

`0.1.1` `0.2.0` 均有此问题出现
