### ISSUE TITLE
Clash 规则转换错误

### ISSUE THREAD

**Issue by misaka00251** [tindy2013/subconverter#251]
版本：v0.6.4
客户端：Clash
远程配置：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini

导入时会在 13247 行（截至发 issue 时）提示 `error: unsupported rule type PROCESS-NAME`。
![image](https://user-images.githubusercontent.com/3908746/94925034-29368380-04f1-11eb-9665-6c05ac74b403.png)

**Comment by zhongfly** [comment]
请更新clash版本，最新版本已支持PROCESS-NAME类型规则。
