### ISSUE TITLE
[Bug] Scholar 规则组中不应当出现 Google Scholar 搜索引擎

### ISSUE THREAD

**Issue by Leo-Mu** [tindy2013/subconverter#253]
Scholar 组内包含用来阅读学术文献的期刊等网站，它们根据 IP 来判断阅读权限，是一类特殊的需要用校园 IP 直连的境外网站。搜索引擎不在这个范畴，并且 Google Scholar 无法直连访问，不应该放到 scholar 组里面。现在这样是没法查找学术文献的，对学术阅读体验是毁灭性的。
https://github.com/tindy2013/subconverter/commit/167adc457e3f1c44834a501a7d321d14a6492323#r42948068

**Comment by zhongfly** [comment]
这是acl4ssr提供的规则，请去 https://github.com/ACL4SSR/ACL4SSR 提issue。

**Comment by Leo-Mu** [comment]
> 这是acl4ssr提供的规则，请去 https://github.com/ACL4SSR/ACL4SSR 提issue。

好的

**Comment by Chandler-Lu** [comment]
Scholar存在的意义不仅是让你用校园网访问特定的网站，还有另外一个问题就是 scihub 和 Google Scholar 也需要特定ip才能访问。。所以最好的办法是自行独立出两个组
