### ISSUE TITLE
本地生成时，自定义Profile文件中定义了exclude字段时，pref.yml中的exclude_remarks配置失效

### ISSUE THREAD

**Issue by nancheung97** [tindy2013/subconverter#255]
# Profile文件配置：
```
[Profile]
target=clash
new_name=true
url=订阅url
insert=false
config=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_NoAuto.ini
emoji=true
list=false
udp=false
tfo=false
scv=false
fdn=false
sort=false
exclude=下架|用户
upload=true
upload_path=ACL4SSR_Online_Full_NoAuto_Clash.yml
```

# pref-acl4ssr.yml配置：
> 为默认配置

```exclude_remarks: ["(到期|过期|剩余|时间|官网|产品)"]```

# 执行批处理文件：
```
@echo off
chcp 65001

set logPath=logs/generate.log

echo 正在生成配置并上传……
subconverter.exe -g pref-acl4ssr.yml >> %logPath%  2>&1
echo 生成完毕！按任意键查看日志…… && pause>nul
start notepad %logPath%
```
实际执行命令就是：
`subconverter.exe -g pref-acl4ssr.yml`

当Profile文件**指定了exclude字段**后，pref-acl4ssr.yml的exclude_remarks**无法生效**；
当Profile文件**没有指定exclude字段**时， pref-acl4ssr.yml的exclude_remarks**生效**。

**Comment by zhongfly** [comment]
预期行为，请认真阅读文档中的[相关说明](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE) 。

**Comment by nancheung97** [comment]
> 预期行为，请认真阅读文档中的[相关说明](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE) 。

你是指外部配置覆盖pref内容吗？
![image](https://user-images.githubusercontent.com/34061813/95483163-7b7c1680-09c1-11eb-8ce0-47cd5c6bcc87.png)
文档所述为
> 本部分用于 链接参数 &config=

其实api上url传递的参数或者Profile文件定义的参数也算外部配置吗？
如果是这个原因我明白了，我以为外部配置单指config字段指定的配置

**Comment by zhongfly** [comment]
> > 预期行为，请认真阅读文档中的[相关说明](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE) 。
> 
> 你是指外部配置覆盖pref内容吗？
> ![image](https://user-images.githubusercontent.com/34061813/95483163-7b7c1680-09c1-11eb-8ce0-47cd5c6bcc87.png)
> 文档所述为
> 
> > 本部分用于 链接参数 &config=
> 
> 其实api上url传递的参数或者Profile文件定义的参数也算外部配置吗？
> 如果是这个原因我明白了，我以为外部配置单指config字段指定的配置

之前我的回复引用了错误的链接，已更正。

**Comment by nancheung97** [comment]
> > > 预期行为，请认真阅读文档中的[相关说明](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE) 。
> > 
> > 
> > 你是指外部配置覆盖pref内容吗？
> > ![image](https://user-images.githubusercontent.com/34061813/95483163-7b7c1680-09c1-11eb-8ce0-47cd5c6bcc87.png)
> > 文档所述为
> > > 本部分用于 链接参数 &config=
> > 
> > 
> > 其实api上url传递的参数或者Profile文件定义的参数也算外部配置吗？
> > 如果是这个原因我明白了，我以为外部配置单指config字段指定的配置
> 
> 之前我的回复引用了错误的链接，已更正。

已看到了文档描述，没注意看到`会覆盖配置文件里的设置`这句话。为对您造成的工作不便感到抱歉，感谢解答！
