### ISSUE TITLE
使用程序导入r的链接的时候混淆参数会缺少短横线

### ISSUE THREAD

**Issue by kanyou** [tindy2013/subconverter#260]
- name: "ssr"
  type: ssr
  server: server
  port: 443
  cipher: chacha20-ietf
  password: "password"
  obfs: tls1.2_ticket_auth
  protocol: auth_sha1_v4
  # obfs-param: domain.tld
  # protocol-param: "#"
  # udp: true
这是官方的配置，使用软件转换的时候会变成obfsparam和protocolparam导致节点无法使用

**Comment by zhongfly** [comment]
请检查是否选择了正确的目标类型
如果是clash客户端，目标类型应为clash，即target=clash
根据你的描述，你应该是错误的生成了clash**R**的配置文件

**Comment by kanyou** [comment]
> 请检查是否选择了正确的目标类型
> 如果是clash客户端，目标类型应为clash，即target=clash
> 根据你的描述，你应该是错误的生成了clash**R**的配置文件

clash不是已经支持了r了吗，我是需要生成clash可用的带r的配置文件，但是生成的文件会如同上面所说的少短横导致节点不能用，需要手动修改生成的配置文件加短横才可以正常使用，还有节点可以不用括弧而是用官方的那种格式吗，想这样的
 - name: "ss2"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: obfs
    plugin-opts:
      mode: tls # or http
      # host: bing.com

**Comment by alexlee728** [comment]
ClashR客户端SSR协议参数是obfsparam和protocolparam
Clash客户端SSR协议参数是obfs-param和protocol-param

所以你的target参数不能选错，否则无法使用。客户端是Clash的话，target就是target；客户端是ClashR的话，target就是clashr。

**Comment by zhongfly** [comment]
> > 请检查是否选择了正确的目标类型
> > 如果是clash客户端，目标类型应为clash，即target=clash
> > 根据你的描述，你应该是错误的生成了clash**R**的配置文件
> 
> clash不是已经支持了r了吗，我是需要生成clash可用的带r的配置文件，但是生成的文件会如同上面所说的少短横导致节点不能用，需要手动修改生成的配置文件加短横才可以正常使用，还有节点可以不用括弧而是用官方的那种格式吗，想这样的
> 
> * name: "ss2"
>   type: ss
>   server: server
>   port: 443
>   cipher: chacha20-ietf-poly1305
>   password: "password"
>   plugin: obfs
>   plugin-opts:
>   mode: tls # or http
>   # host: bing.com

按着回复试一下就那么难吗？
为什么要自作聪明的以为clashR配置能被clash使用？
为什么要自己固执的认为目标类型为clash就不能包含ssr节点？
既然已经发现clashR配置与clash是不同的，为什么还硬是要生成clashR类型的配置？

**Comment by kanyou** [comment]
好的，谢谢，我惯性思维了
