### ISSUE TITLE
未来有可能增加 clashx for mac 最新版本的转换规则么？

### ISSUE THREAD

**Issue by todaycoder001** [tindy2013/subconverter#262]

**Comment by zhongfly** [comment]
clashX使用的clash配置文件是有什么特殊的地方吗？

**Comment by todaycoder001** [comment]
> clashX使用的clash配置文件是有什么特殊的地方吗？

我将ssr的订阅地址转换为 clash 参数的时候，配置文件中没有看到有节点信息。
![image](https://user-images.githubusercontent.com/18589232/98961635-be8d5480-2540-11eb-900e-6a62b051f6db.png)
我想问下是我那里配置不对么？
