### ISSUE TITLE
【已解决】订阅不到节点，因Clash不支持SSR的chacha20加密方式

### ISSUE THREAD

**Issue by todaycoder001** [tindy2013/subconverter#264]
操作系统：macOS Big Sur，11.0 beta
clashX 版本号：Version: 1.30.4 (1.30.4)

模式选择：基础模式
订阅地址：机场 SSR 订阅地址
客户端：Clash 新参数
远程配置：ACL4SSR OnlineNoAuto无自动测速(与Github同步)
后端地址：subconverter-web.now.sh(subconverter作者提供2-稳定)

一键导入 Clash 后出现报错：
托管配置文件格式不正确: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `The dep...` into config.RawConfig

![image](https://user-images.githubusercontent.com/18589232/98966983-e2539900-2546-11eb-87d1-5de6705b9130.png)

**Comment by zhongfly** [comment]
该后端地址已停止服务，请使用其他后端

**Comment by todaycoder001** [comment]
> 该后端地址已停止服务(目前会跳转到作者的另一个后端)，请使用其他后端

我使用了【subcon.dij.tf(sbconverter作者提供1)】后端服务，生成的配置文件能正常导入clashx for mac，但是里面只有网络分发的规则，没有任何订阅节点的信息。具体截图如下：
![image](https://user-images.githubusercontent.com/18589232/99018017-1acd9400-2594-11eb-853b-545c4e3f85e0.png)
请问是我的操作方法有什么问题么？谢谢。

**Comment by todaycoder001** [comment]
> 该后端地址已停止服务(目前会跳转到作者的另一个后端)，请使用其他后端

不好意思，经排查，发现是 clash 不支持ssr的chacha20加密方式.

**Comment by gang4399** [comment]
假如是我就会修改原标题为 （已解决）订阅不到节点，因Clash不支持SSR的chacha20加密方式。

**Comment by todaycoder001** [comment]
> 假如是我就会修改原标题为 （已解决）订阅不到节点，因Clash不支持SSR的chacha20加密方式。

好的，感谢指出，
