### ISSUE TITLE
启动服务后没有默认的web页面吗？

### ISSUE THREAD

**Issue by yflwz** [tindy2013/subconverter#265]
新手一枚，我下载0.64版本到服务器后解压，在pref.ini配置文件中看到有web的目录参数“serve_file_root=”，但是下载下来的项目包中没有找到相关的网页源码文件，是需要自己做还是在哪个目录下可以找到？

**Comment by zhongfly** [comment]
是指前端网页，自己去相关的其他项目中下载。

**Comment by yflwz** [comment]
是sub-web项目吗？

**Comment by zhongfly** [comment]
> 是sub-web项目吗？

可以，任意静态网页均可。

**Comment by yflwz** [comment]
可以，谢谢。
