### ISSUE TITLE
添加 js 脚本 API 文档

### ISSUE THREAD

**Issue by liangchenhe55** [tindy2013/subconverter#267]
`v0.6` 版本已经支持把 js 脚本用于配置项，但是缺少相关文档，例如：

- 支持哪些函数（`geoip()`）等，参数与返回值是什么。
- 不同配置项要求的返回值类型是什么。
- 注入参数 `node` 的结构如何。

等这些问题不得不翻源码查看，略显繁琐。希望可以整理一下。

**Comment by shaoyingrui** [comment]
支持 同求！！！

**Comment by zhongfly** [comment]
中文文档 配置文件 [common] 部分 10. 有介绍

**Comment by liangchenhe55** [comment]
确实已经补充了文档。感谢。
