### ISSUE TITLE
优化建议：去重

### ISSUE THREAD

**Issue by leosam1024** [tindy2013/subconverter#27]
建议1：
我导入了自定义的规则，
```
surge_ruleset=🔰 节点选择,rules/ACL4SSR/Clash/ProxyLite.list
surge_ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaDomain.list
surge_ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaIp.list
```

但是如果，与默认的规则重复的话，不会进行去重。
比如我对生成的规则进行搜索  “DOMAIN-SUFFIX,qq.com,🎯 全球直连”，会出现3次一样的。
希望加一个去重功能。

建议2：
如果我同时导入了
```
  - DOMAIN,livew.l.qq.com,🎯 全球直连
  - DOMAIN,vd.l.qq.com,🎯 全球直连
  - DOMAIN-SUFFIX,qq.com,🎯 全球直连
```
那么最后一条，应该包含前面2条，可以尝试把剩下的2条去掉

谢谢你的贡献。

我的规则：
```
clash_rule_base=rules/ACL4SSR/Clash/General_dns.yml
surge_ruleset=🔰 节点选择,rules/ACL4SSR/Clash/ProxyLite.list
surge_ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaDomain.list
surge_ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaIp.list
```
https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash

**Comment by tindy2013** [comment]
@leosam1995 可以不需要去重 在有多条规则的时候  Clash 只会使用较靠前的规则

**Comment by leosam1995** [comment]
好吧，总感觉怪怪的，
虽然这样，但感觉规则少点，效率能高，因为clash做匹配的时候，匹配不上这条规则的可能性是99%

**Comment by RunningMelos** [comment]
要考虑到现实是存在有 xxx.xxx.com 被墙，而 xxx.com 没被墙的情况的…而且 clash 哪怕读10k 条规则也不过是 3ms，最好的办法应当是自己对规则做一定的维护和去重，毕竟基础的规则不会有太大的变化。

**Comment by libli** [comment]
规则太多影响匹配性能。所以可以把后面出现的和前面一摸一样的规则去掉。
