### ISSUE TITLE
转换成 clash 时，默认使用哪个配置文件？

### ISSUE THREAD

**Issue by Azureki** [tindy2013/subconverter#276]
我修改了配置文件，然后重启 subconverter，但转换成的 clash 配置并没有变化。
我修改了 `base/simple_base.yml`、`base/GeneralClashConfig.yml`，并且复制到了`$HOME/.config/clash/config.yml`和运行目录`subconverter/config.yml`。
请求参数只填了 target(clash) 和 url。

**Comment by naoh1000** [comment]
修改这两个文件不用复制，在pref.yml里引用就行

**Comment by Azureki** [comment]
@naoh1000 谢谢，可以了。

**Comment by ccgakki** [comment]
你好，请问如何设置啊？
