### ISSUE TITLE
自定义远程emoji匹配规则

### ISSUE THREAD

**Issue by fxzxmicah** [tindy2013/subconverter#277]
鉴于节点地区的多样化，命名的多样化和自定义需求的多样化，希望能够将一些匹配规则远程化以适应每个人不同的习惯与需求。
![image](https://user-images.githubusercontent.com/48860358/100536766-b716bc80-325d-11eb-87ca-086662571c99.png)

**Comment by NZESupB** [comment]
外部配置复制一份emoji.txt自己改就行了

**Comment by fxzxmicah** [comment]
@NZESupB 但是我用的不是本地订阅转换，别人的服务器我也没有权限去改啊。

**Comment by zhongfly** [comment]
> @NZESupB 但是我用的不是本地订阅转换，别人的服务器我也没有权限去改啊。

外部配置中可以引用远程的emoji规则

**Comment by naoh1000** [comment]
外部配置写emoji可以直接覆盖原始规则

**Comment by EKyero** [comment]
> @NZESupB但是我用的不是本地订阅转换，别人的服务器我也没有权限去改啊。

https://raw.githubusercontent.com/cccarbondioxide/void/master/cordlite.ini emoji照着抄

**Comment by fxzxmicah** [comment]
没能力，不会抄，而且已经用了ACL的规则，好像不能引用两个外部配置吧。

**Comment by EKyero** [comment]
照着现成规则改很难吗？

**Comment by fxzxmicah** [comment]
不难，是你给的例子太乱了，我照着ACL的改吧。

**Comment by EKyero** [comment]
@fxzxmicah 就让你抄emoji部分你还想干什么呢？

**Comment by fxzxmicah** [comment]
解决了，感谢大佬们的指导，就是指导更直接一点会更好。
比如直接告诉我“复制我使用的ACL的规则到自己的仓库，再在配置文件中加一行`emoji=!!import:<url>`”这样会更好。
