### ISSUE TITLE
支持类型为Auto时，输出的订阅地址能完整支持的只有clash

### ISSUE THREAD

**Issue by zxfandyy** [tindy2013/subconverter#282]
在vps上搭建转换服务，类型为auto时，输出的订阅地址能完整支持的只有clash，quantumult X以及v2rayN完全不支持，Qv2ray只包含VMESS链接，trojan不支持

**Comment by olk90125** [comment]
用 winXray 可以导入各种格式订阅
https://github.com/Chinaboy5216/winXray-4
