### ISSUE TITLE
请问自定义配置的[proxy_group] 部分里边怎么添加不包含关键字的节点

### ISSUE THREAD

**Issue by ouyangxxx** [tindy2013/subconverter#283]
custom_proxy_group=🇯🇵 日本延迟最低`url-test`(日|JP)`http://www.gstatic.com/generate_204`300,5
# 表示创建一个叫 🇯🇵 日本延迟最低 的 url-test 策略组,并向其中添加名字含'日','JP'的节点，每隔300秒测试一次，测速超时为5s

像这种怎么添加不包含某个关键字的节点,比如我要添加除了包含"美国"以外的所有节点,支持这种写法吗?

谢谢

**Comment by gang4399** [comment]
@ouyangxxx 类似
'custom_proxy_group=🇭🇰 港岛节点url-test(?i)^(?!.*(US|美)).*(港|HK|台湾|澳).*$http://www.gstatic.com/generate_204900,5,100'

**Comment by ouyangxxx** [comment]
> @ouyangxxx 类似
> 'custom_proxy_group=🇭🇰 港岛节点`url-test`(?i)^(?!._(US|美))._(港|HK|台湾|澳).*$`http://www.gstatic.com/generate_204`900,5,100'

试了你这个没有成功  然后又百度找到方法了,添加排除美国以外的所有节点
`custom_proxy_group=♻️ 自动2`url-test`^((?!美国).)*$`http://www.gstatic.com/generate_204`600`

**Comment by gang4399** [comment]
> > @ouyangxxx 类似
> > 'custom_proxy_group=🇭🇰 港岛节点`url-test`(?i)^(?!._(US|美))._(港|HK|台湾|澳).*$`http://www.gstatic.com/generate_204`900,5,100'
> 
> 试了你这个没有成功 然后又百度找到方法了,添加排除美国以外的所有节点
> `custom_proxy_group=♻️ 自动2`url-test`^((?!美国).)*$`[http://www.gstatic.com/generate_204`600`](http://www.gstatic.com/generate_204%60600%60)

That's good！

**Comment by fxzxmicah** [comment]
那我还有个问题，就是选出了`(香港|HK)`这种以后，再从中剔除包含`AGA`关键字的节点该怎么写呢？

**Comment by gang4399** [comment]
> 那我还有个问题，就是选出了`(香港|HK)`这种以后，再从中剔除包含`AGA`关键字的节点该怎么写呢？

上面的就是包括哪些同时排除哪些的意思

**Comment by AkariiinMKII** [comment]
@fxzxmicah ^(?!.*AGA).*(HK|香港)

**Comment by kenwestern** [comment]
> @ouyangxxx 类似 `custom_proxy_group=🇭🇰 港岛节点`url-test`(?i)^(?!.*(US|美)).*(港|HK|台湾|澳).*$`[http://www.gstatic.com/generate_204`900,5,100`](http://www.gstatic.com/generate_204%60900,5,100%60)

验证可用，有效解决了流媒体分流误用了高倍率节点耗光流量的问题。

**Comment by qllokirin** [comment]
> @ouyangxxx 类似 `custom_proxy_group=🇭🇰 港岛节点`url-test`(?i)^(?!.*(US|美)).*(港|HK|台湾|澳).*$`[http://www.gstatic.com/generate_204`900,5,100`](http://www.gstatic.com/generate_204%60900,5,100%60)

非常感觉，对我有用
我的节点有
```
[HK]香港01
[HK]香港02
[HK]香港03
香港01
香港02
香港03
```
我试了下`(?i)^(?!.*(HK)).*(香港0).*$`是可以的，但是我想知道为什么`^香港0`这种写法一个都匹配不到？不应该是以香港0开头的字段都能匹配吗，我试了正则匹配测试网站是可以的，但是用订阅转换却没匹配到，打扰了

**Comment by gang4399** [comment]
@qllokirin 左右两个贪婪不得吃完性能？
---Tindy X
