### ISSUE TITLE
[vulnerability] Loop Request检测存在问题，可实现拒绝服务攻击 / Loop Request detection is too fragile and can realize denial of service attacks.

### ISSUE THREAD

**Issue by KB5201314** [tindy2013/subconverter#284]
[English Version Report](https://gist.github.com/KB5201314/150c3a52aead2741ae5d32930988861b#file-subconverter_vulnerability-md)

## 漏洞危害

通过发送一个请求到服务器，就能实现持续的`Loop request`攻击，导致拒绝服务/服务缓慢

## 漏洞原理

通过精心构造的请求头，绕过`Loop request`防御，配合HTTP重定向（301/302），实现`Loop request`攻击。

该程序存在一个公开访问的[外部API](https://github.com/tindy2013/subconverter#access-interface):

```
http://127.0.0.1:25500/sub?target=%TARGET%&url=%URL%&config=%CONFIG%
```

其中的一个名为`url`参数可以是一个任意的外部url。收到该请求后，服务器会发起一个对该`url`的`GET`请求。

1. 构造`Loop request`

   我们可以构造这样的一个url，我们叫它`BAD_URL_ONE`：

   ```
   http://127.0.0.1:25500/sub?target=clash&insert=false&url=BAD_URL_TWO
   ```

   其中`BAD_URL_TWO`也是一个url，在任何时候它都返回一个`301/302`响应，将请求重定向到`BAD_URL_ONE`（重定向可以用一个简单的nginx做到，或者一个带编辑功能的短链接服务做到）

   向该服务器发送一个GET请求，url是`BAD_URL_ONE`，服务器会请求`BAD_URL_TWO`。由于重定向，服务器会访问`BAD_URL_ONE`（自己访问自己），造成`Loop request`

![image-20201219221139213](https://user-images.githubusercontent.com/14936301/102692040-caf58300-424b-11eb-8272-97cc577772b5.png)

   不幸的是，这种攻击已经被得到防御，但是我们发现了新的方法来绕过。

2. 绕过服务端`Loop request`防御

   该程序通过检查请求头来实施对`Loop request`攻击的防御：

   在向外部发送请求时，会带上一个自定义的请求头`SubConverter-Request: 1`：

   https://github.com/tindy2013/subconverter/blob/ab4d7543cec46cd9e45680f3b43d82de16f38a3d/src/webget.cpp#L199

   通过检查请求头中是否包含`SubConverter-Request`，且它的值是否为`"1"`来拒绝`Loop request`：

   https://github.com/tindy2013/subconverter/blob/ab4d7543cec46cd9e45680f3b43d82de16f38a3d/src/webserver_libevent.cpp#L166

   https://github.com/tindy2013/subconverter/blob/ab4d7543cec46cd9e45680f3b43d82de16f38a3d/src/webserver_libevent.cpp#L174

![image-20201219214510521](https://user-images.githubusercontent.com/14936301/102692057-e2347080-424b-11eb-8571-ad84da15952e.png)

   但是该检测方式存在漏洞。

   在服务器发出请求`BAD_URL_TWO`时，会顺带将攻击者请求`BAD_URL_ONE`时发送的所有HTTP请求头也带上，像下面这样：

![image-20201219215030195](https://user-images.githubusercontent.com/14936301/102692091-06904d00-424c-11eb-8c37-d894a5195866.png)

   因此，我们可以用curl请求`BAD_URL_ONE`，并且包含一个叫做`SubConverter-Request`的请求头，但是值不是`"1"`，而是`"2"`，我们就可以得到，两个`SubConverter-Request`💥💥

![image-20201219215510165](https://user-images.githubusercontent.com/14936301/102692107-16a82c80-424c-11eb-8853-a92fd55f30b9.png)

   程序使用libev的[evhttp_find_header](https://libevent.org/doc/http_8h.html#af855b50bd9b47b3f00b44504d38db12c)函数获取请求中的header，这个函数在处理请求中多个相同的header时，只会返回第一个的结果，因此`SubConverter-Request`的值被我们覆盖成了`"2"`，从而绕过了`Loop request`防御。

## 复现过程

1. 从[release页面](https://github.com/tindy2013/subconverter/releases/tag/v0.6.4)下载发布的二进制文件，在本地启动一个服务程序：

   ```shell
   chmod +x ./subconverter
   ./subconverter
   ```

2. 构造`BAD_URL_ONE`：http://127.0.0.1:25500/sub?target=clash&insert=false&url=https://t.xice.wang/v

   其中`BAD_URL_TWO`是一个短链接服务：https://t.xice.wang/v，它会重定向(301)到`BAD_URL_ONE`：

   ```
   curl -v https://t.xice.wang/v
   
   < HTTP/2 301 
   < server: nginx/1.19.0
   < content-type: text/html; charset=UTF-8
   < location: http://127.0.0.1:25500/sub?target=clash&insert=false&url=https://t.xice.wang/v
   < cache-control: no-cache
   ```

3. 发出`BAD_URL_ONE`请求：

   ```
   curl -H 'SubConverter-Request: 2' 'http://127.0.0.1:25500/sub?target=clash&insert=false&url=https://t.xice.wang/v'
   ```

   该请求发出后，程序开始进入无限的`Loop Request`

![image-20201219223158674](https://user-images.githubusercontent.com/14936301/102692124-29226600-424c-11eb-9926-b4b2a5a69a35.png)

   此后新的请求到来时表现为请求缓慢，或者拒绝服务

## 修复建议

   去掉`strcmp()`函数，将检测逻辑改成检测`SubConverter-Request`头是否存在
https://github.com/tindy2013/subconverter/blob/ab4d7543cec46cd9e45680f3b43d82de16f38a3d/src/webserver_libevent.cpp#L174

**Comment by tindy2013** [comment]
感谢提醒。该请求头原意是防止用户将已经过 SubConverter 处理的订阅链接再次送入而做的简单处理，还未考虑过是否能防御真正的攻击。

**Comment by KB5201314** [comment]
> 感谢提醒。该请求头原意是防止用户将已经过 SubConverter 处理的订阅链接再次送入而做的简单处理，还未考虑过是否能防御真正的攻击。

还有一问题，测试过程中通过观察日志，发现在两轮loop之后会停顿几秒钟（可能是timeout），然后再是两轮loop，停顿的期间所有的外部请求都会挂起（包括因为loop request而产生的请求），所以我猜测这里是否意味着程序同时最多只能处理两个外部请求，多余的会丢到队列里？这里是否是libevent的使用问题？（没有用过libevent，只是猜测哈）
