### ISSUE TITLE
建议对于一些基本的节点分组需求简化一下

### ISSUE THREAD

**Issue by fxzxmicah** [tindy2013/subconverter#286]
比如，`(香港|HK)`筛选之后在排除其中包含`AGA`关键字的节点，这些都属于基本需求。完全按照`^((?!(AGA)).)*(香港|HK)*$`这样正则的写法对于简单的需求既繁杂，也不通用：譬如我既有位于名称头部的`AGA`，也有位于中部，尾部的`AGA`，甚至在为其他人写规则，或者节点名称更换频繁时，不利于维护。
我的提议是加入include exclude类似于这种关键字，后面直接跟上需要包含或排除的关键字。

**Comment by gang4399** [comment]
我在另外一贴回你了。你的问题不属于subconverter的功能。just正则表达式而已。你所说的大概是想要程序更直白的给出选项帮你分析各种位置的筛选需求。

但你[另外一个贴子里](https://github.com/tindy2013/subconverter/issues/283) 的正则表达式已经涵盖了你说的各个位置的筛选实现。

**Comment by fxzxmicah** [comment]
我提出的建议是针对最常用的功能做出简化而已，对于这种最常用的部分用正则是有些复杂了（包括逻辑上与表达式上）。并且只是提出这个建议，采不采纳交由原作者定夺。

你所说的另一个帖子中你所给出答案貌似有问题，在正则检测工具中会报错。

我的没有问题，我现在用的就是我在上面写到的表达式，并且在正则检测工具中无报错。

**Comment by gang4399** [comment]
> 我提出的建议是针对最常用的功能做出简化而已，对于这种最常用的部分用正则是有些复杂了（包括逻辑上与表达式上）。并且只是提出这个建议，采不采纳交由原作者定夺。
> 
> 你所说的另一个帖子中你所给出答案貌似有问题，在正则检测工具中会报错。
> 
> 我的没有问题，我现在用的就是我在上面写到的表达式，并且在正则检测工具中无报错。

是我搬运忘记😏格式了，原贴已修正。
`(?i)^(?!.*AGA).*(港|HK).*$`
