### ISSUE TITLE
vmessConstruct 中host和path值设定探讨

### ISSUE THREAD

**Issue by emacsnt** [tindy2013/subconverter#287]
subexport.cpp的[vmessConstruct](https://github.com/tindy2013/subconverter/blob/master/src/subexport.cpp#L103)函数，
当host和path为空时，分别用了节点add字段值和"/"，这样的赋值是否符合机场最初的节点定义？是否会存在潜在的歧义？

**Comment by tindy2013** [comment]
你知道这俩参数啥意思就不会来问这问题了

**Comment by emacsnt** [comment]
主要原因是 用其它客户端(v2rayN和shadowrocket)订阅vmess链接时，手工decode订阅，确认这两个字段没有设定值，为空。
用subconvert生成配置文件时，这两个字段被设定为add代表的域名和"/"，虽然这个配置文件也能使用，但是和机场最初的定义是稍有不同的。
