### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [tindy2013/subconverter#29]
Would you like to [wrap any pointers](https://github.com/tindy2013/subconverter/blob/b89a8b1f7cf7c218164013257549e1fe19a4d56d/src/misc.cpp#L47 "Update candidate: GBKToUTF8()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by tindy2013** [comment]
@elfring This is a good proposal, but I would prefer using reference in pure C++ codes. For other C libraries like libevent, this is worth considering. You are welcomed to make a pull request.
