### ISSUE TITLE
支持加密（base64？）输出

### ISSUE THREAD

**Issue by gouku** [tindy2013/subconverter#291]
在公网搭建了个服务供朋友使用，虽然用了token，但是，默认输出明文感觉有点怪怪的，不知道有没有计划像其他机场那样加密或者说base64混淆后再输出？

**Comment by zhongfly** [comment]
那些target对应的配置类型可以base64加密或自定义加密后还能正常导入代理工具中使用？

**Comment by gouku** [comment]
你是想说“哪些”是吗？没太看明白你的意思

我有一个机场提供的应该就是类似base64的输出：

![image](https://user-images.githubusercontent.com/9361308/104119223-ffe78800-5368-11eb-9151-b0eaeb01791f.png)

然后作为url灌进subconverter可以正常使用

**Comment by tindy2013** [comment]
意义不明，这链接里的东西和 Clash 等客户端用的配置都不是一个东西

**Comment by gang4399** [comment]
“什么几把？”: 猛男说到，只见一人手起刀落，扬肠而去。

**Comment by lin-z-z** [comment]
你好，我想请问下，我的url订阅也是跟你图中一样，都是/client/subscribe这种，这个调用地址填写的时候有什么特殊的地方么，我这边老是400，（http://127.0.0.1:25500/sub?target=%TARGET%&url=%URL%&config=%CONFIG%），就这个链接，我的目标端是clash
