### ISSUE TITLE
对支持多个api_access_token的提议

### ISSUE THREAD

**Issue by gouku** [tindy2013/subconverter#292]
希望可以增加多个 `api_access_token`的支持，这样可以为每个人设置独立的token，当用户失效时，不再希望用户能订阅时，可以单独revoke对应的token，这样就能避免每个用户都要重新用新token。

感谢维护人员的努力，希望能采纳。

**Comment by zhongfly** [comment]
我个人认为，subconverter是一个订阅转换工具，而不是订阅管理分发工具，你可以寻找其他方法来实现。

**Comment by xqXQzzz1** [comment]
@gouku 使用getprofile，是否可以将name当做token，每个用户生成唯一值，提供订阅。不想提供时，在服务器端直接删除对应的文件，不就可以了吗？

**Comment by gouku** [comment]
@zhongfly 有别的方案可以推荐下？当然现成的最好，代码渣路过……

@xqXQzzz1 谢谢，这个思路确实不错，但是创建十几个profile不知道会不会有性能问题？

**Comment by xqXQzzz1** [comment]
@gouku 只要机器储存够大，应该不会出现性能问题吧？每次订阅找一个文件而已吧？
