### ISSUE TITLE
求助：能否筛选固定协议

### ISSUE THREAD

**Issue by nemo2018** [tindy2013/subconverter#294]
不知道能否筛选众多节点里面的指定协议，比如只要Vmess或者只要SS，其他都过滤掉？
谢谢

**Comment by xqXQzzz1** [comment]
@nemo2018 使用subc的script

**Comment by nemo2018** [comment]
谢谢提醒。仿照例子的样子这样写了一个ini，然后放在转换后地址最后&config=这个ini，怎么没生效？
`[common]

enable_filter=true

filter_script=function filter(node) {\n    const info = JSON.parse(node.ProxyInfo);\n    if(info.Type.includes('trojan'))\n        return true;\n    return false;\n}`

**Comment by nemo2018** [comment]
这个配置是一个内部配置，只能通过自建服务器实现而不能通过加一个&config=。。。？

**Comment by xqXQzzz1** [comment]
@nemo2018 据说下个版本支持。
有一个参数script-filter可以用一下。
另外机场节点命名上没有对类型进行分类吗？
最后可以

**Comment by nemo2018** [comment]
> @nemo2018 据说下个版本支持。
> 有一个参数script-filter可以用一下。
> 另外机场节点命名上没有对类型进行分类吗？
> 最后可以先用append_type在节点上附加节点类型，然后再在分组里根据类型筛选

这个办法可行，谢谢！

**Comment by grayguest** [comment]
mark，学习一下。
