### ISSUE TITLE
转换的clash链接打开提示订阅链接无节点

### ISSUE THREAD

**Issue by xixiri** [tindy2013/subconverter#296]
https://subcon.py6.pw/sub?target=clash&new_name=true&url=https%3A%2F%2Fproxypoolss.tk%2Fclash%2Fproxies%3Fc%3DKR%26type%3Dss&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini

转换成clash提示无节点，其实有节点的

**Comment by gang4399** [comment]
@xixiri &fdn=false 呢

**Comment by LM-Firefly** [comment]
@xixiri sub不支持直接把clash proxy providers作为转换源吧 而且这个貌似多个 country 字段

**Comment by xixiri** [comment]
又可以了呢，真是奇怪

**Comment by zhongfly** [comment]
提供节点的网站可能不稳定，与subconverter关系不大。
