### ISSUE TITLE
请问配置文件乱码是什么原因

### ISSUE THREAD

**Issue by huangxiaochi** [tindy2013/subconverter#297]
第一次下载是正常的,后面再下载就是这种乱码
![2](https://user-images.githubusercontent.com/38152042/105957028-9c24c500-60b3-11eb-92af-b7a83cedd67d.png)
![1](https://user-images.githubusercontent.com/38152042/105957037-9f1fb580-60b3-11eb-95dd-04868c39f87a.jpg)

**Comment by tindy2013** [comment]
文件编码识别问题
