### ISSUE TITLE
subconverter里自带的神机规则（10045条）把谷歌浏览器的“沙拉查词”扩展里的谷歌翻译给屏蔽了，关闭clash for windows或者使用clash for Windows里另1个配置后，“沙拉查词”里的谷歌翻译就能正常显示了

### ISSUE THREAD

**Issue by WrathGluttony** [tindy2013/subconverter#298]
①subconverter（版本号：subconverter_win64v0.6.4）里自带的神机规则（神机规则一共是10045条）把谷歌浏览器的“沙拉查词”扩展里的谷歌翻译给屏蔽了，关闭clash for windows或者使用clash for Windows里另1个配置后，“沙拉查词”里的谷歌翻译就能正常显示了。
②请问subconverter里的神机规则里的哪条规则把谷歌浏览器的扩展“沙拉查词”给屏蔽了？
②沙拉查词谷歌应用商店链接：https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg
③沙拉查词github链接：https://github.com/crimx/ext-saladict/releases

**Comment by zhongfly** [comment]
规则问题请找相应的规则项目，subconverter包含规则并不意味着由本项目维护这些规则
