### ISSUE TITLE
服务端是否不支持https？

### ISSUE THREAD

**Issue by xxxtim** [tindy2013/subconverter#300]
文档里没有看到相关选项，如果需要https，只能自己再搭一个反向代理吗？

**Comment by tindy2013** [comment]
客户端内实现 HTTPS 限制较大，推荐使用其他 Web Server 如 Nginx 或 Caddy 提供

**Comment by xietao1233** [comment]
明文在互联网中传输数据也太危险了

**Comment by gang4399** [comment]
@xietao1233 哪来的明文传输服务端？贴下地址

**Comment by xietao1233** [comment]
> @xietao1233 哪来的明文传输服务端？贴下地址

http协议本身

**Comment by gang4399** [comment]
@xietao1233 使用在哪里？我怎么不知道哪个服务用到http 或 明文

**Comment by CareyWang** [comment]
@xietao1233 实现成本与收益不成正比，外网使用自行前置nginx或caddy解决。

**Comment by AkariiinMKII** [comment]
@xietao1233 https://github.com/CareyWang/sub-web 请
