### ISSUE TITLE
现有转换的客户端选项对V2rayN和netch之类的客户端不够友好

### ISSUE THREAD

**Issue by whyjxz14** [tindy2013/subconverter#307]
这些客户端经过更新早就已经都可以兼容ss,ssr,vmess,vless,torjan全部协议了。
但是却没有对应的客户端选项匹配
如果选择v2ray就只有vmess的内容
现有的解决方法是选一个v2ray一个ssr分开使用
但是这样的话torjan会丢失
vless不确定
希望能增加新的客户端选项

**Comment by tindy2013** [comment]
[支持类型](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E6%94%AF%E6%8C%81%E7%B1%BB%E5%9E%8B) `target=mixed`
