### ISSUE TITLE
Feature Request: 对于Shadowsocks转换类型，应该添加如下几种选项

### ISSUE THREAD

**Issue by HuanMeng0** [tindy2013/subconverter#31]
Feature Request: 对于Shadowsocks转换类型，应该添加如下几种选项：
1.base64编码
2.非base64编码
3.json格式的配置文件方式

第二种可以通过剪贴板导入进Shadowsocks Android应用程序，第三种可以通过“从文件替换”导入进Shadowsocks Android应用程序。

以及main.cpp中判断target可以从if换成switch。

**Comment by tindy2013** [comment]
前面的提议没毛病，后面的 if 换 switch 有些问题。C++ 原生并不支持 switch 接收 string 作为标签，要实现必须将 string 进行 hash 处理并用 hash 作为标签。（并不是很想这么整）

**Comment by HuanMeng0** [comment]
了解，那前面的提议实现就好了。

**Comment by tindy2013** [comment]
所有选项已添加完成 详细用法可参照 README

**Comment by BoyceLig** [comment]
做成可视化的 直接可以在上面一栏一栏的填写那样就奈斯了
