### ISSUE TITLE
shadowsocks with v2ray plugin 转换时缺失plugin信息

### ISSUE THREAD

**Issue by zzj0311** [tindy2013/subconverter#310]
subconverter 版本： 0.6.4

调用链接：h ttp://xxxxx/sub?target=clash&url=ss%3A%2F%2Fxxxxx%40xxxxx%3Axxxxx%3F**plugin%3Dv2ray%3Bpath%3D%2Fstatic%3Bmux%3D10%3Bhost%3Dxxxxx%3Btls**%23xxx&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true

得到的proxy：{name: xxx, server: xxxx, port: xxx, type: ss, cipher: aes-256-gcm, password: xxxxxx}

**Comment by tindy2013** [comment]
请使用正确的 plugin 名称 `v2ray-plugin`
