### ISSUE TITLE
请问pref.example.ini中clash能否配置url-test属性lazy为false

### ISSUE THREAD

**Issue by mnm1001** [tindy2013/subconverter#314]
目前看到的配置项只有
interval[,timeout][,tolerance]

请问是否有办法定义lazy为false?

**Comment by zhongfly** [comment]
目前没有办法，之后会添加

**Comment by tindy2013** [comment]
Commit 9797197c85883ccc43941967225f98e570864983 后使用 TOML 配置文件格式添加该选项。

**Comment by xqXQzzz1** [comment]
> Commit [9797197](https://github.com/tindy2013/subconverter/commit/9797197c85883ccc43941967225f98e570864983) 后使用 TOML 配置文件格式添加该选项。

yml和ini格式是否会支持？
