### ISSUE TITLE
配置clash_rule_base后, 模版内容被subconverter变动, 生成的规则是否还是有效的?

### ISSUE THREAD

**Issue by XinSSS** [tindy2013/subconverter#316]
如下两张图所示, 一张是clash_rule_base, 后一张是生成的规则.
我注意到生成的配置文件中, 有些单引号被去掉了, 有些则生成了双引号, 我想问下这种是否会影响规则的有效性呢?

![image](https://user-images.githubusercontent.com/30732527/110279792-aa4ff480-8014-11eb-81a0-5bb39b54bde4.png)

![image](https://user-images.githubusercontent.com/30732527/110279821-b471f300-8014-11eb-8cf3-3dcf5bd075ec.png)

**Comment by zhongfly** [comment]
请自行阅读 [YAML语法](https://zh.wikipedia.org/wiki/YAML#%E8%AA%9E%E6%B3%95)  中相关说明

**Comment by XinSSS** [comment]
> 请自行阅读 [YAML语法](https://zh.wikipedia.org/wiki/YAML#%E8%AA%9E%E6%B3%95) 中相关说明

好的, 谢谢
