### ISSUE TITLE
支持Clash的Load Balance里的strategy参数的指定吗？

### ISSUE THREAD

**Issue by ArriettyQAQ** [tindy2013/subconverter#318]
偶然发现，例子里是没有关于strategy参数的具体指定，不知道是否支持？

`
strategy: consistent-hashing或者round-robin
`

**Comment by zhongfly** [comment]
目前不支持

**Comment by ArriettyQAQ** [comment]
> 
> 
> 目前不支持

好的，谢谢。

**Comment by tindy2013** [comment]
Commit 9797197c85883ccc43941967225f98e570864983 后使用 TOML 配置文件格式添加该选项。
