### ISSUE TITLE
请问能否加入支持armv8 (arm 64bit)的系统?

### ISSUE THREAD

**Issue by promayi** [tindy2013/subconverter#32]
请问能否加入支持armv8 (arm 64bit)的系统?

**Comment by tindy2013** [comment]
@promayi android termux实测可以运行

**Comment by promayi** [comment]
请问用的是哪个类型二进制的文件?
我在斐讯N1上不能运行
root@aml:~# uname -a
Linux aml 5.3.0-aml-g12 #5.99 SMP PREEMPT Fri Nov 22 12:28:10 MSK 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by tindy2013** [comment]
Commit [2f44a21](https://github.com/tindy2013/subconverter/commit/2f44a216b505fe29077aee4d201a3827219e6e90) 已加入 ARM64 (AArch64) 平台的自动构建

**Comment by promayi** [comment]
感谢! 实测，可以使用!!!

**Comment by kettly1260** [comment]
@promayi 你好，请问怎么拉取啊？我直接docker pull 拉取不到

**Comment by tindy2013** [comment]
@kettly1260 docker 目前没有 armv8 架构的自动构建 你可以使用 release 或者自行构建

**Comment by kettly1260** [comment]
> @kettly1260 docker 目前没有 armv8 架构的自动构建 你可以使用 release 或者自行构建

已经构建好了，谢谢

**Comment by hxse** [comment]
> Commit [2f44a21](https://github.com/tindy2013/subconverter/commit/2f44a216b505fe29077aee4d201a3827219e6e90) 已加入 ARM64 (AArch64) 平台的自动构建

请问怎么构建, 有没有脚本可以用啊

**Comment by zm24120** [comment]
@hxse 预编译本身就有呀，直接下不就好了
