### ISSUE TITLE
trojan订阅不能转换吗？

### ISSUE THREAD

**Issue by pcitme** [tindy2013/subconverter#320]
trojan机场官网订阅  用clash一切正常
但是用订阅转换后 全部节点无法连接
是目前还不支持trojan订阅转换吗？

**Comment by zhongfly** [comment]
与https://github.com/tindy2013/subconverter/issues/317 是相同问题

**Comment by pcitme** [comment]
> 与[＃317](https://github.com/tindy2013/subconverter/issues/317)是相同问题

但是依然未解决

**Comment by lxmicode** [comment]
除了手动，无法在subconverter加上一个参数调整吗
