### ISSUE TITLE
Docker 内 MANAGED_PREFIX 不生效

### ISSUE THREAD

**Issue by love4taylor** [tindy2013/subconverter#321]
环境变量应用到 Docker 内了，但是出来的依旧 http://127.0.0.1:25500/

<img width="956" alt="Docker内变量" src="https://user-images.githubusercontent.com/6081912/111873672-670a6400-89cc-11eb-946e-e9e33586d6aa.png">

<img width="956" alt="变量无效" src="https://user-images.githubusercontent.com/6081912/111873725-b81a5800-89cc-11eb-8d78-bf90d7c80fb7.png">

**Comment by tindy2013** [comment]
该选项会被主动进行的读取配置文件覆盖，请设置 `API_MODE=true` 或直接修改容器中的配置文件。

**Comment by love4taylor** [comment]
`API_MODE=true` 解决了，thanks
