### ISSUE TITLE
如何实现自定义序号

### ISSUE THREAD

**Issue by Skyxim** [tindy2013/subconverter#322]
问下如何能够实现自定义序号，比如香港1，香港2，新加坡1，新加坡2
原本我打算在js脚本里定义个map来存储，香港，新加披这种key的出现次数，结果发现每次rename的js脚本都是重新加载的，导致无法实现，请问还有其他实现方式么

**Comment by tindy2013** [comment]
@Skyxim 下个版本将提供 js_clean_context 选项控制每次脚本运行是否使用独立上下文

**Comment by Skyxim** [comment]
了解了，谢谢
