### ISSUE TITLE
最新版本 SS 转换出来的clash 混淆部分格式有问题

### ISSUE THREAD

**Issue by LM-Firefly** [tindy2013/subconverter#326]
转出来的SS节点是这样的 
 - {name: "xxxx", server: xxx, port: 3333, type: ss, cipher: chacha20-ietf-poly1305, password: yyyy, plugin: obfs, plugin-opts: {mode: tls;obfs-host=data.video.qiyi.com, host: ""}, udp: true}

**Comment by tindy2013** [comment]
Fixed in commit b42bfec
