### ISSUE TITLE
转换之后，vmess节点信息缺少servername字段

### ISSUE THREAD

**Issue by gyc98** [tindy2013/subconverter#331]
原有的链接中的节点信息包含servername字段，但是经过subconverter转换之后，缺少了这个字段造成节点无法连接，希望开发者能够修复一下。
比如：
- {name: ***, type: vmess, server: ***, port: ***, uuid: ***, alterId: 0, cipher: auto, udp: true, tls: true, servername: *** }
根据我的理解，这个servername应该适合server字段是一样的

**Comment by IceCodeNew** [comment]
这两个字段可以不一样，tls 这边的 servername 用来指定 TLS SNI，而 server 这边指定一个 IP 地址避免域名被污染（或者跳过解析需要）也是可以的。

**Comment by OneHappyForever** [comment]
希望能支持
