### ISSUE TITLE
Cannot convert IP-CIDR to ip6-cidr in quanx converster

### ISSUE THREAD

**Issue by invisprints** [tindy2013/subconverter#335]
I find the`latest` version and `0.6.4` version subconverter could not convert ipv6 `ip-cidr` address in quanx rule converter

for example, I have a ruleset in clash format:
```
IP-CIDR,2001:b28:f23f::/48,no-resolve
```
and the sub converter convert it to 
```
IP-CIDR,2001:b28:f23f::/48,proxy,no-resolve
```
but the correct one is 
```
IP6-CIDR,2001:b28:f23f::/48,proxy,no-resolve
```

**Comment by tindy2013** [comment]
#369
