### ISSUE TITLE
怎么生成只有节点没有规则的订阅

### ISSUE THREAD

**Issue by chensimmons** [tindy2013/subconverter#338]
把SSR订阅转换clash订阅时，怎么做到生成的订阅只有节点，不引入规则，看了文档，实在不知道哪个参数可以做到，求指点一下

**Comment by AkariiinMKII** [comment]
@chensimmons list=true

**Comment by chensimmons** [comment]
> @chensimmons list=true
@AkariiinMKII 噢噢，可以了，就是这个，万分感谢大佬啊(*^▽^*)
