### ISSUE TITLE
当前版本0.2.5: 从clash转到quantumult的发生错误

### ISSUE THREAD

**Issue by Limgmk** [tindy2013/subconverter#34]
节点配置类似：
Proxy:
- name: 【V2Ray】- 香港
  type:  vmess
  server: test.google.cc
  port: 443
  uuid: xxxxxxxx-cf77-43fd-b049-94957cac9a14
  alterId: 64
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-path: /ray

目前发现只要节点配置了ws-path+tls就会出现错误
转换后的quantumult配置中uri 和请求头以及tls都有问题

**Comment by tindy2013** [comment]
能否详细说明下出现的错误？本地测试并未出现问题。
![image](https://user-images.githubusercontent.com/49061470/72318482-5c24b700-36d7-11ea-887d-1d68ec2c3589.png)

**Comment by Limgmk** [comment]
从
Proxy:
- name: 【V2Ray】香港
  type: vmess
  server: v2.test.com
  port: 443
  uuid: 4e04c823-2204-3a79-8129-2d05d2fa3608
  alterId: 64
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-path: /ray
转换到quantumult会变成这样：
![{62A923EF-0AE0-EC20-B453-E629ED295723}](https://user-images.githubusercontent.com/45861815/72345112-cbe07500-36ca-11ea-9c59-25c96ccc29ee.png)
![{0C8DC29E-275E-47E2-130A-570A859CED9B}](https://user-images.githubusercontent.com/45861815/72345116-ce42cf00-36ca-11ea-9045-16989e1a6b7e.png)
另外我自己试了一下base64解码，vmess://链接是可以解出来的，但是进一步解码成明文就失败了，正常的订阅链接则可以解码成明文

**Comment by tindy2013** [comment]
Should be fixed in [latest release](https://github.com/tindy2013/subconverter/releases/latest).
