### ISSUE TITLE
clash转换ss plugin参数有误 

### ISSUE THREAD

**Issue by Saxon-Sun** [tindy2013/subconverter#342]
转换成ss plugin是simple-obfs 但是ss启动的参数名称是obfs-local （导致openwrt订阅后启动失败，标准obfs-local启动文件只有这个，不认simple-obfs ）

plugin: "obfs-local",  openwrt ss启动认这个
plugin: "simple-obfs" openwrt 这个启动不了

如果转换sssub的话 openwrt 订阅解析不了json格式

**Comment by tindy2013** [comment]
已修复

**Comment by Saxon-Sun** [comment]
谢谢

> 已修复
