### ISSUE TITLE
如何自动过滤/跳过失效的订阅

### ISSUE THREAD

**Issue by miyouzi** [tindy2013/subconverter#351]
`url` 参数中带有多个订阅地址及节点，但是当其中一个订阅地址失效时（如 502，503，time out 等，通常是间歇性抽风），会直接输出无效配置。

如何自动去除失效订阅，保留有效订阅或手动输入的节点，输出有效的配置？

PS：设置输出配置是 clash

![image](https://user-images.githubusercontent.com/24269465/125379187-a6692000-e3c2-11eb-9d33-16cd2ca5af15.png)

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.ini#L276

**Comment by miyouzi** [comment]
感谢
