### ISSUE TITLE
url连接中包含&怎么办呢

### ISSUE THREAD

**Issue by wupengbo125** [tindy2013/subconverter#356]
按照使用方法，我拼接处如下的http请求连接，但我的url包含了&符号，程序就获取不到完整的url了。
http://127.0.0.1:25500/sub?target=clash&url=https://xxxxxx.com?sub=3&extend=1

**Comment by wupengbo125** [comment]
keyword：url 参数   连接符 

%26代替&，   %3F代替?    接受页面不需要改动任何，   &的asc码为%26.  ？的asc码为%3F.

**Comment by zhongfly** [comment]
readme里写得很清楚，“需要经过 URLEncode 处理”
