### ISSUE TITLE
forcerule.yml 中有冲突规则

### ISSUE THREAD

**Issue by pixiandouban** [tindy2013/subconverter#36]
forcerule.yml 中，office365.com 添加了两个一个是 Proxy，一个是 Direct。

> - DOMAIN-SUFFIX,office365.com,Proxy

> - DOMAIN-SUFFIX,office365.com,DIRECT

生成的规则中，结果应该是以第二个为准的

**Comment by tindy2013** [comment]
@pixiandouban 这是示例文件 演示clash base的一种用法 并不代表生成的规则即以此为准

**Comment by pixiandouban** [comment]
如果我想要在 Clash 上添加一个 🗻 日本媒体的 规则，让 这些媒体的域名走这个规则，是这样写吗？

> surge_ruleset=🗻 日本媒体,rules/ConnersHua/Surge/Ruleset/NihonMedia.list

然后在 Clash_custom_proxy 中添加 这个 🗻 日本媒体

**Comment by tindy2013** [comment]
@pixiandouban 可以

**Comment by pixiandouban** [comment]
我在 `pref.ini` 中 加了 `surge_ruleset=🗻 日本媒体`，然后在 `GlobalMedia.list `中用 `#` 注释掉了` Abema.tv` 域名，查看 **Clash for Windows** 日志，还是走的 `🌍  国外媒体` 这个规则。

不知道可能哪里出错。

**Comment by pixiandouban** [comment]
找到问题原因了，我修改了 `GlobalMedia.list` 之后，没有 重新启动 `subconverter.exe`，加载的还是原来的规则。现在好了。

**Comment by ltsj** [comment]
@pixiandouban
