### ISSUE TITLE
请问什么时候能够支持vless协议呢?谢谢

### ISSUE THREAD

**Issue by Comah** [tindy2013/subconverter#361]
希望尽快能够更新一下 以其能够支持vless 辛苦了

**Comment by tindy2013** [comment]
目前没有计划

**Comment by foxdodo** [comment]
> 目前没有计划

大佬考虑一下啊, 因为墙不断加高, 现在很多机场都改成trojan vless了, 不支持这个很难受

**Comment by hadifarnoud** [comment]
please do add support for vless/trojan

**Comment by jacobin** [comment]
[subconverter.MetaCubex](https://github.com/MetaCubeX/subconverter)对mihomo／meta新增协议譬如[vless](https://clash-meta.gitbook.io/clash.meta-wiki-older/function/proxy/vless)有支持。但是支持不完整。譬如对vless的支持就不完整，只支持了vless-tcp，没有支持vless-ws，实际应用案例之比较证明看如下链接：
https://github.com/tindy2013/subconverter/issues/611#issuecomment-3435277158

[subconverter.asdlokj1qpi23](https://github.com/asdlokj1qpi233/subconverter)是[subconverter.MetaCubex](https://github.com/MetaCubeX/subconverter)的拷贝，但是，与[subconverter.MetaCubex](https://github.com/MetaCubeX/subconverter)对[subconverter.tindy2013](https://github.com/tindy2013/subconverter)的尊重不同，[subconverter.asdlokj1qpi23](https://github.com/asdlokj1qpi233/subconverter)对代码的改写是捣乱，不是增量改动，对它的代码审计没法执行。
