### ISSUE TITLE
功能：SIP008转SIP002

### ISSUE THREAD

**Issue by wc7086** [tindy2013/subconverter#366]
SIP008手写比较方便，有些客户端只支持SIP002订阅，手动转换就很难受。

**Comment by zhongfly** [comment]
转换类型选ss(sip002)即可
`target=ss`

**Comment by wc7086** [comment]
> 转换类型选ss(sip002)即可
> `target=ss`

我的意思是把纯SIP008转成SIP002

**Comment by cubercsl** [comment]
The code here may cause the SIP008 subscription can not be converted correctly.

https://github.com/tindy2013/subconverter/blob/867602fbeabd65aeb92caaabcabac4fa4c5f3985/src/parser/subparser.cpp#L498-L500

This patch may be able to fix~

```patch
diff --git a/src/parser/subparser.cpp b/src/parser/subparser.cpp
index 487a29f..d846127 100644
--- a/src/parser/subparser.cpp
+++ b/src/parser/subparser.cpp
@@ -495,7 +495,7 @@ void explodeSSConf(std::string content, std::vector<Proxy> &nodes)
     json.Parse(content.data());
     if(json.HasParseError())
         return;
-    const char *section = json.HasMember("version") && json.HasMember("remarks") && json.HasMember("servers") ? "servers" : "configs";
+    const char *section = json.HasMember("version") && json.HasMember("servers") ? "servers" : "configs";
     if(!json.HasMember(section))
         return;
     GetMember(json, "remarks", group);
```

https://shadowsocks.org/en/wiki/SIP008-Online-Configuration-Delivery.html
https://github.com/shadowsocks/shadowsocks-org/issues/89
