### ISSUE TITLE
转换成 Quantumult X 配置时 IPv6 格式不正确

### ISSUE THREAD

**Issue by imbytecat** [tindy2013/subconverter#369]
转换成 Quantumult X 配置时 IPv6 格式不正确，目前结果是 `IP-CIDR,2001:b28:f23d::/48,Out,no-resolve`，正确结果是 `IP6-CIDR,2001:b28:f23d::/48,Out,no-resolve`

**Comment by tindy2013** [comment]
原规则请使用 `IP-CIDR6`
