### ISSUE TITLE
可否支持macOS系统使用？

### ISSUE THREAD

**Issue by Roy1993sun** [tindy2013/subconverter#37]

**Comment by tindy2013** [comment]
从初代预编译版本开始即有 mac OS 的预编译版本 可直接在 release 中下载

**Comment by pixiandouban** [comment]
@Roy1993sun 在 [release ](https://github.com/tindy2013/subconverter/releases)页面下载已编译版本。

**Comment by PYniang** [comment]
@Roy1993sun 眼睛👀不好不建议使用
