### ISSUE TITLE
转换为vmess时所有额外ID(alterld)会变为0

### ISSUE THREAD

**Issue by RSSYLY** [tindy2013/subconverter#371]
在bc0a8dc，此问题将会出现。具体表现为：v2ray订阅/clash订阅中的v2ray节点在转换为v2ray订阅时alterId会变为0。

**Comment by xixiri** [comment]
@RSSYLY 这应该是你用的网站后端代码没更新，试试这个
https://sub-latest.vercel.app/

**Comment by gitiray** [comment]
mixed 也存在这个问题，只要是v2ray的节点都会

**Comment by xixiri** [comment]
嗯嗯，发现了

**Comment by yangyucacaa** [comment]
是有这个问题

**Comment by tindy2013** [comment]
无法复现，请提供详细信息

**Comment by RSSYLY** [comment]
例如 v2ray 转换为 v2ray
vmess://eyJhZGQiOiIwLjAuMC4wIiwiYWlkIjoiMiIsImhvc3QiOiJleGFtcGxlLmNvbSIsImlkIjoiMTE0NTE0MTkxOTgxMCIsIm5ldCI6IndzIiwicGF0aCI6Ii9wYXRoIiwicG9ydCI6IjQ0MyIsInBzIjoiZXhhbXBsZSIsInNjeSI6Im5vbmUiLCJzbmkiOiIiLCJ0bHMiOiIiLCJ0eXBlIjoiIiwidiI6IjIifQ==
转化后得
vmess://eyJhZGQiOiIwLjAuMC4wIiwiYWlkIjoiMCIsImhvc3QiOiJleGFtcGxlLmNvbSIsImlkIjoiMTE0NTE0MTkxOTgxMCIsIm5ldCI6IndzIiwicGF0aCI6Ii9wYXRoIiwicG9ydCI6IjQ0MyIsInBzIjoiZXhhbXBsZSIsInNjeSI6ImF1dG8iLCJzbmkiOiIiLCJ0bHMiOiIiLCJ0eXBlIjoiIiwidiI6IjIifQ==
后端是 https://subc-api.rssins.net

**Comment by tindy2013** [comment]
不能复现，请尝试使用最新版本

**Comment by gitiray** [comment]
您好，更新到最新版本 v0.7.1 依然复现。过程如下：

准备一个 AlterID != 0 的配置
> vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkFsdGVySUQtVGVzdCIsDQogICJhZGQiOiAiMi4yLjIuMiIsDQogICJwb3J0IjogIjIyMjIiLA0KICAiaWQiOiAiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwNCiAgImFpZCI6ICIyIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIyLjIuMi4yIiwNCiAgInBhdGgiOiAiL3YycmF5IiwNCiAgInRscyI6ICJub25lIg0KfQ==

使用 v0.7.1 生成订阅，得到结果 https://gist.github.com/gitiray/8abda7d9a3725290bebfff7ebec9ce9e

检查订阅后的配置，AlterID == 0
> vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkFsdGVySUQtVGVzdCIsDQogICJhZGQiOiAiMi4yLjIuMiIsDQogICJwb3J0IjogIjIyMjIiLA0KICAiaWQiOiAiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwNCiAgImFpZCI6ICIwIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIyLjIuMi4yIiwNCiAgInBhdGgiOiAiL3YycmF5IiwNCiAgInRscyI6ICIiDQp9

**Comment by yiyedd** [comment]
同样的问题，最新版本 v0.7.1

**Comment by opojin** [comment]
我也是

**Comment by RSSYLY** [comment]
自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
