### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by yangyucacaa** [tindy2013/subconverter#373]
使用自动判断客户端时，cfw(0.18.1)添加订阅会显示failed with error: HTTP Response Status Code (400)。

mac和安卓的clash是正常的。

**Comment by yangyucacaa** [comment]
> 已解决

**Comment by yangyucacaa** [comment]
测试了很多遍还是有这个问题

**Comment by yangyucacaa** [comment]
测试了很多遍还是有这个问题

**Comment by RSSYLY** [comment]
包括readme里的关于UA的文章也缺失了

**Comment by zhongfly** [comment]
> 包括readme里的关于UA的文章也缺失了
https://github.com/tindy2013/subconverter/blob/c35714ba48b6bd2a4329c1727976e47cfe6e1d21/src/handler/interfaces.cpp#L121
