### ISSUE TITLE
subconverter_win64 v0.7.0 出现规则集分组名称错误

### ISSUE THREAD

**Issue by suiahae** [tindy2013/subconverter#378]
![图片](https://user-images.githubusercontent.com/45323123/134475329-064f1c0f-58ba-4ab7-a978-46593959c8ee.png)
使用默认规则`http://127.0.0.1:25500/sub?target=clash&url=`会发生上图错误。

经查找，发现文件`subconverter\snippets\rulesets.toml`和`subconverter\snippets\rulesets.txt`内，
网飞组名称为均为`;🎥 NETFLIX`，多了一个分号。改正后问题消失。

https://github.com/tindy2013/subconverter/releases/download/v0.7.0/subconverter_win64.7z

**Comment by tindy2013** [comment]
4454ef94ae3c1cce2d6c89feb722c6799920f7fd
