### ISSUE TITLE
希望加入ipv6: true参数

### ISSUE THREAD

**Issue by leechiuccc** [tindy2013/subconverter#379]
clashX作者一直没有在界面加入打开IPv6的按钮，只能曲线救国跑到用户配置文件里加入`ipv6: true`参数让核心直接支持。希望能通过订阅转换的方式加入该字段，不然每次订阅都要手动跑去改yaml属实麻烦

```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
ipv6: true
external-controller: :9090
proxies:
```

**Comment by CHIZI-0618** [comment]
@leechiuccc 
请仔细阅读[使用文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E8%BF%9B%E9%98%B6%E7%94%A8%E6%B3%95) .
你可以在[base/all_base.tpl](https://github.com/tindy2013/subconverter/blob/master/base/base/all_base.tpl) 文件的第五行与第六行之间写入 `ipv6: true` 达到目的

**Comment by leechiuccc** [comment]
已解决，感谢
