### ISSUE TITLE
请问下，哪个配置项，可以让规则订阅的url不加前缀

### ISSUE THREAD

**Issue by alecthw** [tindy2013/subconverter#380]
原来的地址是 https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Reject.list
不想被转换成下面这种形式，怎么配置
https://www.xxx.cc/sub/getruleset?type=2&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2xoaWUxL1J1bGVzL21hc3Rlci9TdXJnZS9TdXJnZSUyMDMvUHJvdmlkZXIvUmVqZWN0Lmxpc3Q&group=8J-bkSBBZEJsb2Nr

**Comment by zhongfly** [comment]
您提供的第一个链接是surge的规则
而第二个链接则是subconverter自动将surge规则转换成Quantumult X规则
为什么会“多管闲事”一般的自动转换呢？因为surge规则与Quantumult X并不通用
如果您直接使用Quantumult X规则，当然subconverter就不会做这样的自动转换了。
诚挚的希望您能仔细阅读readme

**Comment by alecthw** [comment]
> 您提供的第一个链接是surge的规则
> 而第二个链接则是subconverter自动将surge规则转换成Quantumult X规则
> 为什么会“多管闲事”一般的自动转换呢？因为surge规则与Quantumult X并不通用
> 如果您直接使用Quantumult X规则，当然subconverter就不会做这样的自动转换了。
> 诚挚地希望您能仔细阅读相关文档

这样啊，明白了，3q
