### ISSUE TITLE
国际战网是否不应该全走直连

### ISSUE THREAD

**Issue by JohnsonRan** [tindy2013/subconverter#381]
![image](https://user-images.githubusercontent.com/89735151/134660280-54183e73-48b5-4701-a9ba-b78f9f609910.png)
![image](https://user-images.githubusercontent.com/89735151/134660237-7a761d19-b111-4d04-8a17-aa9effc25b50.png)

**Comment by zhongfly** [comment]
请找规则仓库，这里是订阅转换工具的仓库

**Comment by JohnsonRan** [comment]
![image](https://user-images.githubusercontent.com/89735151/134661303-937bac9f-08d3-4dea-a9a7-bb87a2b71741.png)
啊，这里写与仓库同步正好上面有个项目仓库所以= =
打扰了
