### ISSUE TITLE
不能在模板文件中配置proxy-groups

### ISSUE THREAD

**Issue by MingSpace** [tindy2013/subconverter#408]
proxy-groups貌似只能配置在pref.ini的[custom_proxy_group]中，
在.tpl模板中无论在proxy-groups配置什么都会替换成 "proxy-groups: ~"
我想给不同的客户端配置不同的Proxy-Group，该怎么办？

**Comment by MingSpace** [comment]
希望可以和ruleset/rules一样可以设置覆盖or追加？

**Comment by LM-Firefly** [comment]
@MingSpace 不是有 if exists 吗

**Comment by zhongfly** [comment]
[外部配置](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE)

**Comment by MingSpace** [comment]
> @MingSpace 不是有 if exists 吗

试过在模板中给proxy-groups块加if，还是会发生同样的情况， 没有试过if exists，我想应该是一样的
目前用 @zhongfly 的方案解决，多谢！
