### ISSUE TITLE
直链本地转换失败，是什么原因？

### ISSUE THREAD

**Issue by Fzw0229** [tindy2013/subconverter#412]

**Comment by Fzw0229** [comment]
![image](https://user-images.githubusercontent.com/52545031/144747982-888396a7-b767-4245-bc96-59b29fd66bc6.jpeg)

**Comment by Fzw0229** [comment]
![image](https://user-images.githubusercontent.com/52545031/144747997-a0606dc9-278a-4f35-8f1c-4ea8c113e92a.jpeg)

**Comment by tindy2013** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/tindy2013/subconverter/issues/new/choose)
