### ISSUE TITLE
custom_proxy_group 的script写法

### ISSUE THREAD

**Issue by lix5027** [tindy2013/subconverter#414]
readme里提到custom_proxy_group=script`select`script:/path/to/script.js
请问大佬可否给一个script.js的例子?
比如筛选所有 udp 为true的,或者port为1234的?
我尝试按照readme里写的例子,发现return之后,只能反馈一个文本'ture',且无法return多个结果.

function filter(node) {
    if(node[0].Port=='1080') {
            return   ture;
            }
                return false;
            }
    
其中node应该是一个完整的数组,但是如何反馈多行给前台web页面?

**Comment by tindy2013** [comment]
此处应返回一个包含所有节点名称的字符串，使用换行符 `\n` 隔开
