### ISSUE TITLE
求解报错原因：terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by XinSSS** [tindy2013/subconverter#415]
2021/12/08 Wed 21:10:43.541224 [8768 1][INFO] Generate target: Clash
2021/12/08 Wed 21:10:43.721293 [8768 1][INFO] Gist id provided. Modifying Gist...
terminate called after throwing an instance of 'std::runtime_error'
  what():  assert

之前一直用的好好的， 今天突然报这种错误

**Comment by AyFun** [comment]
发现如果在linux下，订阅v2rayN的config.json，并且"streamSettings"下的"network"为 tcp 时就会报这个错，已测试最新的Actions依然报错。
