### ISSUE TITLE
docker自动更新了latest版本到最新，所有订阅都出问题了，换回0.7.1就好了

### ISSUE THREAD

**Issue by renkx** [tindy2013/subconverter#416]
docker自动更新了latest版本到最新，所有订阅都出问题了，感觉都会带测速和负载均衡，我明明设置的是不带，换回0.7.1就好了

**Comment by renkx** [comment]
![Uploading 1111122223123.png…]()

**Comment by renkx** [comment]
![image](https://user-images.githubusercontent.com/26194193/146118969-e3d537f6-b9f1-4c23-b6a6-19bfb70a744b.png)

**Comment by MingSpace** [comment]
我前几天也是在latest发现奇奇怪怪的毛病...
