### ISSUE TITLE
Surge配置中的skip-cert-verify参数，值应该是boolean，而不是数字

### ISSUE THREAD

**Issue by LarkinZero** [tindy2013/subconverter#418]
复现的版本：
subconverter v0.7.1-3fe9725 backend

源数据：
`Proxy = trojan, 123.com, 1001, password=abc123, sni=aaa.com, skip-cert-verify=true, tfo=true, udp-relay=true
`
转换后：
`Proxy = trojan, 123.com, 1001, password=abc123, sni=aaa.com, skip-cert-verify=0, tfo=true, udp-relay=true
`

参考Surge手册
[https://manual.nssurge.com/policy/proxy.html](url)

**Comment by tindy2013** [comment]
c10766f1ade9e9fc59e2098ca95ba056339b89bc
