### ISSUE TITLE
auto适配更多的客户端

### ISSUE THREAD

**Issue by jwstaceyOvO** [tindy2013/subconverter#421]
找到替代方案了，留给需要的人
map $http_user_agent $user {
    default            auto;
    ~v2ray            v2ray;
    ~Mozilla         v2ray;
    ""                    v2ray;
    ~clash            clash;
}
proxy_pass  http://127.0.0.1:25500/sub?target=$user

**Comment by devioa** [comment]
你能使用`auto`目标类型吗？我有个issue #586，我用不了auto，调用auto会返回`invalid target`你知道是怎么回事吗
