### ISSUE TITLE
多个订阅转换失败

### ISSUE THREAD

**Issue by sunjx97** [tindy2013/subconverter#422]
我的情况是这样，我有多个机场A、B、C，我想要把机场A的0.1倍率节点**提取出来**，然后B、C**不动**，再将三个订阅合并为一个。如果只是一般的过滤提取节点没有问题，但如果我将**转换后**的A机场订阅链接再和B、C订阅放在一起再进行一次转换就会报错（提示The following link doesn't contain any valid node info:【已转换的A机场订阅】 ）。请问这种问题有什么好的解决方法吗？谢谢

**Comment by thank243** [comment]
target统一同个类型，然后不要urlencode。

**Comment by sunjx97** [comment]
试了下，报同样的错误🤣，而且因为我对已转换的A机场订阅urldecode了，我想筛选A机场节点的【0.1或专线】这个条件的”|“被还原出来了，订阅转换把这个”|“当成了分隔多个订阅链接的分隔符了，错得更离谱😂

**Comment by sunjx97** [comment]
我通过GROUPID实现功能了，不好意思打搅大家了（用了这么久才发现有文档，草w
