### ISSUE TITLE
Quantumult X url-test策略组转换

### ISSUE THREAD

**Issue by jwstaceyOvO** [tindy2013/subconverter#425]
/config/ini里的url-test策略组应该转换为url-latency-benchmark才对，而不是available
例如
url-latency-benchmark=专线, server-tag-regex=(手游|游戏|专线|(?i)IPLC|IEPL|game), check-interval=1800, tolerance=10, img-url=https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png

**Comment by tindy2013** [comment]
Added in 6e3324be50ecd6d7484c38722db572ff288415ef
