### ISSUE TITLE
严重bug！

### ISSUE THREAD

**Issue by fengguowudi** [tindy2013/subconverter#426]
在最新的版本中，windows平台进行转换clash会导致vmess节点的aid参数变成0

**Comment by Karmylr** [comment]
> 在最新的版本中，windows平台进行转换clash会导致vmess节点的aid参数变成0

什么几把标题

**Comment by thank243** [comment]
如果不为0，你怕是连接不到服务器了。

**Comment by fengguowudi** [comment]
原订阅aid是1。。。。

**Comment by fengguowudi** [comment]
还有aid是2的

**Comment by Karmylr** [comment]
不安全

**Comment by fengguowudi** [comment]
本来能用，改成0就连接不上了

**Comment by NinjaUmbra** [comment]
@fengguowudi 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。

**Comment by fengguowudi** [comment]
我是说subconverter的问题，没说vmess的问题，这是转换出错了

**Comment by Karmylr** [comment]
> 我是说subconverter的问题，没说vmess的问题，这是转换出错了

不是哦

**Comment by fengguowudi** [comment]
那我alterid咋没了。。。这个后段不是进行的文字转换吗，也没让他链接呀

**Comment by Karmylr** [comment]
> 

原因上面的说过了
