### ISSUE TITLE
转换为vmess时所有额外ID(alterld)会变为0

### ISSUE THREAD

**Issue by fengguowudi** [tindy2013/subconverter#427]
这个问题仍然会出现
同：https://github.com/tindy2013/subconverter/issues/371
请问有哪个版本没这个问题吗

**Comment by fengguowudi** [comment]
https://github.com/tindy2013/subconverter/commit/e840006e74137a278f14b6700e017e94f8f17a3c
并未成功修复

**Comment by Karmylr** [comment]
🤡

**Comment by tindy2013** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/tindy2013/subconverter/issues/new/choose)
