### ISSUE TITLE
Feature Request: 支持Shadowsocks Android的订阅格式

### ISSUE THREAD

**Issue by HuanMeng0** [tindy2013/subconverter#43]
相关PR：https://github.com/shadowsocks/shadowsocks-android/pull/2392/files

该订阅功能的实现格式应该是JSON。

**Comment by tindy2013** [comment]
请先仔细阅读 README-cn 中 [支持类型](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E6%94%AF%E6%8C%81%E7%B1%BB%E5%9E%8B) 部分
