### ISSUE TITLE
subconverter_aarch64 版本bin文件在openwrt路由器里无法正常转换

### ISSUE THREAD

**Issue by ForestL18** [tindy2013/subconverter#430]
subconverter_aarch64 版本bin文件在openwrt路由器里无法正常转换，会不停循环，之前的0.6.4版本不会有这种问题
docker 版本正常
![image](https://user-images.githubusercontent.com/45709305/148065985-e2f0e88a-fc27-4feb-8b38-40b08dac21fd.png)

**Comment by zm24120** [comment]
ruleset太多了，减少到50个左右看看

**Comment by ForestL18** [comment]
> ruleset太多了，减少到50个左右看看

我的rulesets没超过50个啊，大概40个左右

**Comment by ForestL18** [comment]
还有就是为什么新版本rulesets太多不行呢？

**Comment by zm24120** [comment]
@ForestL18 配置文件有个参数设置

**Comment by ForestL18** [comment]
> @ForestL18 配置文件有个参数设置

```
[advanced]
log_level=info
print_debug_info=false
max_pending_connections=10240
max_concurrent_threads=2
max_allowed_rulesets=0
max_allowed_rules=0
max_allowed_download_size=0
enable_cache=false
cache_subscription=60
cache_config=300
cache_ruleset=21600
script_clean_context=true
async_fetch_ruleset=false
skip_failed_links=false
```

你是指这些参数吗？
我调了`max_allowed_rulesets=0`这个参数，改成64，但并没有效果

**Comment by zm24120** [comment]
@ForestL18 有好几个ini.yaml.toml,toml优先级最高

**Comment by ForestL18** [comment]
> @ForestL18 有好几个ini.yaml.toml,toml优先级最高

我给yaml，toml给删了，默认只使用ini
