### ISSUE TITLE
Clash1.9.0核心不再向前兼容vmess-ws的格式

### ISSUE THREAD

**Issue by eastexxiao** [tindy2013/subconverter#435]
Clash1.9.0在使用vmess-ws的时候要求为
# network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
使用0.7.1生成的配置无法在clash1.9.0中使用

**Comment by tindy2013** [comment]
6e3324be50ecd6d7484c38722db572ff288415ef
