### ISSUE TITLE
该怎么在termux上部署

### ISSUE THREAD

**Issue by hxse** [tindy2013/subconverter#437]
看到有arm平台的releases, 但是不知道该怎么部署, 有没有相关的脚本可以参考或使用的?

**Comment by CHIZI-0618** [comment]
#### 下载最新release并解压, 当然更建议使用 GitHub Action 中的版本.
`wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_aarch64.tar.gz && tar -zxvf subconverter_aarch64.tar.gz`
#### 启动示例.
`./subconverter/subconverter`
#### 如果需要常驻后台, 可在启动命令行行尾添加 ` &` 或者去了解 `nohup` 相关命令.
#### 若需要开机自启, 可借助 termux 的插件, 如果有Magisk, 可了解Magisk模块开发, 开发者指南: https://topjohnwu.github.io/Magisk/guides.html.

**Comment by hxse** [comment]
@CHIZI-0618 这个需要root权限吗

**Comment by hxse** [comment]
运行了一下, termux-chroot, 权限问题就解决了

**Comment by hxse** [comment]
@CHIZI-0618 
运行了但是会报: Unable to load preference settings. Reason: line 0: Target does not exist
```
2022/01/07 Fri 06:51:47.247532 [8081 4280652][INFO] SubConverter v0.7.1 starting up..
2022/01/07 Fri 06:51:47.345469 [8081 4280652][INFO] Reading preference settings...
2022/01/07 Fri 06:51:47.352195 [8081 4280652][FATL] Unable to load preference settings. Reason: line 0: Target does not exist
2022/01/07 Fri 06:51:47.353876 [8081 4280652][INFO] Startup completed. Serving HTTP @ http://127.0.0.1:25500```

**Comment by XinSSS** [comment]
我自己编译过, 如果正常的话, 编译出来的可执行文件不需要root就可以订阅生成配置, 但如果去release下载的话, 是需要root权限的..
悲剧的是, 上次手机坏了, 再配置一次termux的编译环境无力了

**Comment by ttttya** [comment]
> 我自己编译过, 如果正常的话, 编译出来的可执行文件不需要root就可以订阅生成配置, 但如果去release下载的话, 是需要root权限的.. 悲剧的是, 上次手机坏了, 再配置一次termux的编译环境无力了

那我不root怎么弄？用你说的这个编译吗？怎么操作
