### ISSUE TITLE
生成的Surge4配置如果规则是本地，配置文件中都是localhost

### ISSUE THREAD

**Issue by eastexxiao** [tindy2013/subconverter#438]
如果在ini中设置ruleset为本地的文件，使用Surge4生成的配置文件后，配置文件中的RULE-SET就会设为localhost，RULE-SET,http://127.0.0.1:25500/getruleset?(省略).
这样在surge中就无法获取到规则。是否有办法将该地址修改为eth0的地址或指定网卡信息？

**Comment by ftftyfy** [comment]
使用managed_config_prefix配置，可以替换掉生成的文件中的http://127.0.0.1:25500

**Comment by Blankeer** [comment]
修改pref.toml 的 managed_config_prefix

**Comment by cikichen** [comment]
我也是这样的

**Comment by eastexxiao** [comment]
> 
我work around了一下，强制指定expand=true后就可以把外挂的规则写入配置文件，就不需要再去访问规则文件了，一个配置文件包含了所有，FYI，但是手册里写这个默认是开启的，但是实际上似乎没开，需要手动配置一下
