### ISSUE TITLE
trojan配置会丢失sni参数

### ISSUE THREAD

**Issue by stcharlesc** [tindy2013/subconverter#440]
最新Release 0.7.1版 

Trojan 节点 TCP + TLS如果server参数是IP地址，转换成clash配置后会丢失sni参数

如果server是域名则不会

**Comment by tindy2013** [comment]
Please use Issue Template to create issue
请务必使用 Issue Template 创建 Issue

[Issue Template](https://github.com/tindy2013/subconverter/issues/new/choose)

**Comment by szkzn** [comment]
你好，我也采坑了，目前已解决，详见 https://github.com/tindy2013/subconverter/issues/447

**Comment by stcharlesc** [comment]
> @stcharlesc 你好，我也采坑了，目前已解决，详见 #447

感谢提醒 所以目前的最方便的解决方式就是手动修改链接sni为peer吗

**Comment by szkzn** [comment]
是的，次方便的办法是把域名绑定解析到IP上，这样可以实现兼容，因为 peer 不是 RFC 规范的字段， Ghost 、Qv2ray 等开发者极力反对引入 peer 字段，使用 peer 在 Qv2ray、V2rayN 上无法导入识别 peer 字段的trojan链接

**Comment by stcharlesc** [comment]
> 是的，次方便的办法是把域名绑定解析到IP上，继续使用sni字段，同时还可以实现兼容 标准规范的客户端，因为 peer 不是 RFC 规范的字段， Ghost 、Qv2ray 等开发者极力反对引入 peer 字段，详见我的那个 issue 查到的一些讨论结果，使用 peer 在 Qv2ray、V2rayN 上无法导入识别 peer 字段的trojan链接

明白了，感谢解答!
