### ISSUE TITLE
config是否可以支持本地文件路径的ini文件

### ISSUE THREAD

**Issue by Misaka09982** [tindy2013/subconverter#441]
&config=cdn链接时更新不及时，raw又经常失败，是否可以把ini文件放到config里，&config=填写本地路径

**Comment by CHIZI-0618** [comment]
本来就支持.
强烈建议看完文档再发 issue.
文档 [外部配置](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE).

**Comment by Misaka09982** [comment]
> 本来就支持. 强烈建议看完文档再发 issue. 文档 [外部配置](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE).

看了外部配置，在订阅转换连接写上default_external_config=config/clash.ini或者config=config/clash.ini都是默认配置，正确的写法是什么

**Comment by Wrandz** [comment]
config=config/clash.ini，就是这个，你路径是不是搞错了，不行你就config=clash.ini把配置文件放到相同文件夹下，我都试过是可以的。
