### ISSUE TITLE
希望适配最新的clash（0.19.5）写法

### ISSUE THREAD

**Issue by Ethanwish** [tindy2013/subconverter#442]
由于clash更新0.19.5后，格式变化，导致转换订阅后，链接不能适配新版clash。

**Comment by zhongfly** [comment]
已经就支持了，请升级至最新git版本(从action页面下载)
https://github.com/tindy2013/subconverter/commit/6e3324be50ecd6d7484c38722db572ff288415ef

**Comment by aLIEz-xue** [comment]
> 已经就支持了，请升级至最新git版本(从action页面下载) [6e3324b](https://github.com/tindy2013/subconverter/commit/6e3324be50ecd6d7484c38722db572ff288415ef)

有点不理解怎么下载

**Comment by zhongfly** [comment]
> > 已经就支持了，请升级至最新git版本(从action页面下载) [6e3324b](https://github.com/tindy2013/subconverter/commit/6e3324be50ecd6d7484c38722db572ff288415ef)
> 
> 有点不理解怎么下载

不懂就去看github文档 https://docs.github.com/cn/actions/managing-workflow-runs/downloading-workflow-artifacts

**Comment by Ethanwish** [comment]
在action页面，选择最新的库，然后拉到最下面，就能看到程序了，其实只需要替换主程序就行了

**Comment by aLIEz-xue** [comment]
> 

明白了，感谢

**Comment by aLIEz-xue** [comment]
> > > 已经就支持了，请升级至最新git版本(从action页面下载) [6e3324b](https://github.com/tindy2013/subconverter/commit/6e3324be50ecd6d7484c38722db572ff288415ef)
> > 
> > 
> > 有点不理解怎么下载
> 
> 不懂就去看github文档 https://docs.github.com/cn/actions/managing-workflow-runs/downloading-workflow-artifacts

谢谢

**Comment by fdmove** [comment]
自己编译，需要本地安装新版本的docker-ce，系统OS建议，选择和作者一致的Ubuntu 20.04。

在自己的海外VPS上面编译，可以减少异常。

我的VPS只有1核心1GB内存，故而，略微修改了编译脚本。

apt-get update
apt-get install git
mkdir -p /root/src
cd /root/src
git clone https://github.com/tindy2013/subconverter.git
sed -i 's/j4/j1/g' /root/src/subconverter/scripts/build.alpine.release.sh
sed -i 's/j2/j1/g' /root/src/subconverter/scripts/build.alpine.release.sh
docker pull multiarch/alpine:amd64-latest-stable
docker run -v /root/src/subconverter:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"


Refer My Blog Address: https://dasmz.com/?p=1169

完成编译后，会在该目录下，生成subconverter的目录，打包传输到需要运行subconverter的服务器，运行即可！！！

**Comment by zhongfly** [comment]
> 自己编译，需要本地安装新版本的docker-ce，系统OS建议，选择和作者一致的Ubuntu 20.04。
> 
> 在自己的海外VPS上面编译，可以减少异常。
> 
> 我的VPS只有1核心1GB内存，故而，略微修改了编译脚本。
> 
> apt-get update apt-get install git mkdir -p /root/src cd /root/src git clone https://github.com/tindy2013/subconverter.git sed -i 's/j4/j1/g' /root/src/subconverter/scripts/build.alpine.release.sh sed -i 's/j2/j1/g' /root/src/subconverter/scripts/build.alpine.release.sh docker pull multiarch/alpine:amd64-latest-stable docker run -v /root/src/subconverter:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
> 
> Refer My Blog Address: https://dasmz.com/?p=1169
> 
> 完成编译后，会在该目录下，生成subconverter的目录，打包传输到需要运行subconverter的服务器，运行即可！！！

我实在不明白，直接从action里下载编译好的版本不行吗？
相关链接：https://github.com/tindy2013/subconverter/actions/workflows/build.yml

另外看了你这篇文章，我才知道这错误的版本号从何而来，原来是“Fndroid发布的新版的Clash内核，v0.19.5版本”……
1. Fndroid发布的是CFW，不是clash内核，CFW在v0.19.5版本中自带的是clash内核 v1.9.0
2. 内核是在 https://github.com/Dreamacro/clash 发布的，兼容性发生变化的是[v1.9.0](https://github.com/Dreamacro/clash/releases/tag/v1.9.0)

希望你认真阅读相关文档，或者先阅读完 https://docs.cfw.lbyczf.com/#%E5%90%8D%E8%AF%8D 再写文章，以免误导他人
![image](https://user-images.githubusercontent.com/11155705/149613051-7b8bacfc-58af-49bb-bc91-64c76442e6e8.png)
如果不理解“图形客户端”，可以自行网络搜索

**Comment by fdmove** [comment]
好的，收到，已更正。谢谢
