### ISSUE TITLE
subconverter把skip-cert-verify: true改成了skip-cert-verify: false

### ISSUE THREAD

**Issue by Karmylr** [tindy2013/subconverter#444]
如题

**Comment by HynoR** [comment]
这玩意默认就是关掉的 除非开发用途 否则这个参数启用和裸奔没有区别

**Comment by Karmylr** [comment]
> 这玩意默认就是关掉的 除非开发用途 否则这个参数启用和裸奔没有区别

请问该怎么开起来呢 机场主是这么设置的

**Comment by HynoR** [comment]
自己手打批量替换 谢谢 本来这玩意就不是trojan/vmess协议规范里可以设置的参数，这个参数是通过能使用这些节点的软件定义的

**Comment by Karmylr** [comment]
> 自己手打批量替换 谢谢 本来这玩意就不是trojan/vmess协议规范里可以设置的参数，这个参数是通过能使用这些节点的软件定义的

好的 谢谢

**Comment by HynoR** [comment]
说白了就是 一个规范的vmess trojan节点是不存在跳过证书验证这个选项的
跳过证书验证这个功能不是节点让软件跳过证书验证 而是软件自己跳过证书验证，这个参数属于软件自行规定的，每个软件标准不一样，所以订阅转换没有办法通过原来的订阅里这个参数来生成新的参数

**Comment by tindy2013** [comment]
可以尝试解析原订阅里有的这些信息，除非在转换的参数中指定了 true 或 false

**Comment by LarkinZero** [comment]
不应该是按照配置文件里本来的参数值来转换么，原来什么值就是什么值。
把原来True的改成False，这是啥意思？

**Comment by Karmylr** [comment]
> 

还会改alterid呢
