### ISSUE TITLE
[BUG] ws+tls转换为clash规则时会将host和server会变成同一个地址

### ISSUE THREAD

**Issue by RnJ4** [tindy2013/subconverter#451]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.1-2f78eaf

### 转换过程

vmess链接转换为clash

### 转换设置

v2ray配置：
{
  "v": "2",
  "ps": "name",
  "add": "中转服务器域名",
  "port": "10086",
  "id": "c2de340b-a79d-48d8-8b30-xxxxxxxxxxxx",
  "aid": "0",
  "scy": "none",
  "net": "ws",
  "type": "none",
  "host": "",
  "path": "/path111111",
  "tls": "tls",
  "sni": "实际使用的tls的域名"
}

### 复现步骤

将以上配置转换为vmess分享链接，再使用subconverter转换
/sub?target=clash&url=vmess%3A%2F%2FewogICJ2IjogIjIiLAogICJwcyI6ICJuYW1lIiwKICAiYWRkIjogIuS4rei9rOacjeWKoeWZqOWfn%2BWQjSIsCiAgInBvcnQiOiAiMTAwODYiLAogICJpZCI6ICJjMmRlMzQwYi1hNzlkLTQ4ZDgtOGIzMC14eHh4eHh4eHh4eHgiLAogICJhaWQiOiAiMCIsCiAgInNjeSI6ICJub25lIiwKICAibmV0IjogIndzIiwKICAidHlwZSI6ICJub25lIiwKICAiaG9zdCI6ICIiLAogICJwYXRoIjogIi9wYXRoMTExMTExIiwKICAidGxzIjogInRscyIsCiAgInNuaSI6ICLlrp7pmYXkvb%2FnlKjnmoR0bHPnmoTln5%2FlkI0iCn0%3D

### 期望结果

proxies:
  - {name: name, server: 中转服务器域名, port: 10086, type: vmess, uuid: c2de340b-a79d-48d8-8b30-xxxxxxxxxxxx, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: "/path111111", headers: {Host: 实际使用tls的域名}}}

其中Host和server应该是不同的两个域名

### 实际结果

proxies:
  - {name: name, server: 中转服务器域名, port: 10086, type: vmess, uuid: c2de340b-a79d-48d8-8b30-xxxxxxxxxxxx, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: "/path111111", headers: {Host: 中转服务器域名}}}
  导致无法连接

**Comment by tindy2013** [comment]
若需要使用 Host header 值 请将域名填到 host 而不是 sni 中
