### ISSUE TITLE
无法过滤<_公告>这种节点

### ISSUE THREAD

**Issue by cikichen** [tindy2013/subconverter#454]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

latest

### 转换过程

exclude

### 转换设置

exclude%3D(%E6%B5%81%E9%87%8F%7C%E5%AE%98%E7%BD%91%7C%E8%BF%87%E6%9C%9F%7C%E5%85%AC%E5%91%8A)

### 复现步骤

url后面拼接exclude%3D(%E6%B5%81%E9%87%8F%7C%E5%AE%98%E7%BD%91%7C%E8%BF%87%E6%9C%9F%7C%E5%85%AC%E5%91%8A)

### 期望结果

能够过滤所有关键词，但是
<img width="354" alt="image" src="https://user-images.githubusercontent.com/1478821/153120890-36ecb079-cf25-4a7d-b4d7-b998ac7563db.png">
这种类型的过滤不掉

### 实际结果

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1478821/153120910-33bbde4f-8e27-45e7-86d5-0b178902cc39.png">

**Comment by zhongfly** [comment]
这部分参数是你自己拼接的吧？
在URL的Query String里变量名与变量值之间用=连接
所以应该为：
`exclude=%28%E6%B5%81%E9%87%8F%7C%E5%AE%98%E7%BD%91%7C%E8%BF%87%E6%9C%9F%7C%E5%85%AC%E5%91%8A%29`

**Comment by zhongfly** [comment]
请多看文档，或者使用sub-web帮助生成链接
