### ISSUE TITLE
[BUG] 转换订阅时，节点名称中出现�

### ISSUE THREAD

**Issue by Logic530** [tindy2013/subconverter#455]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.1-80cda7b

### 转换过程

clash 转换为 clash，添加 ACL4SSR 规则

### 转换设置

https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/config/ACL4SSR_Online.ini

### 复现步骤

尝试转换，原本节点名中出现 `\_` 的地方，在转换后出现�，在 clash for windows 中使用时没有问题，但在 clash for android 中使用时报错 Kr328/ClashForAndroid#1379

转换前后的订阅在 VSCode 中的显示
![image](https://user-images.githubusercontent.com/22793670/153715353-f3c3a458-288e-419d-aa0c-1c41d63627c6.png)
![image](https://user-images.githubusercontent.com/22793670/153715357-71bf4809-a717-4a78-9349-727f69688b3b.png)

### 期望结果

转换结果正常，没有�

### 实际结果

出现一个�

### 错误信息

```shell
和平时转换没有不同
```

**Comment by tindy2013** [comment]
这是 YAML 中可用的转义字符 若不想出现该符号 请不要这么写
