### ISSUE TITLE
dns配置

### ISSUE THREAD

**Issue by updater1234** [tindy2013/subconverter#46]
你好，请问可否在Clash(R)的配置文件中添加有关DNS的设置？

**Comment by tindy2013** [comment]
@updater1234 可以自行在 Clash Base 中添加 DNS 设置  将反映到生成的 Clash(R) 配置文件中

**Comment by updater1234** [comment]
是在原链接的配置文件中添加DNS设置吗？但问题是机场链接的文件没法改。

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/base/simple_base.yml
