### ISSUE TITLE
[Feature] 不覆盖原有代理

### ISSUE THREAD

**Issue by lazureice** [tindy2013/subconverter#467]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

simple_base 中设置rule，并且在config中设置overwrite_original_rules=false，simple_base 的rule就不会被覆盖。
但是 proxies 和 proxy-groups 似乎没有这样的开关，无论如何都会被覆盖。

希望能保留原有代理。

### 可能的解决方案

类似 overwrite_original_rules 的 overwrite_original_proxies

**Comment by ma20236544** [comment]
你好 我有同样的问题，请问你找到解决办法了吗？
