### ISSUE TITLE
Feature request: Support latest subscription protocol of ss

### ISSUE THREAD

**Issue by perqin** [tindy2013/subconverter#47]
The official Shadowsocks client (Windows and Android ports) has added the support of subscription. An [example subscription response](https://gist.github.com/madeye/8451355b1baba312dae78a6c8ca4d1a1) is also provided. It would be great to support it. The `ss` target in current release (0.3.0) outputs base64-encoded `ss://` lines, which is only ready for Import From Clipboard.

**Comment by tindy2013** [comment]
@perqin Please use target sssub to export Shadowsocks-Android-compatible subscription, which is already stated in README-cn.md.

**Comment by perqin** [comment]
Thanks! I've only read the English README. I am closing this issue.
