### ISSUE TITLE
[Feature] 是否考虑缩短生成的订阅链接

### ISSUE THREAD

**Issue by raddyyt** [tindy2013/subconverter#471]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [x] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

起因是我要用的app有地域限制，于是我用前端网站把我所有的订阅链接都放进去做关键字筛选，结果生成的链接长度太长，以至于在手机端无法使用。我已经翻遍了文档，似乎除了转成短链接以外没有任何办法能在使用别人的后端时缩短生成的链接长度。

### 可能的解决方案

可不可以在考虑多一些添加订阅链接的方式，比如允许写在外部配置文件里，像用“ruleset=”添加规则一样追加订阅链接。

**Comment by aliveday** [comment]
如果能这样添加订阅的话 维护起来也更方便了 当其中某条订阅失效时只要编辑一次外部配置文件就行了 现在碰上订阅失效就只能到客户端软件里去逐条修改 还是比较麻烦了
