### ISSUE TITLE
监听ipv6端口

### ISSUE THREAD

**Issue by jackadam1981** [tindy2013/subconverter#484]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [x] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [x] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述
`
root@OpenWrt:~# netstat -antup |grep subconverter

tcp        0      0 0.0.0.0:25500           0.0.0.0:*               LISTEN      2897/subconverter

root@OpenWrt:~# netstat -antup |grep 25500

tcp        0      0 0.0.0.0:25500           0.0.0.0:*               LISTEN      2897/subconverter

`

我尝试在openwrt上直接运行subconverter的二进制版本。
发现之监听了IPV4的端口，我的openwrt是双栈IPV4和IPV6，现在只能通过ipv4地址访问，不能通过ipv6地址访问。
随着IPV6的普及，省去了内网穿透，端口映射等配置，可以考虑兼容同时监听ipv4和ipv6的端口。

### 可能的解决方案

listen [::]:80
python flask 是这么解决的。
同时监听IPV4 IPV6

**Comment by jackadam1981** [comment]
看来没什么计划啊

**Comment by tindy2013** [comment]
套个 nginx

**Comment by jackadam1981** [comment]
是临时套了nginx，但是原生支持会更好。
