### ISSUE TITLE
[Feature] 保留或转发response header

### ISSUE THREAD

**Issue by SplitGemini** [tindy2013/subconverter#485]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [x] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

保留一些提供订阅信息的header，例如subscription-userinfo，一些软件会通过header显示流量信息，经过subconverter之后这些信息就丢失了

典型的header如下

```
content-disposition: attachment; filename=Clash_1651233353.yaml
subscription-userinfo: upload=296556980691; download=2974805645774; total=20219487584256; expire=1658910551
```

### 可能的解决方案

大概转发一下指定header就行吧

**Comment by zhongfly** [comment]
实际上已经有了，请尝试使用最新版本。

这个主要是看机场方面的设置，可能你使用的机场对于UA为特定软件时返回的Headers不包含流量信息

**Comment by littleneko** [comment]
> 

实测和 ua 应该没关系，用 postman 请求机场订阅链接返回 header 里有流量信息；请求 subconvert 转换后的链接，返回的 header 里就没有流量信息了。是不是 subconvert 配置有问题？用的是 docker:latest
