### ISSUE TITLE
[Feature] <本地配置路径>

### ISSUE THREAD

**Issue by yorunning** [tindy2013/subconverter#488]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [ ] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

config选项是否增加一个本地配置路的选项，例如config=http://127.0.0.1:25500/config/xxx.ini，谢谢！

**Comment by Lucio-0408** [comment]
@yorunning config=config/xxx.ini

**Comment by yorunning** [comment]
> @yorunning config=config/xxx.ini

感谢🙏
