### ISSUE TITLE
[ISSUE] 密码（可能还有其他字符串）在Clash for windows下显示字符串格式错误

### ISSUE THREAD

**Issue by GOUKI9999** [tindy2013/subconverter#507]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

自定义clash配置文件yml，和其他订阅合并为新的clash配置文件yml中

### 转换设置

http://localhost:25500/sub?target=clash&new_name=true&url=https%3A%2F%2Fsubscribe.aaaa.top%2Flink%2FIYpad6q5vHN9V3nR%3Fclash%3D2%7Chttps%3A%2F%2Fsubscribe.aaaa.top%2Flink%2FIYpad6q5vHN9V3nR%3Fsub%3D4%26game%3D1%7Chttps%3A%2F%2Faaaa.dns-dns.com%3A7043%2FPrivateServer.yml&insert=false&config=config%2FGOUKI_Local.ini

地址涉私隐去

### 复现步骤

导入clash for windows 订阅地址及配置无误，但生成的文件或订阅都存在相同问题，即

'password' expected type 'string', got unconvertible type 'float64'

这一问题是yml格式以及clash for windows所致，目前也有反馈但无妥善解决方案

https://github.com/Kr328/ClashForAndroid/issues/372

### 期望结果

在生成clash配置文件中的 proxies 字段时，可以对passsword 字段或指定字段的值（字符串）加上引号

可以保证如上或同类问题不出现（密码字段看起来符合16进制特征，如0a1b2c 852340等简单密码，在yml规则下被错误识别）

### 实际结果

见上出错信息

### 错误信息

该问题在clash for andriod和open clash (openwrt)上并不存在，仅限于windows

**Comment by Skyline5723** [comment]
解决了吗，好像现在还是有这个问题啊

**Comment by dingchundong** [comment]
貌似还没有弄好欸
