### ISSUE TITLE
Android Termux上无法获取node

### ISSUE THREAD

**Issue by llllllllqq** [tindy2013/subconverter#51]
用浏览器打开显示：The following link doesn't contain any valid node info.
命令行输出：Fetching node data from url.

而默认配置，相同命令，相同环境下，用电脑跑win64就能用。安卓arm64和armhf均报相同错误。

红米note5 安卓9 miui11 termux最新版（里面软件包也是最新的）。
已测试releases的0.3和0.27都不行

update：发现暂时解决办法，安装proot包，执行termux-chroot在chroot环境里执行就好了。怀疑是termux的环境不标准之类的，请作者加入个检测机制或者提示使用termux-chroot

**Comment by tindy2013** [comment]
@llllllllqq 由于运行库不同  Termux 下无法直接运行 Linux release  请手动构建

**Comment by llllllllqq** [comment]
> @llllllllqq 由于运行库不同 Termux 下无法直接运行 Linux release 请手动构建

感谢回复。
发现暂时解决办法，安装proot包，执行termux-chroot在chroot环境里执行就好了。直接用编译好的release版也能执行。
