### ISSUE TITLE
[Feature] emoji匹配问题

### ISSUE THREAD

**Issue by sunjx97** [tindy2013/subconverter#514]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

发现emoji生成时，节点名称中 iepl 匹配到了 pl（波兰）的国旗😂（`rule=(PL|POL|波兰),🇵🇱`），求解决。

**Comment by HynoR** [comment]
版本太老了吧 很久之前已经把双字国家缩写的emoji规则移除掉了

**Comment by sunjx97** [comment]
这条规则是我自己写的自定义规则🤣，因为之前有节点用到。
其实可以把这条规则放在最下面最后匹配解决问题，只是想知道有没有更好的解决方法。
