### ISSUE TITLE
[BUG] <response header 中Subscription-UserInfo信息获取异常>

### ISSUE THREAD

**Issue by pjylilac** [tindy2013/subconverter#517]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.2

### 转换过程

机场链接转化为clash

### 转换设置

http://localhost:25500/sub?target=clash&url=111&insert=false&append_type=true&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&append_info=true&udp=true&new_name=true

### 复现步骤

浏览器直接访问转换链接，添加参数append_info=true。response header中存在Subscription-UserInfo信息。
当使用curl -I 直接获取header信息，出现404 

### 期望结果

正确返回header信息

### 实际结果

HTTP/1.1 404 Not Found

### 错误信息

```shell
log输出
2022/06/20 Mon 14:40:04.884445 [71796 0x700005aaf000][DEBG] Accept connection from client 127.0.0.1:57149
2022/06/20 Mon 14:40:04.884480 [71796 0x700005aaf000][VERB] handle_cmd:    HEAD handle_uri:    /sub?target=clash&urlXXXXXXXX

返回值
HTTP/1.1 404 Not Found
Date: Mon, 20 Jun 2022 06:40:04 GMT
```

**Comment by zhangdiming** [comment]
> ### 确认版本最新
> * [x]  我已经确认在最新Action编译的版本中复现
> 
> ### 检索issue
> * [x]  我已经确认之前没有issue涉及此BUG
> 
> ### subconverter版本
> v0.7.2
> 
> ### 转换过程
> 机场链接转化为clash
> 
> ### 转换设置
> http://localhost:25500/sub?target=clash&url=111&insert=false&append_type=true&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&append_info=true&udp=true&new_name=true
> 
> ### 复现步骤
> 浏览器直接访问转换链接，添加参数append_info=true。response header中存在Subscription-UserInfo信息。 当使用curl -I 直接获取header信息，出现404
> 
> ### 期望结果
> 正确返回header信息
> 
> ### 实际结果
> HTTP/1.1 404 Not Found
> 
> ### 错误信息
> ```shell
> log输出
> 2022/06/20 Mon 14:40:04.884445 [71796 0x700005aaf000][DEBG] Accept connection from client 127.0.0.1:57149
> 2022/06/20 Mon 14:40:04.884480 [71796 0x700005aaf000][VERB] handle_cmd:    HEAD handle_uri:    /sub?target=clash&urlXXXXXXXX
> 
> 返回值
> HTTP/1.1 404 Not Found
> Date: Mon, 20 Jun 2022 06:40:04 GMT
> ```

使用curl -I -X GET 可以正确获取订阅信息

**Comment by pjylilac** [comment]
已解决
