### ISSUE TITLE
[Feature] 建议支持本地文件的订阅转换

### ISSUE THREAD

**Issue by yu-steven** [tindy2013/subconverter#519]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

细说就是可以直接对subconverter目录下的文件直接进行转换

举例子：把一个名为input的base64的文件放置在subconverter同一目录，通过一个类似 subconverter --clash -i input -o output.yaml 这样的命令，可以直接在同一目录生成output.yaml 这样的Clash配置文件

**这有利于自动化部署，如果可以，望采纳！**

### 可能的解决方案

现在的替换解决方案就是上传到GitHub或者GitHub的gist
然后通过现有的配置好的 subconverter -g 命令自动化部署

**Comment by yu-steven** [comment]
> 目前subconverter -g就可以实现你的目的吧，url里面可以直接填写文件路径


我现在用的确实是 subconverter -g 但是需要转换的文件只能是远程文件(https://)

**所以可不可以是本地的文件呢？**

**Comment by yu-steven** [comment]
> 可以啊，url里面直接写本地文件路径

哦哦哦，哈哈哈，我试试

**Comment by yu-steven** [comment]
啊确实可以，谢谢提醒啦 @Evolution404

**Comment by yu-steven** [comment]
成功啦，哈哈哈哈哈哈哈，我真是个大聪明

**Comment by XhstormR** [comment]
建议完善下文档 example，刚看到也不知道这个 url 可以填本地路径
