### ISSUE TITLE
建议添加调用“Url-Shorten-Worker”API生成短链接

### ISSUE THREAD

**Issue by vitaminx** [tindy2013/subconverter#520]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [x] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

建议添加调用[Url-Shorten-Worker](https://github.com/xyTom/Url-Shorten-Worker)的API，实现短连接

**Comment by zhongfly** [comment]
有关前端页面的建议请去 https://github.com/CareyWang/sub-web
