### ISSUE TITLE
[BUG] /version 的返回状态不应该是error 404

### ISSUE THREAD

**Issue by gouku** [tindy2013/subconverter#528]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.2-f6e77b7

### 转换过程

无需转换，和转换无关

### 转换设置

无需转换，和转换无关

### 复现步骤

curl -I http://localhost:25500/version

### 期望结果

返回200结果，而不是404，因为现在是404，导致无法通过docker 的healthcheck进行检查

### 实际结果

返回404

**Comment by youshandefeiyang** [comment]
@gouku 使用大写I只能得到请求头，subc的webserver里面file_not_find是直接返回404的，把大写I改成小写i辅助判断就行
