### ISSUE TITLE
[Feature] 重定向shell输出

### ISSUE THREAD

**Issue by fxzxmic** [tindy2013/subconverter#533]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

似乎subconverter并不能重定向执行日志到文件？
希望可以添加此功能以便进行错误分析。

### 可能的解决方案

当然我明白这样会导致公开服务的subconverter可以保存用户的订阅链接，不利于用户使用的安全性，但我觉得这属于程序设计的不足之处，因为完全没有必要输出日志的同时输出完整的订阅链接地址，最多输出链接的host部分足够了，希望可以考虑下。

**Comment by youshandefeiyang** [comment]
@fxzxmic web server大都自带url参数记录日志输出，反代一下就行了。
或者用supervisor[基于Python]、PM2[基于node]进程管理工具也都是自带日志输出，或者直接用docker都可以保留完整的日志记录

**Comment by fxzxmic** [comment]
我用的是本地生成模式。
至于你说的后两个，我觉得有些小题大做了，我的subconverter是托管于Guthub Actions的。

**Comment by tindy2013** [comment]
Google [shell redirect stderr](https://www.google.com/search?q=shell+redirect+stderr)
