### ISSUE TITLE
[Feature] 请问是否支持ss + SIP003？

### ISSUE THREAD

**Issue by jearton** [tindy2013/subconverter#535]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [x] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

我看到文档里描述的是SIP002，不知道SIP003能否支持呢？

**Comment by EKyero** [comment]
你对sip003是不是有什么误解。。。

**Comment by jearton** [comment]
> 你对sip003是不是有什么误解。。。

SIP003是ss的插件规范吗？我服务端是单节点ss+v2ray-plugin，能否使用你这个工具转换成clash订阅地址？

**Comment by tindy2013** [comment]
先试再问
