### ISSUE TITLE
[BUG] 订阅返回配置会在某个部位截断

### ISSUE THREAD

**Issue by waltcow** [tindy2013/subconverter#537]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v.0.7.2

### 转换过程

clash

### 转换设置

https://user-images.githubusercontent.com/3941174/186054584-6e1e5600-c175-4b2d-809d-1703d88f05e5.png

### 复现步骤

pref.toml 中没有对最大规则数进行限制
```
[advanced]
log_level = "debug"
print_debug_info = true
max_pending_connections = 10240
max_concurrent_threads = 4
max_allowed_rulesets = 128
max_allowed_rules = 0
max_allowed_download_size = 0
enable_cache = true
cache_subscription = 120
cache_config = 300
cache_ruleset = 216000
script_clean_context = true
async_fetch_ruleset = false
skip_failed_links = true
```

### 期望结果

正常输出

### 实际结果

https://user-images.githubusercontent.com/3941174/186054584-6e1e5600-c175-4b2d-809d-1703d88f05e5.png

### 错误信息

```shell
日志正常
```

**Comment by tindy2013** [comment]
网络问题

**Comment by waltcow** [comment]
@tindy2013 主机在国外的，如何排查规则集的问题
