### ISSUE TITLE
[BUG] The following link doesn't contain any valid node info

### ISSUE THREAD

**Issue by tsiens** [tindy2013/subconverter#548]
### subconverter版本

0.7.2

### 转换过程

https://s.youyun666.site/link/***********

### 转换设置

https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_AdblockPlus.ini

### 复现步骤

在本地docker搭建的0.7.2中，返回No nodes were found，docker日志显示The following link doesn't contain any valid node info。回退到0.5.X版本可以正常获取节点，但是由于格式与最新clash不符无法使用
使用https://acl4ssr-sub.github.io  网页上的在线转换，就可以正常拿到

### 期望结果

正常获取节点

### 实际结果

The following link doesn't contain any valid node info

**Comment by ptt5em** [comment]
这个问题似乎和机场url有关，有些机场开了防火墙，就会出现这问题，我也碰到了，换个机场就不会

**Comment by Attiv** [comment]
same

**Comment by panda62** [comment]
我也是相同的情况
而且客户端只有选择clash能输出结果，选择其他的接口都没有数据返回

**Comment by panda62** [comment]
例如我选择了v2ray，日志看着是有增加节点的，但是没有结果输出

**Comment by mw418** [comment]
自己部署的0.7.2使用最新镜像 会出现该问题
sub.xeton.dev 没有此问题

**Comment by zhychen1173** [comment]
> 
sub.xeton.dev  同样有这个问题。
