### ISSUE TITLE
在Windows Server2016上出现SSL错误导致规则不完整

### ISSUE THREAD

**Issue by yshtcn** [tindy2013/subconverter#55]
规则是默认配置里包括的ConnersHua的Telegram.list，输出目标是surge2和surge4，在Windows10 1909上配置好反复测试是正常的。在Windows2016上经常就会出现配置规则少了的情况，打开debug模式，发现报错如下：

```
Updating ruleset url 'https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Telegram.list' with group '���报信息'.
*   Trying 151.101.0.133:443...
* TCP_NODELAY set
* Connected to raw.githubusercontent.com (151.101.0.133) port 443 (#0)
* ALPN, offering http/1.1
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443
* Closing connection 0
Warning: No data was fetched from this link. Skipping...
```

顺带一提：如果输出为surge3，surge4的外置规则列表，最终输出为规则的只有一行：
`RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Telegram.list,电报信息`

但程序无法下载时，就会不输出这一行规则。

我的subconverter版本是0.3.0

**Comment by tindy2013** [comment]
对于这种无法正常下载 ruleset 的问题 推荐设置 proxy_ruleset 选项 或者使用本地 ruleset 解决

**Comment by yshtcn** [comment]
您的意思是：这个错误还是由网络问题造成的，对吗？

可不可以为 proxy_ruleset 配置增加替补规则和缓存规则。
替补规则：一个规则可以输入多个网址或文件地址，当下载失败时使用下一个网址或文件地址。
缓存规则：当下载完成后，写入指定的文件。

**Comment by tindy2013** [comment]
以后会考虑加入
