### ISSUE TITLE
如何添加额外配置规则？不是覆盖规则

### ISSUE THREAD

**Issue by hudingwen** [tindy2013/subconverter#551]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

比如最近的谷歌翻译域名在中国停用了，每次我在clash中添加对谷歌翻译的过滤规则后一旦clash订阅链接更新后就无法使用谷歌翻译，必须重新一遍谷歌翻译。

**Comment by ipx2001** [comment]
我把规则添加进去了，但是在clash查看，添加的规则都是在最低层，手动移动到最上面就生效了，不知道怎么彻底解决这个情况！每次换新的订阅都要手动调整到最上面才会有效果！

**Comment by WheaeSong** [comment]
> 我把规则添加进去了，但是在clash查看，添加的规则都是在最低层，手动移动到最上面就生效了，不知道怎么彻底解决这个情况！每次换新的订阅都要手动调整到最上面才会有效果！

**Comment by WheaeSong** [comment]
> 我把规则添加进去了，但是在clash查看，添加的规则都是在最低层，手动移动到最上面就生效了，不知道怎么彻底解决这个情况！每次换新的订阅都要手动调整到最上面才会有效果！

可以通过更改clash设置-配置-配置文件预处理，这样子每次更新订阅的时候就会在订阅配置中重写，但是是配置了谷歌翻译也没通，虽然他确实已经写入订阅的设置中去了。

**Comment by tindy2013** [comment]
将添加的规则移动到配置文件中规则部分的顶部

**Comment by WheaeSong** [comment]
不是，他确实是写在顶部了，但确实不太对，不知道是不是写错了规则，
如下图，这是配置预处理之后重写的规则


从 Windows 版邮件发送

发件人: Tindy X
发送时间: 2022年12月30日 15:22
收件人: tindy2013/subconverter
抄送: WheaeSong; Comment
主题: Re: [tindy2013/subconverter] 如何添加额外配置规则？不是覆盖规则 (Issue #551)

将添加的规则移动到配置文件中规则部分的顶部

**Comment by dckill** [comment]
我有个办法, 我是用docker部署的, 我把snippets文件映射到了外部, 可以通过修改rulesets.toml文件内规则排序置顶自己新添加的规则
