### ISSUE TITLE
[BUG] profile中如何指定多个订阅url

### ISSUE THREAD

**Issue by jesseincn** [tindy2013/subconverter#558]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.2

### 转换过程

http://127.0.0.1:25500/getprofile?name=profiles/example_profile.ini&token=password

### 转换设置

http://127.0.0.1:25500/getprofile?name=profiles/example_profile.ini&token=password

### 复现步骤

- profile添加2个订阅链接

- 执行http://127.0.0.1:25500/getprofile?name=profiles/example_profile.ini&token=password生成

### 期望结果

的到两个订阅链接的所有节点

### 实际结果

只有一个订阅url的节点

**Comment by biteliang** [comment]
在pref文件里编辑,可以得到多个订阅地址吧

**Comment by tindy2013** [comment]
在一个 url 条目后面用 | 连接多个订阅链接
