### ISSUE TITLE
[建议]增加Surge的SSID Group的支持

### ISSUE THREAD

**Issue by yshtcn** [tindy2013/subconverter#56]
虽然我不太确定功能上是不是支持，但subconverter似乎不支持SSID Group的输出，对吗？
我尝试用了很多办法也没办法加上最终的输出文件上加上一行SSID Group的配置，包括修改perf.ini或者修改surge.conf的基础规则模版.

因为家里的路由环境已经配置好了，所以常用ssid group。而且surge的SSID功能推出的非常早，包括surge mac 2.0 也是支持的。

参考：https://manual.nssurge.com/policy/group.html

我当前使用的subconverter版本是0.3.0，环境是Windows2016和Windows10 1909.
非常感谢您项目。

**Comment by tindy2013** [comment]
Fixed in commit [ac75c95](https://github.com/tindy2013/subconverter/commit/ac75c9513a48f8a04af96ed145f4c154f06cc449)
