### ISSUE TITLE
[错误] 运行时无法读取设置

### ISSUE THREAD

**Issue by leeharuhiofcn** [tindy2013/subconverter#560]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.2

### 转换过程

运行subconverter.exe时

### 转换设置

none

### 复现步骤

none

### 期望结果

none

### 实际结果

Unable to load preference settings. Reason: line 29: Item exists outside of any section

### 错误信息

```shell
这里的 29行 是指哪个文件？
```

**Comment by cool-ic** [comment]
同遇到了，请问如何解决的？
