### ISSUE TITLE
[BUG] 处理vmess链接时，path丢失变为/

### ISSUE THREAD

**Issue by AyFun** [tindy2013/subconverter#568]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

vmess链接转clash

### 转换设置

默认

### 复现步骤

vmess://ewogICAgImFkZCI6ICIyMDMuMjQuMTA4LjkiLAogICAgImFpZCI6IDAsCiAgICAiaG9zdCI6ICJvcGZyMS52MnJheWZyZWUxLnh5eiIsCiAgICAiaWQiOiAiNDYxMjYxOGMtMjRjZC00Mzc5LTk5MjQtY2ZkZjNkNjFmYTVhIiwKICAgICJuZXQiOiAid3MiLAogICAgInBhdGgiOiAiL0lZS0xENTNNIiwKICAgICJwb3J0IjogNDQzLAogICAgInBzIjogIjExMTEiLAogICAgInRscyI6ICJ0bHMiLAogICAgInR5cGUiOiAiYXV0byIsCiAgICAic2VjdXJpdHkiOiAiYXV0byIsCiAgICAic2tpcC1jZXJ0LXZlcmlmeSI6IHRydWUsCiAgICAic25pIjogIiIKfQ==

### 期望结果

  - {name: 1111, server: 203.24.108.9, port: 443, type: vmess, uuid: 4612618c-24cd-4379-9924-cfdf3d61fa5a, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /IYKLD53M, headers: {Host: opfr1.v2rayfree1.xyz}}}

### 实际结果

  - {name: 1111, server: 203.24.108.9, port: 443, type: vmess, uuid: 4612618c-24cd-4379-9924-cfdf3d61fa5a, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /, headers: {Host: opfr1.v2rayfree1.xyz}}}

**Comment by Masaiki** [comment]
base64 decode 之后
{
    "add": "203.24.108.9",
    "aid": 0,
    "host": "opfr1.v2rayfree1.xyz",
    "id": "4612618c-24cd-4379-9924-cfdf3d61fa5a",
    "net": "ws",
    "path": "/IYKLD53M",
    "port": 443,
    "ps": "1111",
    "tls": "tls",
    "type": "auto",
    "security": "auto",
    "skip-cert-verify": true,
    "sni": "",
    "v": "2"
}
缺少 v 这一项，默认为 1，按照 v1 版本的链接去解析所以出错了
添加之后链接为
vmess://ewogICAgImFkZCI6ICIyMDMuMjQuMTA4LjkiLAogICAgImFpZCI6IDAsCiAgICAiaG9zdCI6ICJvcGZyMS52MnJheWZyZWUxLnh5eiIsCiAgICAiaWQiOiAiNDYxMjYxOGMtMjRjZC00Mzc5LTk5MjQtY2ZkZjNkNjFmYTVhIiwKICAgICJuZXQiOiAid3MiLAogICAgInBhdGgiOiAiL0lZS0xENTNNIiwKICAgICJwb3J0IjogNDQzLAogICAgInBzIjogIjExMTEiLAogICAgInRscyI6ICJ0bHMiLAogICAgInR5cGUiOiAiYXV0byIsCiAgICAic2VjdXJpdHkiOiAiYXV0byIsCiAgICAic2tpcC1jZXJ0LXZlcmlmeSI6IHRydWUsCiAgICAic25pIjogIiIsCiAgICAidiI6ICIyIgp9
解析就没问题了
