### ISSUE TITLE
[BUG] Trojan WS转换不正常

### ISSUE THREAD

**Issue by e5u** [tindy2013/subconverter#569]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

Trojan转换为Clash配置

### 转换设置

example_profile.ini

### 复现步骤

将Trojan ws节点转换为clash节点，给出的结果中password字段会有 `!<str>` 且未给出ws配置

给出出错的Trojan ws节点例子
`trojan://123@example.com:443?path=%2Fmypath&security=tls&host=example.com&type=ws&sni=example.com#example`

### 期望结果

转换后的配置文件中没有错误字段且ws配置正确

### 实际结果

```
proxies:
  - {name: example, server: example.com, port: 443, type: trojan, password: !<str> 123, sni: example.com, skip-cert-verify: false}
```

**Comment by Masaiki** [comment]
能确认问题出在哪，但我比较好奇
trojan://123@example.com:443?path=%2Fmypath&security=tls&host=example.com&type=ws&sni=example.com#example
是怎么生成出来的

**Comment by e5u** [comment]
使用v2rayN或v2rayNG生成的

菜姬 ***@***.***> 于 2023年1月14日周六 13:34写道：

**Comment by Masaiki** [comment]
可以试一下 https://github.com/Masaiki/subconverter/actions/runs/3918397951 的构建产物
