### ISSUE TITLE
Gist上传功能出错：本地报失败，Gist上已生成。

### ISSUE THREAD

**Issue by penuser** [tindy2013/subconverter#57]
如题，本地会报Create new Gist failed! Return data: XXXXXXXX
但是去gist页面上却能看见成功新创建的文件，并且时间戳也对得上。

转换目标文件类型：clash
上传github尝试过使用/不使用代理

**Comment by tindy2013** [comment]
这是 GitHub 的锅吧，没有正常返回 HTTP 201 Created。本地测试正常

**Comment by Skimige** [comment]
同遇到这个问题，Return data 为空却创建成功了。
而且 bug 一直存在，导致每一次上传都会创建一个新的 gist
