### ISSUE TITLE
[Feature] <title>希望能增加对vless链接的支持

### ISSUE THREAD

**Issue by sanzo-mlgb** [tindy2013/subconverter#574]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

因为对udp FullCone的需求，切换到了xray核心，协议也换到了vless，但subconverter不支持vless协议

**Comment by Karmylr** [comment]
https://github.com/MetaCubeX/subconverter

**Comment by youshandefeiyang** [comment]
https://sub.v1.mk

**Comment by sanzo-mlgb** [comment]
> https://github.com/MetaCubeX/subconverter

十分感谢

**Comment by kitkw** [comment]
> https://github.com/MetaCubeX/subconverter
metacubex/clash-meta:latest
运行不了？？？
2023-02-28T15:43:34.468076207Z exec /clash: no such file or directory
2023-02-28T15:43:35.404370901Z exec /clash: no such file or directory
2023-02-28T15:43:36.194506510Z exec /clash: no such file or directory
2023-02-28T15:43:36.950172556Z exec /clash: no such file or directory
2023-02-28T15:43:38.121707238Z exec /clash: no such file or directory
2023-02-28T15:43:40.083152025Z exec /clash: no such file or directory
2023-02-28T15:43:43.686109461Z exec /clash: no such file or directory
2023-02-28T15:43:50.454092008Z exec /clash: no such file or directory

**Comment by sanzo-mlgb** [comment]
> > https://github.com/MetaCubeX/subconverter
> > metacubex/clash-meta:latest
> > 运行不了？？？
> > 2023-02-28T15:43:34.468076207Z exec /clash: no such file or directory
> > 2023-02-28T15:43:35.404370901Z exec /clash: no such file or directory
> > 2023-02-28T15:43:36.194506510Z exec /clash: no such file or directory
> > 2023-02-28T15:43:36.950172556Z exec /clash: no such file or directory
> > 2023-02-28T15:43:38.121707238Z exec /clash: no such file or directory
> > 2023-02-28T15:43:40.083152025Z exec /clash: no such file or directory
> > 2023-02-28T15:43:43.686109461Z exec /clash: no such file or directory
> > 2023-02-28T15:43:50.454092008Z exec /clash: no such file or directory

跟本repo一模一样的用法，我没遇到什么问题

**Comment by kitkw** [comment]
> > > https://github.com/MetaCubeX/subconverter
> > > metacubex/clash-meta:latest
> > > 运行不了？？？
> > > 2023-02-28T15:43:34.468076207Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:35.404370901Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:36.194506510Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:36.950172556Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:38.121707238Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:40.083152025Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:43.686109461Z exec /clash: no such file or directory
> > > 2023-02-28T15:43:50.454092008Z exec /clash: no such file or directory
> 
> 跟本repo一模一样的用法，我没遇到什么问题

好吧！我搞错了镜像。哈哈！！
请问怎样使用此库？有现成镜像吗？

**Comment by kitkw** [comment]
兄弟可以请教一下怎样使用repo 吗?已经申请了pattoken 填进去还是构建失败的。想PUSH dockerhub 将主仓的docker.yml搞进去还是构建失败。。。（docker 账号变量已填）

**Comment by sanzo-mlgb** [comment]
> 兄弟可以请教一下怎样使用repo 吗?已经申请了pattoken 填进去还是构建失败的。想PUSH dockerhub 将主仓的docker.yml搞进去还是构建失败。。。（docker 账号变量已填）

我对docker不熟欸，都是直接用releases里的

**Comment by kitkw** [comment]
好吧！那先不搞它。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢

**Comment by zhouwencn** [comment]
> 好吧！那先不搞docker。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢

现在clash支持vless转过来的订阅吗？

**Comment by Karmylr** [comment]
> > 好吧！那先不搞docker。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢
> 
> 现在clash支持vless转过来的订阅吗？

clash.meta支持

**Comment by zhouwencn** [comment]
> clash.meta

好的，我研究一下

**Comment by zhouwencn** [comment]
> > > 好吧！那先不搞docker。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢
> > 
> > 
> > 现在clash支持vless转过来的订阅吗？
> 
> clash.meta支持

我想问一下，这个subconvert怎么启动啊，网上也找不到，readme也没有写，真的崩溃了

**Comment by Karmylr** [comment]
> 

指令./subconverter

**Comment by Karmylr** [comment]
> > > > 好吧！那先不搞docker。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢
> > > 
> > > 
> > > 现在clash支持vless转过来的订阅吗？
> > 
> > 
> > clash.meta支持
> 
> 我想问一下，这个subconvert怎么启动啊，网上也找不到，readme也没有写，真的崩溃了

指令./subconverter

**Comment by zhouwencn** [comment]
> 

尝试过，但是不行似乎，我的是m系列的mac，然后去release里面下载了一个arrch64的包，cd进去，执行./subconverter，似乎并没有成功，只是打印zsh: exec format error: ./subconverter,使用lsof -i:25500也没有任何信息展示

**Comment by kitkw** [comment]
> > 好吧！那先不搞docker。但我fork了后，直接触发它action还是全部构建失败的，能不能复现一下你的步骤。感谢
> 
> 现在clash支持vless转过来的订阅吗？
我没有玩成我是arm64,releases也没有这个.........
自己也不会触发构建.....

**Comment by AkariiinMKII** [comment]
@zhouwencn 那就用darwin64

**Comment by zhouwencn** [comment]
> @zhouwencn 那就用darwin64

多谢，使用这个包OK了

**Comment by sherlock-png** [comment]
> @zhouwencn 那就用darwin64

感谢大佬。。。我也用了aarch64不能用

**Comment by jacobin** [comment]
> https://github.com/MetaCubeX/subconverter

[subconverter.MetaCubex](https://github.com/MetaCubeX/subconverter)对mihomo／meta新增协议譬如vless有支持。但是支持不完整。譬如对vless的支持就不完整，只支持了vless-tcp，没有支持vless-ws：
https://github.com/tindy2013/subconverter/issues/611#issuecomment-3435277158
