### ISSUE TITLE
QX [BUG] <title>

### ISSUE THREAD

**Issue by JoeJoeLam** [tindy2013/subconverter#576]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

tindy2013/subconverter:latest

### 转换过程

vmess转QX

### 转换设置

[filter_remote]下订阅规则地址错误，直接显示为http://127.0.0.1:25500/getruleset?type=2&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvTG9jYWxBcmVhTmV0d29yay5saXN0&group=8J-OryDlhajnkIPnm7Tov54, tag=???? 全球直连, enabled=true，如果将http://127.0.0.1:25500改为subconveroter实际地址，就可以正常访问

### 复现步骤

1输入vmess
2选择acl去广告规则
3客户端选QX

### 期望结果

[filter_remote]下订阅规则地址修正

### 实际结果

[filter_remote]下订阅规则地址错误，直接显示为http://127.0.0.1:25500/getruleset?type=2&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvTG9jYWxBcmVhTmV0d29yay5saXN0&group=8J-OryDlhajnkIPnm7Tov54, tag=???? 全球直连, enabled=true，如果将[filter_remote]下订阅规则地址

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L149
