### ISSUE TITLE
v2ray订阅节点中含有vmess和ss协议节点的出错。

### ISSUE THREAD

**Issue by SenLief** [tindy2013/subconverter#58]
如果订阅中同时含有vmess和ss的节点，生成后会无法导入clash提示错误。

Could not switch to this profile!
Proxy 107: 'password' expected type 'string', got unconvertible type 'float64'

**Comment by tindy2013** [comment]
Should be fixed in commit [ac0dede](https://github.com/tindy2013/subconverter/commit/ac0dedecf06c369124b2e7a8596c75abc06e599b)
