### ISSUE TITLE
能不能补充一下readme，说一下怎么启动这个项目啊[

### ISSUE THREAD

**Issue by zhouwencn** [tindy2013/subconverter#581]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

能不能补充一下怎么运行这个项目啊，根本不知道怎么启动这个C++项目

**Comment by Kiswelrg** [comment]
同文 文档读半天没有

**Comment by Kiswelrg** [comment]
./subconverter 启动，我刚开始也没启动起，因为不支持m系列 mac，试了下linux

**Comment by zhouwencn** [comment]
> ./subconverter 启动，我刚开始也没启动起，因为不支持m系列 mac，试了下linux
它这个是支持m系列的，我一开始用的arm64的根本不行，后面在一个issue下面有人告诉我，下载那个Darwin的包就可以了，我试了一下确实可以，你可以试试
