### ISSUE TITLE
[Feature] <如何添加自定义的clash rule>

### ISSUE THREAD

**Issue by beacon007** [tindy2013/subconverter#582]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

对于clash，如何添加自定义的`DOMAIN-SUFFIX`? 当前我有一些域名，走的是漏网之鱼，我想改下配置文件，增加一个`DOMAIN-SUFFIX` 让流量默认走`全球直连`，但每次更新订阅后都需要手动改下配置文件，很不方便

**Comment by Karmylr** [comment]
第一个verify你是怎么好意思勾选的

**Comment by kadaliao** [comment]
> ### verify
> * [x]  我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
> * [x]  我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
> * [x]  我已经尝试自行解决，确认自己没有能力解决
> 
> ### 功能描述
> 对于clash，如何添加自定义的`DOMAIN-SUFFIX`? 当前我有一些域名，走的是漏网之鱼，我想改下配置文件，增加一个`DOMAIN-SUFFIX` 让流量默认走`全球直连`，但每次更新订阅后都需要手动改下配置文件，很不方便
> 
> ### 可能的解决方案
> _No response_

刚接触项目，也是看不太明白，请问在哪里修改的？

**Comment by beacon007** [comment]
> > ### verify
> > 
> > * [x]   我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
> > * [x]   我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
> > * [x]   我已经尝试自行解决，确认自己没有能力解决
> > 
> > ### 功能描述
> > 对于clash，如何添加自定义的`DOMAIN-SUFFIX`? 当前我有一些域名，走的是漏网之鱼，我想改下配置文件，增加一个`DOMAIN-SUFFIX` 让流量默认走`全球直连`，但每次更新订阅后都需要手动改下配置文件，很不方便
> > ### 可能的解决方案
> > _No response_
> 
> 刚接触项目，也是看不太明白，请问在哪里修改的？

我这里也是提供一种可能的方案：在你的`pref.toml`里增加一个`[[rulesets]]`,如下所示

```
[[rulesets]]
group = "🎯 全球直连"
ruleset = "snippets/my_custom_rule.txt"
type = "clash-domain"

[[rulesets]]
import = "snippets/rulesets.toml"
```

然后`my_custom_rule.txt`中内容如下：
```
DOMAIN-SUFFIX,xxx.com
```
其中第二个`[[rulesets]]`是配置文件中默认的，一定要加在默认的`[[rulesets]]`上面，这样转换后的clash中的规则也是在最上面，从而可以覆盖自带的rules
