### ISSUE TITLE
请问怎么运行，文档堵了半天也没有只说了运行之后的事

### ISSUE THREAD

**Issue by Kiswelrg** [tindy2013/subconverter#584]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

请问怎么运行，文档堵了半天也没有只说了运行之后的事，小白，看不懂下载releases之后的项目如何运行，求大佬帮助

**Comment by sgon00** [comment]
T_T 没有回复，直接就关了？可能是非常牛的产品，但是文档是我见过最差的。可以说是没有开头，没有结尾。如何安装？如何运行？怎么使用？什么功能？全部都没有。一上来就给你个本地链接，一顿解释，不知道在说什么。

**Comment by Kiswelrg** [comment]
> T_T 没有回复，直接就关了？可能是非常牛的产品，但是文档是我见过最差的。可以说是没有开头，没有结尾。如何安装？如何运行？怎么使用？什么功能？全部都没有。一上来就给你个本地链接，一顿解释，不知道在说什么。

试试他给的几个example然后问问ai，这个文档就是比较简陋，当时花了点时间解决了之后就没管了忘了

**Comment by sgon00** [comment]
> > T_T 没有回复，直接就关了？可能是非常牛的产品，但是文档是我见过最差的。可以说是没有开头，没有结尾。如何安装？如何运行？怎么使用？什么功能？全部都没有。一上来就给你个本地链接，一顿解释，不知道在说什么。
> 
> 试试他给的几个example然后问问ai，这个文档就是比较简陋，当时花了点时间解决了之后就没管了忘了

真没想到，2023年初您提的问题，现在能迅速回复，非常感谢。我现在找到几个替代软件，正在尝试。就是要把机场订阅生成多个v2ray.json配置文件，可以在linux下搭配ss-tproxy使用。我问了ai，SubConverter命令行应该可以解决问题，但文档烂成这样，不到万不得已，还是先不用了。再次感谢您回复。
