### ISSUE TITLE
不支持经过base64加密的ssr或ssd……订阅链接

### ISSUE THREAD

**Issue by Liquor030** [tindy2013/subconverter#59]
在base64加密后的ssr订阅会显示“ The following link doesn't contain any valid node info”

**Comment by CareyWang** [comment]
@Liquor030 那就不加密呗

**Comment by Liquor030** [comment]
@CareyWang 但是。机场给的订阅链接是加密的。ssd也一样 TAT

**Comment by CareyWang** [comment]
@Liquor030 https://sub-web.netlify.com 请

**Comment by Liquor030** [comment]
@CareyWang 不行呀。还是显示“ The following link doesn't contain any valid node info”

**Comment by tufu9441** [comment]
> @Liquor030 https://sub-web.netlify.com 请

这个网站很好用，我的机场提供的订阅链接用[https://bianyuan.xyz](https://bianyuan.xyz)和[https://gfwsb.114514.best](https://gfwsb.114514.best)都无法转换出QX能用的node-list，但在您提供的这里成功了，我看也是基于subconverter的后端，不知有什么不同。
