### ISSUE TITLE
[Feature] 启用缓存时，在缓存到期前自动刷新缓存

### ISSUE THREAD

**Issue by devioa** [tindy2013/subconverter#592]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

目前缓存到期后需要收到新请求才会刷新
这导致命中过期缓存的转换请求响应会非常慢
可否实现在缓存到期前自动刷新缓存？

**Comment by ableding** [comment]
maybe you can just make pure proxies list then url circular reference.
