### ISSUE TITLE
[Feature] 能否增加标识节点是哪个机场来的？

### ISSUE THREAD

**Issue by grayguest** [tindy2013/subconverter#595]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

## 问题
最近使用的2个机场，其中1个机场更名后，和另外一个机场的节点名称很相似，想区别开以快速定位到是哪个机场的问题，同时显示更清晰。

## 目前 subconverter 的行为
rename_node功能好像没有办法直接做，如果用js脚本，传参是node，没办法获取到机场名吧？

## 其他疑惑
- js脚本传参的node里面没有节点名称吗？看文档只有Hostname Port 等等，https://github.com/netchx/netch/blob/268bdb7730999daf9f27b4a81cfed5c36366d1ce/GSF.md
- 如何调试js脚本呢，看日志？把subconverter弄成了cmdline下的systemd服务，没找到相关日志，怎么知道传参的node包括的所有属性，怎么调试这一块儿呢？

### 可能的解决方案

- 一种是直接
- 另外一种是js脚本方案，不知道怎么调试和能否实现，希望能指教一下怎么调试这块，谢谢博主。

**Comment by xingmiye** [comment]
要不。。。尝试一下自定义分组，然后按照机场订阅地址来分组
custom_proxy_group=g1`select`!!GROUPID=0`!!INSERT=0
; 指订阅链接中的第一条订阅以及配置文件中 insert_url 中的第一条节点
custom_proxy_group=g2`select`!!GROUPID=1
; 指订阅链接中的第二条订阅
custom_proxy_group=g2`select`!!GROUPID=!2
; 指除了订阅链接中的第三条订阅
custom_proxy_group=g2`select`!!GROUPID=3-5
; 指订阅链接中的第四条到第六条订阅

**Comment by grayguest** [comment]
> 要不。。。尝试一下自定义分组，然后按照机场订阅地址来分组
> 
> ```
> custom_proxy_group=g1`select`!!GROUPID=0`!!INSERT=0
> ; 指订阅链接中的第一条订阅以及配置文件中 insert_url 中的第一条节点
> custom_proxy_group=g2`select`!!GROUPID=1
> ; 指订阅链接中的第二条订阅
> custom_proxy_group=g2`select`!!GROUPID=!2
> ; 指除了订阅链接中的第三条订阅
> custom_proxy_group=g2`select`!!GROUPID=3-5
> ; 指订阅链接中的第四条到第六条订阅
> ```

感谢，是一个折衷的方案，话说老哥知道怎么调试js脚本吗，node属性里面没有节点名称的吗？https://github.com/netchx/netch/blob/268bdb7730999daf9f27b4a81cfed5c36366d1ce/GSF.md

**Comment by jingzhongchangan** [comment]
+1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称

**Comment by Lucio-0408** [comment]
> +1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称

url=tag:ABC,https……
外部配置文件:
rename=!!GROUP=ABC!!^@XXX
重命名后的节点名:
XXX节点名

**Comment by jingzhongchangan** [comment]
> 

感谢大佬，目前这个用法能修改一条订阅规则，rename支持多个规则么？我试了两个rename参数，或者两条规则用逗号，|，或者数组都不行

**Comment by jingzhongchangan** [comment]
> > +1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称
> 
> url=tag:ABC,https…… 外部配置文件: rename=!!GROUP=ABC!!^@某某云 重命名后的节点名: 某某云节点名

感谢大佬，这样能匹配一条规则，rename支持多条规则么？比如 !!GROUP=ABC!!^@ABC, !!GROUP=DEF!!^@DEF，我试了两个rename参数，逗号，|符号，或者数组都不行

**Comment by AkariiinMKII** [comment]
> > > +1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称
> > 
> > url=tag:ABC,https…… 外部配置文件: rename=!!GROUP=ABC!!^@某某云 重命名后的节点名: 某某云节点名
> 
> 感谢大佬，这样能匹配一条规则，rename支持多条规则么？比如 !!GROUP=ABC!!^@ABC, !!GROUP=DEF!!^@DEF，我试了两个rename参数，逗号，|符号，或者数组都不行

多条规则之间用`隔开

**Comment by jingzhongchangan** [comment]
> > > > +1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称
> > > 
> > > 
> > > url=tag:ABC,https…… 外部配置文件: rename=!!GROUP=ABC!!^@某某云 重命名后的节点名: 某某云节点名
> > 
> > 
> > 感谢大佬，这样能匹配一条规则，rename支持多条规则么？比如 !!GROUP=ABC!!^@abc, !!GROUP=DEF!!^@def，我试了两个rename参数，逗号，|符号，或者数组都不行
> 
> subcon URL中多条规则之间用`隔开

没太理解，我目前结构是 url=tag:1,http...|tag:2,http...&rename=!!GROUP=1!!^@1，不知道怎么添加第二条的rename规则，是需要 url=tag:1,http...|tag:2,http...&rename=!!GROUP=1!!^@1`!!GROUP=2!!^@2，这样么？

**Comment by yongman** [comment]
> 要不。。。尝试一下自定义分组，然后按照机场订阅地址来分组
> 
> ```
> custom_proxy_group=g1`select`!!GROUPID=0`!!INSERT=0
> ; 指订阅链接中的第一条订阅以及配置文件中 insert_url 中的第一条节点
> custom_proxy_group=g2`select`!!GROUPID=1
> ; 指订阅链接中的第二条订阅
> custom_proxy_group=g2`select`!!GROUPID=!2
> ; 指除了订阅链接中的第三条订阅
> custom_proxy_group=g2`select`!!GROUPID=3-5
> ; 指订阅链接中的第四条到第六条订阅
> ```

求问下 toml 配置文件格式中 rule 如何定义？

**Comment by kenwestern** [comment]
> > +1，我也是类似的问题，同时多条订阅线路，想在节点名称加一些自定义的前缀后缀，用来区分机场，不知道怎么获取机场名称
> 
> url=tag:ABC,https…… 外部配置文件: rename=!!GROUP=ABC!!^@某某云 重命名后的节点名: 某某云节点名

大佬，请问toml配置文件中，如何写才能让把tag加到节点名前面？
toml格式中给出的跟rename相关示例是这样的，不像是能添加前缀的

[[node_pref.rename_node]]
match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?'
replace = "$1x"

**Comment by Wrandz** [comment]
借楼请教一下各位大佬，replace = "$1x"，这个起到什么作用？
比如我的节点名是，香港1A-x1.0，我将这里的配置随便改了一下(由于不太清楚replace的作用，所以随便试了一下)
```
[[node_pref.rename_node]]
match = '\((x|X)?(\d+(\.\d+)?)((\s?倍率?)|(x|X))?\)?'
replace = "$1x[Rate]"
```
结果发现没什么作用，节点名还是一样没变。

**Comment by Wrandz** [comment]
我将配置改为
```

[[node_pref.rename_node]]
match = '香港1A-x1.0'
replace = "$1x"
```
节点名变成了一个字母，x，不知道$1在其中起到什么作用。
