### ISSUE TITLE
[BUG] 转换 Surge 节点配置到 Clash 时会输出 Clash 不支持的 Snell v4 节点

### ISSUE THREAD

**Issue by ZeroClover** [tindy2013/subconverter#616]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

Surge 到 Clash

### 转换设置

默认配置文件

### 复现步骤

将包含 Snell v4 节点的 Surge 配置文件转换为 Clash Node List

例如：

```
🇭🇰 HK Shadowsocks = ss, hk.example.com, 1919, encrypt-method=aes-256-gcm, password=114514, udp-relay=true
🇭🇰 HK Snell = snell, hk.example.com, 810, psk=114514, version=4
```

### 期望结果

不输出包含 Snell v4 的节点

### 实际结果

输出的 Clash Node List 仍然包含 Snell v4 节点，然而 Clash 目前并不支持 Snell v4

```
proxies:
  - {name: 🇭🇰 HK Shadowsocks, server: hk.example.com, port: 1919, type: ss, cipher: aes-256-gcm, password: 114514, udp: true}
  - {name: 🇭🇰 HK Snell, server: hk.example.com, port: 810, type: snell, psk: 114514, version: 4, udp: true}
```

**Comment by tindy2013** [comment]
Fixed in commit deb73c56694a1d6eaf6fa27a4569aed4be941367
