### ISSUE TITLE
[Feature] <建议增加自定义请求头的功能>

### ISSUE THREAD

**Issue by youshandefeiyang** [tindy2013/subconverter#621]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

现在一些机场设置了禁止订阅转换，我现在是自己写了一个专门拉订阅的中间代理后端，然后拉到订阅后交给SubConverter处理，大概是验证Refer和UA同时限制了IP区域，请求头这块Subconverter写死了，可以搞个自定义请求头之类的，说实话不太清楚不让使用订阅转换是为了啥，如果是为了防止被D那作用不是很大，直接Nginx做个针对参数域名请求拦截，用第三方工具请求获取到订阅后再转发给Subconverter最后返回处理的内容，好像也防不住个啥，不过还是希望Subconverter可以支持一下自定义请求头

**Comment by AirportR** [comment]
> ### verify
> * [x]  我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
> * [x]  我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
> * [x]  我已经尝试自行解决，确认自己没有能力解决
> 
> ### 功能描述
> 现在一些机场设置了禁止订阅转换，我现在是自己写了一个专门拉订阅的中间代理后端，然后拉到订阅后交给SubConverter处理，大概是验证Refer和UA同时限制了IP区域，请求头这块Subconverter写死了，可以搞个自定义请求头之类的，说实话不太清楚不让使用订阅转换是为了啥，如果是为了防止被D那作用不是很大，直接Nginx做个针对参数域名请求拦截，用第三方工具请求获取到订阅后再转发给Subconverter最后返回处理的内容，好像也防不住个啥，不过还是希望Subconverter可以支持一下自定义请求头
> 
> ### 可能的解决方案
> _No response_

因为有一些小道消息说是subconverter存在安全漏洞（未证实，请勿相信），为防范订阅泄露，故一些机场会禁止使用公开的订阅转换。

**Comment by tindy2013** [comment]
什么安全漏洞？本来转换的 log 就会有用户订阅链接内容相关的信息，总不能说访问 log 也是安全漏洞吧？

**Comment by AirportR** [comment]
个人认为并没有安全漏洞，这种说法仅仅来源于小道说法，在没有更确切的消息之前，我更相信是第三方平台是不受信任的，第三方订阅转换本就需要自行承担订阅泄露风险。从机场方面上说，用户自发的外泄行为显然是需要防范的，这可能出于责任心的目的？通过请求头识别，设置白名单一定程度上防止用户的订阅外泄，我想这是它禁止订阅转换的原因之一。

**Comment by klgd** [comment]
希望能够处理一下 我现在用的一个已经不能用subconverter转换了
