### ISSUE TITLE
[BUG] 在使用toml作为配置文件的时候无法使用tasks任务

### ISSUE THREAD

**Issue by Sndav** [tindy2013/subconverter#629]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

lastest

### 转换过程

无

### 转换设置

无

### 复现步骤

在使用toml作为配置文件的时候无法使用tasks任务，具体原因是在解析完toml文件的tasks后忘记refresh_schedule()了

### 期望结果

在toml中也可以使用tasks任务

### 实际结果

在toml中也不可以使用tasks任务

**Comment by tindy2013** [comment]
Fixed in commit 3cb07c3
