### ISSUE TITLE
[BUG] surge config file cannot be parsed with a "=" in the key string (node names)

### ISSUE THREAD

**Issue by miyuanbo** [tindy2013/subconverter#630]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

clashx to surge

### 转换设置

BEFORE CONVERT (clashx format): 
the node name is "nodename(a=b)"

AFTER CONVERT (surge .conf format):
[Proxy]
DIRECT = direct
nodename(a=b) = valuestring

### 复现步骤

When the keystring (ex. the name of the nodes of clashx) contains an "=", then the config files would not be parsed correctly. 

### 期望结果

The converter can identify "="s in the node names and replace them with "-"s or something else, so that the converted surge .conf files will not contain "="s. 

### 实际结果

Currently the converter cannot avoid "="s in the key strings in surge .conf files, and surge is not able to parse the .conf files.

**Comment by miyuanbo** [comment]
简而言之，就是当节点名称中含有等号（我的clashx订阅中就是这种情况）时，转化为surge的conf文件后，其一行中将会出现两个或多个等号，此时surge无法正常解析文件。
建议是在转换为surge的配置文件前，检查替换节点名称中的等号，并替换为“-”或其他符号。

**Comment by miyuanbo** [comment]
已创建pr，将替换等号的代码加入到 /src/generator/config/subexport.cpp 文件的 processRemark 函数中.

**Comment by tindy2013** [comment]
已合并
