### ISSUE TITLE
希望建个群或者TG组，请大佬坐镇，有的看不懂得向大佬请教！

### ISSUE THREAD

**Issue by yjiawqgj** [tindy2013/subconverter#633]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

希望开个交流学习群组，有很多看不懂想学习！

**Comment by moshaoli688** [comment]
当然不介意可以到我的TG群里唠唠嗑 @FFQGroup

**Comment by yjiawqgj** [comment]
> @FFQGroup

只要有人教，哪都行！

**Comment by moshaoli688** [comment]
有问题我看到了，只要能解决就会回答的

yjiawqgj ***@***.***> 于2023年9月5日周二 22:05写道：

**Comment by tindy2013** [comment]
@subconverter_discuss
