### ISSUE TITLE
[Feature] custom_proxy_group可以使用proxy_group定义的代理吗

### ISSUE THREAD

**Issue by plum9696** [tindy2013/subconverter#636]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

就是我定义了一个custom_proxy_group    proxy_group1,我在第二个custom_proxy_group想用到定义的proxy_group1

**Comment by gang4399** [comment]
示例的远程引用ini文件里不就有套壳代理组吗？

**Comment by plum9696** [comment]
> 示例的远程引用ini文件里不就有套壳代理组吗？

我是想这样设置,已经创建了自动选择这个组,然后在创建手动选择的时候,把所有节点和自动选择加起来
```
;custom_proxy_group=手动选择`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`60,,100
```

**Comment by AkariiinMKII** [comment]
```
custom_proxy_group=手动选择`select`[]自动选择`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`60,,100
```

**Comment by plum9696** [comment]
> ```
> custom_proxy_group=手动选择`select`[]自动选择`.*
> custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`60,,100
> ```
