### ISSUE TITLE
[Feature] 新版本发布release

### ISSUE THREAD

**Issue by libli** [tindy2013/subconverter#638]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

为什么现在新的版本都不发布release了，只发布docker版本？
因为我的软路由无法安装docker,需要安装release版本。

**Comment by hm-Private** [comment]
> 去actions下载
> 
> https://github.com/tindy2013/subconverter/actions/workflows/build.yml

怎么下载

**Comment by hm-Private** [comment]
> @hm-Private 
> 
> 找绿色的✓
> 
> 点进去滑到最底下就有二进制软件了

截图下呗，大佬

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/releases/tag/v0.8.0
