### ISSUE TITLE
Could you let External Configuration File support exclude_remarks or include_remarks?

### ISSUE THREAD

**Issue by Marukon** [tindy2013/subconverter#64]
In pref.ini, there are some lines that not supported in External Configuration File:

> ;Exclude nodes which remarks match the following patterns. Supports regular expression.
exclude_remarks=(到期|剩余流量|时间|官网|产品)
;exclude_remarks=(other rule)

> ;Only include nodes which remarks match the following patterns. Supports regular expression.
;include_remarks=V3.*港

It is seems that all possible customization settings has been shown in this file:
[https://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.ini](https://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.ini) However, it is not include the lines mentioned above.

Although we can use include or exclude Argument in the link, I think it is not convenience. If this can be supported in External Configuration File, it may be better than before.

Thank you for your great work.

**Comment by tindy2013** [comment]
@Marukon This should be added in the next version.

**Comment by Marukon** [comment]
> @Marukon This should be added in the next version.

Thank you.
