### ISSUE TITLE
[BUG] 转换为quanx配置时，规则被写成了远程分流，并且服务器地址为127.0.0.1

### ISSUE THREAD

**Issue by AdoShan** [tindy2013/subconverter#642]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.8.0

### 转换过程

clash转为quanx

### 转换设置

https://github.com/AdoShan/Shan/raw/master/SubconverterExample/yueyi

### 复现步骤

前往圈X中下载配置。链接为：`http://192.168.2.101:25500/sub?target=quanx&url=机场订阅url&add_emoji=true&config=https%3A%2F%2Fgithub.com%2FAdoShan%2FShan%2Fraw%2Fmaster%2FSubconverterExample%2Fyueyi&filename=YueYi&interval=86400`

### 期望结果

可以将规则直接写入本地分流`filter_local`或者直接使用外部配置里面的远程链接

### 实际结果

不管是否添加`expand=false`参数，最终生成的配置文件全部为`filter_remote`且订阅地址均为`https://127.0.0.1:25500`开头，无法更新分流

**Comment by AdoShan** [comment]
可通过[此方法](https://github.com/tindy2013/subconverter/issues/588)暂时解决

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 [managed-config] 部分
