### ISSUE TITLE
能否添加一个默认在线地址配置?

### ISSUE THREAD

**Issue by hudingwen** [tindy2013/subconverter#650]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

想修改下面配置文件
src/handler/settings.h
**原来**
struct Settings
{
    //common settings
    std::string prefPath = "pref.ini", defaultExtConfig;
    string_array excludeRemarks, includeRemarks;
    RulesetConfigs customRulesets;
    RegexMatchConfigs streamNodeRules, timeNodeRules;

**希望能实现如下效果,在生成订阅链接时不用手动附加在线规则,以便在服务端进行管理**
struct Settings
{
    //common settings
    std::string prefPath = "pref.ini", defaultExtConfig = **"https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini";**
    string_array excludeRemarks, includeRemarks;
    RulesetConfigs customRulesets;
    RegexMatchConfigs streamNodeRules, timeNodeRules;

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L40

**Comment by hudingwen** [comment]
docker run -d --restart=always -p 25501:25500 -v /root/pref.toml:/base/pref.toml  --name test tindy2013/subconverter:latest

pref.toml这样不起作用
只改了下面这个
default_external_config = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"

**Comment by hudingwen** [comment]
三个我都改了一遍
#default_external_config = "https://raw.githubusercontent.com/hudingwen/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"

# The file scope limit of the 'rule_base' options in external configs.
base_path = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"

# Clash config base used by the generator, supports local files/URL
clash_rule_base = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini"

**Comment by hudingwen** [comment]
是还没实现么?

**Comment by hudingwen** [comment]
好了 不过还是感谢...
