### ISSUE TITLE
[Feature] <title>把大象装冰箱里 不是 win端纯本地的默认双击EXE里增加一个DMM的分组 总共分几步骤

### ISSUE THREAD

**Issue by lhj5426** [tindy2013/subconverter#651]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

我想在这个 双击打开的EXE 里增加一个DMM 分组
![image](https://github.com/tindy2013/subconverter/assets/30548000/861db4f7-c331-48f5-a43c-8fbf017e938b)
我看了 文档 感觉在看天书
完全看不懂 
能不 能 通俗一点 
第一步 把冰箱门打开 
第二步 把大象装冰箱里
第三步 把冰箱门带上

这样通俗一点的 

我现在 是 没办法只能
![image](https://github.com/tindy2013/subconverter/assets/30548000/64eebc4b-4a59-445e-87eb-04a2ac2e7e02)
每次更新订阅之后

![image](https://github.com/tindy2013/subconverter/assets/30548000/e44f9e3d-c933-4530-bde0-d47e402d29ba)
 手动编辑 配置文件来添加 
   - DOMAIN-SUFFIX,dmm.co.jp,🍎 苹果服务
  - DOMAIN-SUFFIX,dmm.com,🍎 苹果服务
  DMM的2条规则
  重复次数多了 我实在也是烦了 每天更新订阅 每天改
  
  这个文档对我实在是没有任何的帮助 所以 真新请问一下 
  到底要怎么自己添加 本地EXE里的分组 或者 怎么把 这2条 添加到 本地exe 里
  每次双击打开 就包含这2条规则 不需要 我每次更新订阅之后手动添加

### 可能的解决方案

请教教我 简单的三部曲
编辑本地文件夹里的哪 复制到哪然后保存 双击EXE 享受规则

**Comment by lhj5426** [comment]
拜托了 我是真的不会 也看不懂 真想求求谁能教教我  在此感谢了

**Comment by HaneRo** [comment]
参照rules文件夹里的文件写一个包含DMM网址的分流，参照config文件夹中的非在线规则添加你写的分流及分组，把订阅链接中的config改为 config=config%2F你的规则名称.ini
