### ISSUE TITLE
[BUG] 丢失config

### ISSUE THREAD

**Issue by s0w0h** [tindy2013/subconverter#653]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

tindy2013/subconverter:latest

### 转换过程

自建配置文件问题

### 转换设置

https://raw.githubusercontent.com/s0w0h/clash-rule/main/clash-rule.ini

### 复现步骤

使用docker自建后端、肥羊增强后端（api.v1.mk/sub?）无法使用，会调用默认配置，但是使用品云后端（sub.id9.cc/sub?、v.id9.cc/sub?）可以正常解析。
经过测试，注释掉下面这行可以正常解析
ruleset=🤖 GLM,https://raw.githubusercontent.com/s0w0h/clash-rule/main/rules/Glmai.list
该文件为：
```shell
DOMAIN-KEYWORD,bing
DOMAIN-KEYWORD,copilot
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,pi.ai
DOMAIN-SUFFIX,sentry.io
DOMAIN-SUFFIX,bard.google.com
```

### 期望结果

![image](https://github.com/tindy2013/subconverter/assets/87455543/51c0cffc-414d-47ef-aa44-2509d0b95952)

### 实际结果

![image](https://github.com/tindy2013/subconverter/assets/87455543/0edf774d-6295-4fc7-80d4-933640f5f363)

**Comment by AkariiinMKII** [comment]
@s0w0h 有在线ruleset fetch失败了 建议看log

**Comment by s0w0h** [comment]
> @s0w0h 有在线ruleset fetch失败了 建议看log

我查看了日志，发现可能问题出在Ruleset count in external config has exceeded limit.请问下这个限制可以取消吗

**Comment by AkariiinMKII** [comment]
@s0w0h 修改 https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L313

**Comment by AdoShan** [comment]
> @s0w0h 修改 https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L313

我现在也遇到了这个问题，我知道了，修改max_allowed_rulesets参数的值。
