### ISSUE TITLE
[BUG] <新版本docker安装匹配架构不对>

### ISSUE THREAD

**Issue by adeya520** [tindy2013/subconverter#662]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

	tindy2013/subconverter@sha256:5c16326c7159055cc40f9118bf0591e99332c830b9b5d42b3ffcd1dbdfb431d6

### 转换过程

docker安装过程

### 转换设置

未到转换环节

### 复现步骤

提示如下错误：WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### 期望结果

rt

### 实际结果

exec /bin/sh: exec format error

**Comment by adeya520** [comment]
最新镜像暂时只支持386，先用以前版本吧

**Comment by tindy2013** [comment]
打包机问题 已解决

**Comment by adeya520** [comment]
> 打包机问题 已解决

大佬，有两个问题咨询，
1、有多个机场，怎么实现不同机场的节点设立对应策略组，这样可以在针对不同场景使用不同机场。
2、我想到的办法是用js函数筛选节点，建立不同的策略组，但是，有个很小白的问题，我找不到docker安装SubConverter，挂载目录里边没有东西，也找不到容器根路径了，没法修改pref文件。。。
以下是我安装容器的命令：
docker run -itd --restart=always --name=SubConverter --net=bridge -p 2556:25500 -v /root/docker/SubConverter:/mnt tindy2013/subconverter

**Comment by adeya520** [comment]
> 打包机问题 已解决

大佬，docker安装的根文件路径在哪啊，以下为我的docker安装命令：
docker run -itd --restart=always --name=SubConverter --net=bridge -p 2556:25500 -v /root/docker/SubConverter:/mnt tindy2013/subconverter
我在主机对应挂载目录没找到，里边是空的。找到了根路径/var/lib/docker/overlay2/4d7ac3f28767a855d2a038b28eef6bf383e00c3bcc28f5e02a950b9233216be9/merged，里边也没有pref文件啊，是哪里不对吗？
麻烦了

**Comment by NZESupB** [comment]
:/base/pref.toml

**Comment by adeya520** [comment]
> :/base/pref.toml

我挂载就是这么写的啊
