### ISSUE TITLE
[BUG] Surge 的 DOMAIN-SET 生成问题

### ISSUE THREAD

**Issue by rule-airport** [tindy2013/subconverter#667]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.8.1-885a63b backend

### 转换过程

将规则文件转换为 Surge DOMAIN-SET

### 转换设置

getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2JsYWNrbWF0cml4Ny9pb3NfcnVsZV9zY3JpcHQvbWFzdGVyL3J1bGUvQ2xhc2gvQWR2ZXJ0aXNpbmdMaXRlL0FkdmVydGlzaW5nTGl0ZS5saXN0

### 复现步骤

[DOMAIN-SET：专为大量域名集列表文件设计，支持上万条记录的快速查询。文件中每行为一个域名，如果某行以 . 开头则表示匹配所有子域名和该域名本身。可用于广告过滤。](https://manual.nssurge.com/book/understanding-surge/cn/#%E8%A7%84%E5%88%99)

由官方文件可知，当规则是 DOMAIN-SUFFIX 的时候，应该以 . 开头；那么当规则是 DOMAIN 的时候，才是直接以域名开头。

定位代码：

https://raw.githubusercontent.com/tindy2013/subconverter/885a63b83778fbcf85765d10ec94ea06b9ca72da/src/handler/interfaces.cpp 的 242 行至249行，修改一下即可。

case 5:
            if(!startsWith(strLine, "DOMAIN-SUFFIX,") && !startsWith(strLine, "DOMAIN,"))
                continue;
            if(filterLine())
                continue;
            output_content += strLine.substr(posb, pose);
            output_content += '\n';
            continue;

以个人的代码水平修改如下：

case 5:
            if(!startsWith(strLine, "DOMAIN-SUFFIX,") && !startsWith(strLine, "DOMAIN,"))
                continue;
            if(filterLine())
                continue;
            if(strLine[posb - 2] == 'X')
                output_content += ".";
            output_content += strLine.substr(posb, pose);
            output_content += "'\n";
            continue;

### 期望结果

当规则是 DOMAIN-SUFFIX 的时候，应该以 . 开头；那么当规则是 DOMAIN 的时候，以域名开头

### 实际结果

不论是 DOMAIN-SUFFIX 还是 DOMAIN，转换后的规则都是以域名开头。

**Comment by tindy2013** [comment]
Fixed in [05a542c](https://github.com/tindy2013/subconverter/commit/05a542c4f1730f4c84526b0c95d3cca388fd276e)
