### ISSUE TITLE
[BUG] sing-box 不支持 simple-obfs，建议增加功能将其重命名为 obfs-local，正如在 clash 中统一重命名为 obfs 那样

### ISSUE THREAD

**Issue by aur3l14no** [tindy2013/subconverter#671]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.8.1-c578ea6 backend

### 转换过程

shadowsocks sip002 转换为 singbox

### 转换设置

默认

### 复现步骤

转换包含该节点的订阅

ss://zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz@lol.fc-xxx.xyz:10001/?plugin=simple-obfs%3Bobfs%3Dhttp%3Bobfs-host%3D5491deeb4b.douyincdn.com#NODE

### 期望结果

**把 simple-obfs 自动转换成 obfs-local**

### 实际结果

simple-obfs 输出为 simple-obfs

**Comment by tindy2013** [comment]
Fixed in 7968d54
