### ISSUE TITLE
[BUG] 开启 append_type，指定 target 为 quanx 的时候无效。

### ISSUE THREAD

**Issue by yunyouu** [tindy2013/subconverter#680]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.8.1-38fd0da

### 转换过程

本地 vmess url 转换为 loon 订阅地址

### 转换设置

target=quanx
url=<vmess 配置>
emoji=true
add_emoji=true
append_type=true
tfo=true
udp=false
sort=true
scv=false
classic=true

### 复现步骤

直接指定 profile 文件进行转换

### 期望结果

所有 target 行为一致

### 实际结果

全面有个空的括号，其他 target 是正常的
<img width="241" alt="image" src="https://github.com/tindy2013/subconverter/assets/32095100/e77f6b17-b1ab-49cf-881e-c26cc7b5907e">
<img width="136" alt="image" src="https://github.com/tindy2013/subconverter/assets/32095100/39ee875b-e466-4bd3-bdc3-fb9bcac4cd0f">

### 错误信息

```shell
没有错误信息
```

**Comment by tindy2013** [comment]
Fixed in d9ff111
