### ISSUE TITLE
[BUG] url parameter lost when using alias

### ISSUE THREAD

**Issue by lr7skquo** [tindy2013/subconverter#681]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.8.1-d9ff111 backend

### 转换过程

ssr subscription link to clash

### 转换设置

[[aliases]]
uri = "/myairport"
target = "/getprofile?name=profiles/my_airport.ini"

### 复现步骤

1. pull and run the docker
2. access "http://docker_address:25500/myairport?token=12345"
3. the webpage was redirected to "http://docker_address:25500/getprofile?name=profiles/my_airport.ini"

### 期望结果

the webpage should be redirected to "http://docker_address:25500/getprofile?name=profiles/my_airport.ini&token=12345"

### 实际结果

the webpage was redirected to "http://docker_address:25500/getprofile?name=profiles/my_airport.ini"

**Comment by tindy2013** [comment]
Fixed in [2f820b8](https://github.com/tindy2013/subconverter/commit/2f820b81c424273547a35edb066bb163120ebafe)
