### ISSUE TITLE
[BUG] domain_suffix转出到singbox匹配不正确

### ISSUE THREAD

**Issue by AoEiuV020** [tindy2013/subconverter#684]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [x] 我已经确认之前没有issue涉及此BUG

### subconverter版本

master

### 转换过程

clash转换为singbox

### 转换设置

https://github.com/AoEiuV020/SubConfig/raw/main/subconverter.ini

### 复现步骤

转换成singbox配置，
开启singbox规则代理，
访问代理正常，
访问google.com匹配到规则domain_suffix le.com 走了直连导致连接失败，

我在singbox那边确认过了，他们的domain_suffix语义和这边不同且没有计划修改，
这边的 DOMAIN-SUFFIX,le.com 应该转成那边的两条规则，
`{
  "domain": "le.com",
  "domain_suffix": ".le.com"
}`
https://github.com/SagerNet/sing-box/issues/1189

### 期望结果

访问google.com走代理，

### 实际结果

访问google.com连接失败，

**Comment by deuteros-gex** [comment]
最新进展：
这个行为未来会改，不过得等1.9.0了
https://github.com/SagerNet/sing-box/commit/f91a90cad8bc331f9ad7c943dd083c77c3ebfc7f

**Comment by AoEiuV020** [comment]
很好，那这边就不需要改了，
还是统一的好，
singbox除了等正式版也有actions自动编译的可以先试试，
如果没什么问题这个issue就可以直接关闭了，

**Comment by AoEiuV020** [comment]
本来想去singbox那边最早的issue提一下这个进展，没想到那边已经超时禁止评论了，
没法通知当时关注这个问题的人了，
