### ISSUE TITLE
[Feature] <建议增加『针对加密方法进行过滤/exclude』的选项>

### ISSUE THREAD

**Issue by jacobin** [tindy2013/subconverter#686]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述
现下，subconverter的呼叫参数exclude是针对着属性name而进行的。
但是，可能是出于技术覆盖不够，有的客户端譬如clash-meta不支持加密方法**_[chacha20-poly1305](https://wuxuejun2018.github.io/2019/04/25/ChaCha20-Poly1305/)_**，从而导致对整个yaml的检验失败。

在yaml中，有关部分内容如下：

> proxies:
>   - {name: github.com/freefq - 福建省厦门市金桥网络通信有限公司 1, server: 175.178.55.243, port: 33963, type: ss, cipher: chacha20-poly1305, password: MxZuOpppbY, udp: true}

一般意义上，傻憨保守的客户端须要规避或者不会使用这种有不明飞行物技术的节点。

我把**Openclash**日志粘贴如下：

> 2023-12-10 00:24:59 错误：配置文件测试失败，请查看《**_内核日志_**》排查失败原因！
> 2023-12-10 00:24:59 配置文件【/etc/openclash/config/xxxxx.yaml】测试失败...
> 2023-12-10 00:24:58 配置文件下载成功，使用内核测试是否有错误...
> 2023-12-10 00:24:56 提示：检测到 Dnsmasq 正常工作，还原防火墙 DNS 劫持规则...
> 2023-12-10 00:24:56 开始更新配置文件【xxxxx】...

**clash**的《**_内核日志_**》

> [ERRO][2023-12-09T23:59:29.132786284+08:00] proxy 880: ss 172.252.59.67:42572 initialize error: **_unknown method_**: **_chacha20-poly1305_** 
> [INFO][2023-12-09T23:59:29.040051005+08:00] Start initial configuration in progress

**Comment by wongz** [comment]
+1，现有版本不知道通过自定义能不能实现

**Comment by jacobin** [comment]
这个话题扯到了加密领域的问题，具体就是堆成加密方法chacha20-poly1305。我注意到了clash支持ChaCha20-IETF-Poly1305，它是更高级的chacha20-poly1305。对chacha20-poly1305的抛弃，也许是出于安全强度的担忧。
以上想法，是我发现clash-meta不屌chacha20-poly1305之后的第一个想法。而后，我发现chacha20-poly1305其实是比AES_**[更新的推出时间更短](https://wuxuejun2018.github.io/2019/04/25/ChaCha20-Poly1305/)**_的加密算法。真实的情况应该是，自从google放出chacha20-poly1305之后直至今天，chacha20-poly1305处于快速迭代升级的练功时期，强身健体之后，修正主义变苏修，把自己革了老命了。相对于AES的3-4倍的速度优势，变成了30%的聊胜于无 。
关于chacha20-poly1305及其儿孙们的简单比较在[这里](https://crypto.stackexchange.com/questions/73220/which-version-of-chacha-is-more-secure)，其中说到“XChaCha20-Poly1305-IETF is very likely to become the function used by the high-level API in a future libsodium release. Which means that other variants will not be available any longer in **_minimal builds_**.” 
XChaCha20-Poly1305-IETF 很可能成为未来 libsodium 版本中高级 API 使用的函数。 这意味着其他变体在**_最小构建_**中将不再可用

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L25-L37

**Comment by jacobin** [comment]
如附件文件，重点关注其中有关filter_script的内容
[Uploading subconverter_README-cn.md at master · tindy2013_subconverter.pdf…]()

**Comment by jacobin** [comment]
如附件文件，重点关注其中有关filter_script的内容

[Uploading subconverter_README-cn.md at master · tindy2013_subconverter.pdf…]()
