### ISSUE TITLE
[建议] 增加港、台媒体分组

### ISSUE THREAD

**Issue by Comah** [tindy2013/subconverter#69]
现在港台媒体默认走的是国外媒体分组  但是港台很多媒体 例如：TVB  动画疯 之类的都是需要本地原生IP才能收看的 。如果能多一个香港分组 就能把TVB 等一些本地媒体划分到原生线路去了。

**Comment by Y-SubWbe** [comment]
@Comah 可以下载本地后自行配置港澳台分组，并且港澳台分组在Rules文件夹也是存在的，直接调用即可
