### ISSUE TITLE
[BUG] 勾选Clash DOH后发现生成的订阅地址中没有DNS

### ISSUE THREAD

**Issue by Jacky-Bruse** [tindy2013/subconverter#696]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

最新

### 转换过程

v2ray转换为clash

### 转换设置

https://domain/sub?target=clash&new_name=true&url=http://localhost/path

### 复现步骤

https://domain/sub?target=clash&new_name=true&url=http://localhost/path

### 期望结果

勾选doh后在订阅地址中有doh dns，我修改后打包成docker还是没成功，麻烦指导，谢谢

### 实际结果

前端勾选doh,生成的链接中DNS没有变化

**Comment by hm-Private** [comment]
解决了嘛
