### ISSUE TITLE
[BUG] clash配置uuid对应filter_script中node的哪个字段

### ISSUE THREAD

**Issue by viocha** [tindy2013/subconverter#705]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.8.1

### 转换过程

clash转clash

### 转换设置

function filter(node) {
  if (node.EncryptMethod === "chacha20-poly1305") return true;
  if ((node.TransferProtocol === "h2" || node.TransferProtocol === "grpc") && node.TLSSecure === false) return true;
  if (node.UserID) return true;
  return false;
}

### 复现步骤

尝试使用filter_script对节点进行过滤，针对uuid判断，不知道它对应node参数中哪个字段，尝试了文档中的UserID、AlterID都没有效果

![image](https://github.com/tindy2013/subconverter/assets/66580331/e379a285-dbd1-4fcd-aacc-78e43f68d563)
![image](https://github.com/tindy2013/subconverter/assets/66580331/627bb5e6-ca70-4ab5-a684-85b3d8ac3fa0)

### 期望结果

能够读取clash配置中的uuid字段

### 实际结果

不知道对应node哪个名字，UserID、AlterID都没有效果

**Comment by viocha** [comment]
这个uuid格式错误一直处理不了，不知道怎么读取它的值
![image](https://github.com/tindy2013/subconverter/assets/66580331/ba4cea08-b279-496a-95d6-57a982ecef8e)

**Comment by viocha** [comment]
排查出错误了，UserID的D要小写，这文档质量真差
![image](https://github.com/tindy2013/subconverter/assets/66580331/09bf14a8-87f1-431b-9791-472d13e4ddfe)

**Comment by tindy2013** [comment]
node 的所有字段以 https://github.com/tindy2013/subconverter/blob/master/src/script/script_quickjs.h#L97-L146 中定义的为准。
关联 #697

**Comment by jacobin** [comment]
> 排查出错误了，UserID的D要小写，这文档质量真差

👍 同样感触，请看卑文：[有关filter_script的node的parse的问题](https://github.com/tindy2013/subconverter/issues/697)
