### ISSUE TITLE
请求增加ipv6的支持

### ISSUE THREAD

**Issue by kayloving** [tindy2013/subconverter#706]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

希望访问可以增加对ipv6的支持，只有ipv6公网的也想使用自己搭建的

**Comment by BlueHtml** [comment]
@kayloving 我修改了下，能绑定ipv6了。你可以在[这里](https://github.com/BlueHtml/subconverter/commit/516417eec14df756005f953fa7627a1c075c4e2d)查看代码，也可以在[这里](https://github.com/BlueHtml/subconverter/actions/runs/8029090194)直接下载编译好的文件。

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L326 修改该行以绑定到 IPv6 地址上
