### ISSUE TITLE
[BUG] quanx 里面直接填入转换地址更新订阅返回Invalid response（但贴入浏览器中返回的配置文件正文没问题）

### ISSUE THREAD

**Issue by qhgary** [tindy2013/subconverter#710]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本
docker中latest获取到的版本：
v0.8.1-eef5328

### 转换过程

clash转换quantumultx

### 转换设置

仅订阅地址用自己的，其他全部用默认pref.ini

### 复现步骤

在浏览器贴入subconverter命令得到转换后的配置文件正文，全选贴入quantumultx里面一切正常。
但是把该地址贴入quantumultx的订阅里面，更新时会显示“invalid response”

测试clash或者surfboard直接贴入链接都没问题，就是quantumultx有问题。quanx的版本为最新1.4.2-817

### 期望结果

更新正常

### 实际结果

invalid response

### 错误信息

```shell
invalid response
```

**Comment by tindy2013** [comment]
Quantumulut X 订阅请设置 nodelist=true

**Comment by qhgary** [comment]
> Quantumulut X 订阅请设置 nodelist=true

你说的是list参数吧，但是如果设置list=true以后，quanx就拿不到模版内容了，比如我在all_base.tpl里面quanx部分定义的filter_remote, 以及dns等一些内容。

**Comment by captaincool886** [comment]
你解决了么，我有同样问题,怎么解决的？

**Comment by sjnuowen** [comment]
请问您解决了吗
