### ISSUE TITLE
[Feature] 自动 target 能否添加 clash verge 的 user agent

### ISSUE THREAD

**Issue by SummonHIM** [tindy2013/subconverter#712]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

为UAMatchList添加 clash verge 的 user agent。

### 可能的解决方案

```C++
{"clash-verge","","","clash",true},
```
verge的ua是`clash-verge/v版本号` [（代码）](https://github.com/clash-verge-rev/clash-verge-rev/blob/main/src-tauri/src/config/prfitem.rs#L219)

应该大部分版本号都支持new rule吧？

**Comment by Masaiki** [comment]
@SummonHIM 嗯？直接提个PR不就好了

**Comment by SummonHIM** [comment]
> @SummonHIM 嗯？直接提个PR不就好了

version_match 是指定版本号regex吗。还有version_target是？

**Comment by Masaiki** [comment]
@SummonHIM 瞅了一眼 这里 version_match 匹配 UA 中的版本号 version_target 指定了最低版本
