### ISSUE TITLE
[BUG] 使用profile时，subconverter -g --artifact 出错

### ISSUE THREAD

**Issue by redjumper** [tindy2013/subconverter#719]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.8.1-eef5328 (docker)

### 转换过程

使用artifact生成配置文件文本

### 转换设置

generate.ini文件配置如下

```
[test]
path=output.conf
target=surge
ver=4
url=ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpwYXNzd29yZA@www.example.com:1080#Example

[clash_profile]
path=config.yaml
profile=profiles/example_profile.ini
```
example_profile.ini文件在/base/profiles下存在，配置如下
```
[Profile]
target=clash
url=xxxx
config=config/xxxx.ini
udp=true
new_name=true
```
subconverter -g --artifact "clash_profile"时会报错Reason: Profile not found

### 复现步骤

如上

### 期望结果

0.7.2版本没有这个问题。能够正确生成config.yaml

### 实际结果

把profile文件直接写入generate.ini，然后subconverter -g --artifact "clash_profile"可以正常生成config.yaml
```
[test]
path=output.conf
target=surge
ver=4
url=ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpwYXNzd29yZA@www.example.com:1080#Example

[clash_profile]
path=config.yaml
target=clash
url=xxxx
config=config/xxxx.ini
udp=true
new_name=true
```

### 错误信息

```shell
[ERRO] Artifact 'clash_profile' generate ERROR! Reason: Profile not found
```

**Comment by tindy2013** [comment]
提交 [535d1d0](https://github.com/tindy2013/subconverter/commit/535d1d01e1761edb035db9c9174a5658a8933c3c) 已修复该问题

**Comment by redjumper** [comment]
感谢
