### ISSUE TITLE
[BUG] quanx_rule_base 似乎只有在值为 URL 或者 base/quanx.conf 才会生效

### ISSUE THREAD

**Issue by ihainan** [tindy2013/subconverter#723]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

latest docker image - d015ecda67d0

### 转换过程

V2RAY 订阅转换成 Quantumult X 订阅

### 转换设置

profile 如下：

```
[Profile]
target=quanx
url=proxies/v2ray.list
config=custom_config/pref.ini
udp=true
expand=true
```

pref.ini 如下：

```
[custom]

; .. 省略
; 以下两种设置生效
quanx_rule_base=base/quanx.conf ; docker 挂载（覆盖）修改后的 quanx.conf
quanx_rule_base=http://xxx.com/quanx.conf ; 相同文件，URL 方式 获取

; 以下设置不生效
quanx_rule_base=custom_sub_template/quanx.conf ; custom_sub_template 目录通过 docker 挂载，确定过 docker container 内文件存在，内容正确
```

### 复现步骤

获取转换后的订阅文件：`http://xxx.com/getprofile?name=profiles/quanx.ini&token=xxx`。

以下两种 quanx_rule_base 生效：

```
quanx_rule_base=base/quanx.conf ; 修改后的 quanx.conf
quanx_rule_base=http://xxx.com/quanx.conf ; URL 方式
```

但是一旦指定其他目录下的文件，就不会生效，比如：

```
quanx_rule_base=custom_sub_template/quanx.conf ; custom_sub_template 目录通过 docker 挂载，确定过 docker container 内文件存在，内容正确
```

### 期望结果

获取到正确的订阅文件。

### 实际结果

参见上面描述。

**Comment by tindy2013** [comment]
https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L43 修改该设置以调整允许加载 base 文件的路径
