### ISSUE TITLE
2020.02.15的“Optimize codes”更新后，src/misc.cpp的一点问题

### ISSUE THREAD

**Issue by nftbty** [tindy2013/subconverter#74]
问题是最近自己编译时报错发现的，然后查了一下历次的commits，发现是2020年02月15日的一个“Optimize codes” Commit引入的，链接如下：
 [https://github.com/tindy2013/subconverter/commit/e8624a7d256fdad84f7ec202e344ee0aa3a119dd#diff-718077d5c48933b84cfa39dd863e1461](url)
在`#ifdef USE_STD_REGEX`这一段，regFind()，regReplace()，regMatch() 参数加了const，却调用了erase()。
506行
`- bool regFind(std::string src, std::string target)`
`+ bool regFind(const std::string &src, const std::string &target)`
513行 `target.erase(0, 4);`
525行
`- std::string regReplace(std::string src, std::string match, std::string rep)`
`+ std::string regReplace(const std::string &src, const std::string &match, const std::string &rep)`
533行 `match.erase(0, 4);`
546行
`- bool regMatch(std::string src, std::string match)`
`+ bool regMatch(const std::string &src, const std::string &match)`
553行 `match.erase(0, 4);`

**Comment by tindy2013** [comment]
Already fixed.
