### ISSUE TITLE
Surge通过External能支持ssr

### ISSUE THREAD

**Issue by Liquor030** [tindy2013/subconverter#75]
``` 
Node = custom, hostname, port, method, password, https://github.com/lhie1/Rules/blob/master/SSEncrypt.module?raw=true 
```

是否考虑添加这个支持呢

**Comment by Liquor030** [comment]
``` Node = custom, hostname, port, method, password, https://github.com/lhie1/Rules/blob/master/SSEncrypt.module?raw=true ```

是否考虑添加这个支持呢

**Comment by tindy2013** [comment]
1. Surge 2 Shadowsocks 配置解析与生成在初代版本中就已加入
2. 如需要在 Surge for macOS 上使用 ShadowsocksR  请在 `pref` 中设置 `surge_ssr_path` 项为 `ssr-local` 的路径

**Comment by Liquor030** [comment]
好的 感谢
