### ISSUE TITLE
在更新节点或规则时通过代理

### ISSUE THREAD

**Issue by RunningMelos** [tindy2013/subconverter#8]
因为手头有些订阅链接在通过 `http://127.0.0.1:25500/clash?url=%url%` 更新获取时速度很感人，所以想请问下是否能在 `pref.ini` 中设定例如 `http_proxy=socks5://127.0.0.1:1080` 这样的字段实现远端节点或规则时使用已有代理呢？

**Comment by tindy2013** [comment]
@RunningMelos 可以考虑加入

**Comment by RunningMelos** [comment]
> @RunningMelos 可以考虑加入

感谢🙌

**Comment by RunningMelos** [comment]
此外对最新版有个小疑问，节点名称emoji后面的 [type] 是必须的吗？就我当前手上的五个链接而言，一个订阅下的节点都会是同一个类型吧，感觉要区分的话要不考虑从类似 [ ]GROUPID 那样的下手？

**Comment by tindy2013** [comment]
@RunningMelos 已经加入开关控制type的添加

**Comment by tindy2013** [comment]
Added in commit [6d646c65](https://github.com/tindy2013/subconverter/commit/6d646c650ea8111a607fabdfa23a5698dc13cd56)

**Comment by RunningMelos** [comment]
🤦‍ 对不起我又来了，大佬未来方便做个节点排序吗（虽然看上去是个可以有但是不那么必要的功能）
🙇‍♂️ 给你添麻烦了...

****

然后还遇到了一个 BUG：

运行后直接打开 `http://127.0.0.1:25500/sub?target= surge(surfboard)&url=Proxies/xxx` 的时候不会添加规则，只会处理 base 部分、节点和节点组，此时 CMD 里显示：
```cmd
Reading preference settings...
Read preference settings completed.
Fetching node data from url 'Proxies/xxx'.
Generate target: Surge
```
需要先 `http://127.0.0.1:25500/sub?target=clash&url=Proxies/xxx`一遍，确认规则添加上了，此时CMD里显示：
```cmd
Reading preference settings...
Read preference settings completed.
Fetching node data from url 'Proxies/xxx'.
Generate target: Clash
Updating ruleset url 'Profiles\White.list' with group 'DIRECT'.
Updating ruleset url 'Profiles\China.list' with group 'DIRECT'.
Updating ruleset url 'Profiles\Windows.list' with group 'DIRECT'.
Updating ruleset url 'Profiles\GlobalMedia.list' with group '📺 影音媒体'.
Updating ruleset url 'Profiles\Telegram.list' with group '📟 电报适用'.
Updating ruleset url 'Profiles\Black.list' with group '🎯 出口选择'.
Updating ruleset url 'Profiles\Global.list' with group '🎯 出口选择'.
Adding rule 'GEOIP,CN,DIRECT'.
Adding rule 'MATCH,🎯 出口选择'.
```
接着运行 `http://127.0.0.1:25500/sub?target= surge(surfboard)&url=Proxies/xxx` 才会出现规则，尽管CMD还是显示如下，但确实刷新出来了。我的电脑环境里有多次复现。
```cmd
Reading preference settings...
Read preference settings completed.
Fetching node data from url 'Proxies/CCCAT-SS'.
Generate target: Surge
```

**Comment by tindy2013** [comment]
@RunningMelos 请确定使用最新release进行测试

**Comment by RunningMelos** [comment]
蠢的我战术后仰，对比了一下发现是把下面这个`true`了，我的理解是每次发送请求都会更新一次规则，看来错了...
```ini
;Perform a ruleset update on request
update_ruleset_on_request=true
```
🙇‍♂️🙇‍♂️🙇‍♂️ 真的不好意思，添麻烦了，咚咚咚

**Comment by tindy2013** [comment]
@RunningMelos 这个算是个bug 以后的版本会修复

**Comment by RunningMelos** [comment]
> 🤦‍ 对不起我又来了，大佬未来方便做个节点排序吗（虽然看上去是个可以有但是不那么必要的功能）
> 🙇‍♂️ 给你添麻烦了...

🤦‍♂️ 得纠正一下这个说法，现有的节点排序是建立在读取时进行对吧，那么在进行节点重命名（或者在添加Emoji）后就会出现节点再次混乱的情况，是不是可以考虑在处理的最后进行节点排序，具体情况就像如下：

|正则和 EMOJI 处理前原始名称|正则和 EMOJI 处理后显示顺序|目标期望排序顺序|
|:--|:--|:--|
|Echo - 新加坡  |  🇭🇰 香港 Cinderella|🇭🇰 香港 Cinderella|
|Mercury - 澳门  |  🇯🇵 东京 Crimson|🇭🇰 香港 Mirage|
|Mirage - 香港  |  🇸🇬 新加坡 Echo|🇭🇰 香港 Rin|
|Cinderella - 香港  |  🇰🇷 首尔 Maackia|🇯🇵 东京 Crimson|
|Rin - 香港  |  🇲🇴 澳门 Mercury|🇯🇵 东京 Setsuna (倍率:0.8)|
|Mirai - 台北  |  🇺🇸 洛杉矶 Miracle|🇰🇷 首尔 Maackia|
|Crimson - 东京  |  🇭🇰 香港 Mirage|🇲🇴 澳门 Mercury|
|Setsuna - 东京【限时8折】  |  🇹🇼 台北 Mirai|🇳🇱 阿姆斯特丹 Tulip|
|Myrica - 洛杉矶  |  🇺🇸 洛杉矶 Myrica|🇷🇺 新西伯利亚 Sabia|
|Miracle - 洛杉矶  |  🇭🇰 香港 Rin|🇸🇬 新加坡 Echo|
|Maackia - 首尔  |  🇷🇺 新西伯利亚 Sabia|🇹🇼 台北 Mirai|
|Tulip - 阿姆斯特丹  |  🇯🇵 东京 Setsuna (倍率:0.8)|🇺🇸 洛杉矶 Miracle|
|Sabia - 新西伯利亚  |  🇳🇱 阿姆斯特丹 Tulip|🇺🇸 洛杉矶 Myrica|

**Comment by tindy2013** [comment]
> 因为手头有些订阅链接在通过 `http://127.0.0.1:25500/clash?url=%url%` 更新获取时速度很感人，所以想请问下是否能在 `pref.ini` 中设定例如 `http_proxy=socks5://127.0.0.1:1080` 这样的字段实现远端节点或规则时使用已有代理呢？

已添加


> 此外对最新版有个小疑问，节点名称emoji后面的 [type] 是必须的吗？就我当前手上的五个链接而言，一个订阅下的节点都会是同一个类型吧，感觉要区分的话要不考虑从类似 [ ]GROUPID 那样的下手？

已添加


> 🤦‍ 对不起我又来了，大佬未来方便做个节点排序吗（虽然看上去是个可以有但是不那么必要的功能）
> 🙇‍♂️ 给你添麻烦了...
> 
> 然后还遇到了一个 BUG：
> 
> 运行后直接打开 `http://127.0.0.1:25500/sub?target= surge(surfboard)&url=Proxies/xxx` 的时候不会添加规则，只会处理 base 部分、节点和节点组，此时 CMD 里显示：
> 
> ```batchfile
> Reading preference settings...
> Read preference settings completed.
> Fetching node data from url 'Proxies/xxx'.
> Generate target: Surge
> ```
> 
> 需要先 `http://127.0.0.1:25500/sub?target=clash&url=Proxies/xxx`一遍，确认规则添加上了，此时CMD里显示：
> 
> ```batchfile
> Reading preference settings...
> Read preference settings completed.
> Fetching node data from url 'Proxies/xxx'.
> Generate target: Clash
> Updating ruleset url 'Profiles\White.list' with group 'DIRECT'.
> Updating ruleset url 'Profiles\China.list' with group 'DIRECT'.
> Updating ruleset url 'Profiles\Windows.list' with group 'DIRECT'.
> Updating ruleset url 'Profiles\GlobalMedia.list' with group '📺 影音媒体'.
> Updating ruleset url 'Profiles\Telegram.list' with group '📟 电报适用'.
> Updating ruleset url 'Profiles\Black.list' with group '🎯 出口选择'.
> Updating ruleset url 'Profiles\Global.list' with group '🎯 出口选择'.
> Adding rule 'GEOIP,CN,DIRECT'.
> Adding rule 'MATCH,🎯 出口选择'.
> ```
> 
> 接着运行 `http://127.0.0.1:25500/sub?target= surge(surfboard)&url=Proxies/xxx` 才会出现规则，尽管CMD还是显示如下，但确实刷新出来了。我的电脑环境里有多次复现。
> 
> ```batchfile
> Reading preference settings...
> Read preference settings completed.
> Fetching node data from url 'Proxies/xxx'.
> Generate target: Surge
> ```

发版的时候忘记修了...


> > 🤦‍ 对不起我又来了，大佬未来方便做个节点排序吗（虽然看上去是个可以有但是不那么必要的功能）
> > 🙇‍♂️ 给你添麻烦了...
> 
> 🤦‍♂️ 得纠正一下这个说法，现有的节点排序是建立在读取时进行对吧，那么在进行节点重命名（或者在添加Emoji）后就会出现节点再次混乱的情况，是不是可以考虑在处理的最后进行节点排序，具体情况就像如下：
> 
> 正则和 EMOJI 处理前原始名称	正则和 EMOJI 处理后显示顺序	目标期望排序顺序
> Echo - 新加坡	🇭🇰 香港 Cinderella	🇭🇰 香港 Cinderella
> Mercury - 澳门	🇯🇵 东京 Crimson	🇭🇰 香港 Mirage
> Mirage - 香港	🇸🇬 新加坡 Echo	🇭🇰 香港 Rin
> Cinderella - 香港	🇰🇷 首尔 Maackia	🇯🇵 东京 Crimson
> Rin - 香港	🇲🇴 澳门 Mercury	🇯🇵 东京 Setsuna (倍率:0.8)
> Mirai - 台北	🇺🇸 洛杉矶 Miracle	🇰🇷 首尔 Maackia
> Crimson - 东京	🇭🇰 香港 Mirage	🇲🇴 澳门 Mercury
> Setsuna - 东京【限时8折】	🇹🇼 台北 Mirai	🇳🇱 阿姆斯特丹 Tulip
> Myrica - 洛杉矶	🇺🇸 洛杉矶 Myrica	🇷🇺 新西伯利亚 Sabia
> Miracle - 洛杉矶	🇭🇰 香港 Rin	🇸🇬 新加坡 Echo
> Maackia - 首尔	🇷🇺 新西伯利亚 Sabia	🇹🇼 台北 Mirai
> Tulip - 阿姆斯特丹	🇯🇵 东京 Setsuna (倍率:0.8)	🇺🇸 洛杉矶 Miracle
> Sabia - 新西伯利亚	🇳🇱 阿姆斯特丹 Tulip	🇺🇸 洛杉矶 Myrica

以后再加入

**Comment by RunningMelos** [comment]
@tindy2013 体验超棒！大佬辛苦了~

**Comment by RunningMelos** [comment]
`simple_base.yml` 中的 这一段[(L7-L32)](https://github.com/tindy2013/subconverter/blob/master/simple_base.yml#L7-L32) 可以不加，因为 `CFW` 在加载处理后的 `Profiles/xxxx.yml` 文件时只会读取 `Proxy/Proxy Group/Rule/dns` 这几个字段 <sup>[1]</sup>

[1]: 配置文件 · Clash for Windows  https://docs.cfw.lbyczf.com/contents/configfile.html

**Comment by tindy2013** [comment]
谢谢反馈 未来将去除

**Comment by tindy2013** [comment]
> > 🤦‍ 对不起我又来了，大佬未来方便做个节点排序吗（虽然看上去是个可以有但是不那么必要的功能）
> > 🙇‍♂️ 给你添麻烦了...
> 
> 🤦‍♂️ 得纠正一下这个说法，现有的节点排序是建立在读取时进行对吧，那么在进行节点重命名（或者在添加Emoji）后就会出现节点再次混乱的情况，是不是可以考虑在处理的最后进行节点排序，具体情况就像如下：
> 
> 正则和 EMOJI 处理前原始名称	正则和 EMOJI 处理后显示顺序	目标期望排序顺序
> Echo - 新加坡	🇭🇰 香港 Cinderella	🇭🇰 香港 Cinderella
> Mercury - 澳门	🇯🇵 东京 Crimson	🇭🇰 香港 Mirage
> Mirage - 香港	🇸🇬 新加坡 Echo	🇭🇰 香港 Rin
> Cinderella - 香港	🇰🇷 首尔 Maackia	🇯🇵 东京 Crimson
> Rin - 香港	🇲🇴 澳门 Mercury	🇯🇵 东京 Setsuna (倍率:0.8)
> Mirai - 台北	🇺🇸 洛杉矶 Miracle	🇰🇷 首尔 Maackia
> Crimson - 东京	🇭🇰 香港 Mirage	🇲🇴 澳门 Mercury
> Setsuna - 东京【限时8折】	🇹🇼 台北 Mirai	🇳🇱 阿姆斯特丹 Tulip
> Myrica - 洛杉矶	🇺🇸 洛杉矶 Myrica	🇷🇺 新西伯利亚 Sabia
> Miracle - 洛杉矶	🇭🇰 香港 Rin	🇸🇬 新加坡 Echo
> Maackia - 首尔	🇷🇺 新西伯利亚 Sabia	🇹🇼 台北 Mirai
> Tulip - 阿姆斯特丹	🇯🇵 东京 Setsuna (倍率:0.8)	🇺🇸 洛杉矶 Miracle
> Sabia - 新西伯利亚	🇳🇱 阿姆斯特丹 Tulip	🇺🇸 洛杉矶 Myrica

added in commit [6a90348](https://github.com/tindy2013/subconverter/commit/6a90348a0a16ccf6463cbe424c7bf77872c60a0b)
