### ISSUE TITLE
[Feature] <Allow to define "MANAGED_PREFIX" environment variable>

### ISSUE THREAD

**Issue by LedPeach** [tindy2013/subconverter#803]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

I'm hosting subconverter on my website and using nginx reverse proxy pointing to a certain path `/path`. So the subconverter is running on `https://my.domain.tld/path`. But if I do `https://my.domain.tld/path/sub?`, the subconverter backend receives a `/path/sub?` handle instead of `/sub?`. 

Is there a way to define the "MANAGED_PREFIX" environment variable so I can use it with a `/path` prefix?

Here you have included this variable "MANAGED_PREFIX" but I can't find it anywhere else. 
https://github.com/tindy2013/subconverter/blob/c207bfc1f03185114467b50a4ce97f2d0394c782/src/main.cpp#L170-L173

Is it possible to define it by adding this variable in the `pref.toml`/`.ini` file? For instance, 
```
version = 1
[common]
# API mode, set to true to prevent loading local subscriptions or serving local files directly
api_mode = false

# Access token used for performing critical action through Web interface
api_access_token = "password"

# Comment
managed_prefix = "/path"
```

**Comment by tindy2013** [comment]
@LedPeach https://github.com/tindy2013/subconverter/blob/master/base/pref.example.toml#L159

**Comment by LedPeach** [comment]
Great. Thx for the help.

**Comment by LedPeach** [comment]
Alternatively, I solved it by adding ```rewrite /path(/|$)(.*) /$2 break;``` in the nginx conf
