### ISSUE TITLE
linux版本在转换成Surge配置时出现问题

### ISSUE THREAD

**Issue by qwaszxcvbdf** [tindy2013/subconverter#83]
在转换其他代理软件是， rule部分一切正常， 但是当转换Surge时， rule部分出现异常， 哪怕是在作者本人的api转换时也是这样
出现的问题：
![image](https://user-images.githubusercontent.com/36601614/76579143-17b26d80-6506-11ea-950c-4c4ffdd9ed9d.png)
在转换其他软件的时候，　一切正常

**Comment by L0snight** [comment]
从你的图和描述没有看出任何问题。

**Comment by qwaszxcvbdf** [comment]
![image](https://user-images.githubusercontent.com/36601614/76581704-4d0f8900-650f-11ea-8d27-c7a44e3d8ac5.png)
这一张图片是转换为clash配置时的rule部分，　正常来讲应该都是这样
但是当我试图转换为surge配置时，　就变成了这样
![image](https://user-images.githubusercontent.com/36601614/76581775-81834500-650f-11ea-9faa-be68e8d36d9f.png)

我的意思是，　转换为surge配置时，　没有成功转换出rule部分

**Comment by L0snight** [comment]
surge 3以后，surge本来就支持以RULE-SET来导入外部规则，这是特性。

**Comment by qwaszxcvbdf** [comment]
<img width="698" alt="图片" src="https://user-images.githubusercontent.com/36601614/76582868-85649680-6512-11ea-9597-524f8f2c8f4b.png">
好吧我可能还是没有描述清楚， 我现在的目标是从远程服务器导入配置， 但是导入之后rule部分是这样的报错， 如果使用 surge&ver=2 的话会导致我无法获取到节点（我全是v2r)， 而且这个问题是我更新了subconverter的版本之后才出现的, 之前的版本没有这个问题， 我再去试试看
