### ISSUE TITLE
V2RAY 加密方式转换后都是auto， 是我姿势不对么？

### ISSUE THREAD

**Issue by ceozero** [tindy2013/subconverter#85]
{
  "v": "2",
  "ps": "xxx.xxx.xxx",
  "add": "xxx.xxx.xxx",
  "port": "443",
  "id": "9d872920-b9f0-xxxx-91ac-4a978d4xxxxx",
  "aid": "550",
  "net": "ws",
  "cipher": "none",
  "type": "none",
  "host": "xxx.xxx.xxx",
  "path": "/111",
  "tls": "tls"
}

cipher头写错了？ 还是不管怎么写都是auto?

**Comment by tindy2013** [comment]
1. 根据 [v2rayN VMess 链接 ver.2 的说明](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))  该链接格式不包含 cipher 信息
2. VMess 协议的加密是由客户端与服务端自动协商的  无需手动指定
3. 如果无论如何都要指定的话  请使用 Clash 或 Quantumult X 的订阅作为源节点信息

**Comment by ceozero** [comment]
> 1. 根据 [v2rayN VMess 链接 ver.2 的说明](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))  该链接格式不包含 cipher 信息
> 2. VMess 协议的加密是由客户端与服务端自动协商的  无需手动指定
> 3. 如果无论如何都要指定的话  请使用 Clash 或 Quantumult X 的订阅作为源节点信息

明白了。谢谢。
