### ISSUE TITLE
HTTP/Socks 链接 空用户名或密码 类型

### ISSUE THREAD

**Issue by Wittoy** [tindy2013/subconverter#87]
[支持类型](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E6%94%AF%E6%8C%81%E7%B1%BB%E5%9E%8Bl)中的类 TG 代理的 HTTP/Socks 链接，在无用户名或密码的情况下如何转换

**Comment by tindy2013** [comment]
去除该参数即可

**Comment by Wittoy** [comment]
删除后Clash参数输出变成`{name: xx, server: xx, port: xx, type: http, username: "", password: !<str> "", tls: false}`

**Comment by tindy2013** [comment]
不会影响 不用理会
