### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by taowuhan** [tindy2013/subconverter#88]
浏览器提示 Forbidden，

**Comment by taowuhan** [comment]
当通过上述 进阶链接 配置好订阅链接后，通常会使得链接十分冗长和难以记忆，此时可以考虑使用配置档案。

**Comment by taowuhan** [comment]
http://127.0.0.1:25500/getprofile?name=profiles/diy.ini&token=666666

**Comment by CareyWang** [comment]
@taowuhan 使用短链接

**Comment by taowuhan** [comment]
OK
