### ISSUE TITLE
http节点转换成quanx托管后丢失

### ISSUE THREAD

**Issue by ericzhaomac** [tindy2013/subconverter#90]
如题

在添加类TG的http代理时候发现的问题，转换成Clash订阅没有这个问题。

**Comment by tindy2013** [comment]
@ericzhaomac 目前最新 release 未正常输出 HTTP 节点到 Quantumult X 订阅中 将在下个版本修复

**Comment by ericzhaomac** [comment]
@tindy2013 感谢~
