### ISSUE TITLE
是否可增加Trojan支援？

### ISSUE THREAD

**Issue by reechang** [tindy2013/subconverter#92]
是否可考慮增加解析Trojan協議？目前Clash已經支援Trojan協議。

**Comment by CareyWang** [comment]
@reechang 已支持

**Comment by tindy2013** [comment]
Commit [17ef7c6](https://github.com/tindy2013/subconverter/commit/17ef7c6150b3a5800ba96ebe3f9c316f683f7bc2) [7e48978](https://github.com/tindy2013/subconverter/commit/7e489788e32a6483f09e7f112f46fe56499d3812) [b9fb6b8](https://github.com/tindy2013/subconverter/commit/b9fb6b8d7d271a28d781c06d5e302f05039adcd8)

**Comment by reechang** [comment]
好的，謝謝。等待下個Release。

**Comment by xiaolilir** [comment]
你好，trojan订阅的配置格式怎么填写？
