### ISSUE TITLE
Surge3的load-balance模式不能被正确地转换

### ISSUE THREAD

**Issue by bingsmocha** [tindy2013/subconverter#97]
在结尾为.ini的文件中添加如下的proxy_group的时候：
    custom_proxy_group=LoadBalance\`load-balance\`.*\`http://www.gstatic.com/generate_204`300
通过surge上的install from URL不能成功导入整个的surge配置，会提示不能识别LoadBalance这个Proxy_group

附：Surge配置详解（包含load-balance在配置文件中的用法） https://zhuangzhuang.cf/2018-11-14/surge/

**Comment by tindy2013** [comment]
目前版本暂时不会添加 Load Balance 分组到 Surge 配置文件中 下个版本将修复
