### ISSUE TITLE
SSR订阅地址为TXT文件不能截取节点

### ISSUE THREAD

**Issue by rtcheng** [tindy2013/subconverter#98]
比如：地址转码后为https%3A%2F%2xxxxx%2xxxx%2Ftxt%2xxx.txt，txt内容为base64编码的节点信息，转换后节点是空的。

**Comment by rtcheng** [comment]
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
Proxy: ~
Proxy Group:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:

**Comment by tindy2013** [comment]
订阅中的 ShadowsocksR 节点在输出类型为 Clash 时会被过滤 如有需要请使用 ClashR 输出类型

**Comment by rtcheng** [comment]
问题解决了，谢谢。
