### ISSUE TITLE
FEATURE REQUEST: sssub类型下，添加route参数。

### ISSUE THREAD

**Issue by HuanMeng0** [tindy2013/subconverter#99]
route参数用于Shadowsocks Android客户端，用于定义代理模式是全局、绕过局域网或绕过局域网和中国地址等。

除了route参数，还有proxy_apps、remote_dns、udpdns等参数。

提出这个需求的原因是，阿里巴巴的软件会检测VPN流量，而shadowsocks客户端默认是全局路由，触发次数过多可能会引发风控进而被完全封锁账号。
相关链接：https://www.v2ex.com/t/655557

**Comment by tindy2013** [comment]
Added in commit [a3e337c](https://github.com/tindy2013/subconverter/commit/a3e337c56965edc92390a0ca42348cbd9fcb9401)
